export const formElements = {
    department : `button[id='headlessui-listbox-button-:re2:']`,
    term:'input[name="term"]',
    counterParty : "input[name='counter_party']",
    monetaryValue :"input[name='monetary_value']",
    currencyNotAUD : "input[name='monetary_value_currency']",
    other : 'input[name="other_currency"]',
    splTermsText : 'div[data-placeholder="e.g. exclusive agreement?"]',
    termination : 'div[data-placeholder="How can the agreement be ended"]',
    risk : `div[data-placeholder="Are there special reputational risks which need to be considered – e.g. Nature of the parties or subject matter?"]`,
    search : `input[placeholder="Search by Form Id or Counter Party"]`,
    profile : `button[id='headlessui-menu-button-:rk:'] span svg`,
    forms : `button[id="view-forms-menu"]`,
    configuration : `button[id="view-configuration"]`,
    dashboard : `button[id="view-dashboard-menu"]`,
    myRequestTab : `button[id='view-my-requests-tab']`,
    moduleMenu : `button[id^='headlessui-menu-button-:re:']`,
    teamRequestTab : `button[id="view-team-requests-tab"]`,
    approveRequestTab : `button[id="view-approve-request-tab"]`,
    eSignRequestTab : `button[id="view-e-sign-requests-tab"]`,
    approveListTab : `button[id="view-my-approved-requests-tab"]`,
    settings : `div[id='headlessui-menu-item-:r1r:'] button[type='button']`,
    contractApproval : `div[id='headlessui-menu-item-:r1q:'] div[class='flex gap-2 items-center']`,
    userSettings : `button[id="view-user-settings"]`,
    departmentSettings : `button[id="view-department-settings"]`,
    roleSettings: `button[id="view-role-settings"]`,
    permissionSettings : `button[id="view-permission-settings"]`,
    moduleSettings : `button[id="view-module-settings"]`,
    // approveRequestTab: 'button[aria-selected="true"]',
    monetaryValueDetailsPage: '//label[text()="Monetary Value (in AUD, excluding Australian GST)"]/parent::div/parent::div/div[2]/span',
    techBypass: '//label[contains(text(), "software")]/parent::div/span/label',
    typeOfApproval: '//label[text()="Type of Approval being sought"]/parent::*/parent::*/div[2]/label',
    egm: '//span[text()="EGM"]' ,
    legal: '//span[text()="Legal"]',
    technology: '//span[text()="Technology"]',
    insurance:'//span[text()="Insurance"]',
    finance: '//span[text()="Finance"]',
    cfo : '//span[text()="CFO"]',
    ceo : '//span[text()="CEO"]' ,
    okayButton : '(//button[text()="Okay"])[4]' ,
    rejectReason : '//textarea[@placeholder="Kindly provide a reason *"]' ,
    rejectButton: '//button[@id="reject"]' ,
    formId : '//table/tbody/tr/td/button/p' ,
    esignYes : '//div[@class="flex gap-4"]/label[1]/div' ,
    esignNo : '//div[@class="flex gap-4"]/label[2]/div',
    witnessNo : '(//div[@class="flex gap-4"]/label[2]/div)[2]',
    witnessYes : '(//div[@class="flex gap-4"]/label[1]/div)[2]',
    witnessName : 'input[placeholder="Witness Name"]' ,
    witnessId : 'input[placeholder="Witness Email ID"]',
    approveButton: '(//button[@id="approve"])[2]'
}