import { ObjectId, Db } from "mongodb";

const rolesData = [
  {
    _id: new ObjectId("676435d455a50e076bedab81"),
    name: "First Reviewer",
    code: "first-reviewer",
    description: "First Reviewer / Pre EGM Approver",
    permissions: [
      {
        _id: new ObjectId("676d3997ccffb83c5ccf5d9b"),
        moduleId: new ObjectId("65e3579de0ca70fe8f2e148e"),
        permissionCode: "view-forms-menu",
        permissionName: "View Forms Menu",
        moduleCode: "contract",
        moduleName: "Contract Approval",
        moduleStatus: true,
        description: "Allows access to Forms Menu page",
        status: true,
        updatedBy: "vrameshbapu@nrl.com.au",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        _id: new ObjectId("676d563eccffb83c5ccf5da5"),
        moduleId: new ObjectId("65e3579de0ca70fe8f2e148e"),
        permissionCode: "view-my-requests-tab",
        permissionName: "View My Requests Tab",
        moduleCode: "contract",
        moduleName: "Contract Approval",
        moduleStatus: true,
        description: "Allows access to enable My Requests Tab",
        status: true,
        updatedBy: "vrameshbapu@nrl.com.au",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        _id: new ObjectId("676d3e3cccffb83c5ccf5da2"),
        moduleId: new ObjectId("65e3579de0ca70fe8f2e148e"),
        permissionCode: "view-approve-request-tab",
        permissionName: "View Approve Requests Tab",
        moduleCode: "contract",
        moduleName: "Contract Approval",
        moduleStatus: true,
        description: "Allows access to enable Approve Requests Tab",
        status: true,
        updatedBy: "vrameshbapu@nrl.com.au",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        _id: new ObjectId("67e268a608b3f2bc83885e6c"),
        moduleId: new ObjectId("65e3579de0ca70fe8f2e148e"),
        permissionCode: "view-e-sign-requests-tab",
        permissionName: "View E Sign Requests Tab",
        moduleCode: "contract",
        moduleName: "Contract Approval",
        moduleStatus: true,
        description: "Allows access to enable E Sign Requests Tab",
        status: true,
        updatedBy: "vrameshbapu@nrl.com.au",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        _id: new ObjectId("67e2888bdbce9cd169ecadc8"),
        moduleId: new ObjectId("65e3579de0ca70fe8f2e148e"),
        permissionCode: "view-my-approved-requests-tab",
        permissionName: "View My Approved Requests Tab",
        moduleCode: "contract",
        moduleName: "Contract Approval",
        moduleStatus: true,
        description: "Allows access to enable My Approved Requests Tab",
        status: true,
        updatedBy: "vrameshbapu@nrl.com.au",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    status: true,
    moduleId: [new ObjectId("65e3579de0ca70fe8f2e148e")],
    createdAt: new Date("2024-02-28T11:06:18.974Z"),
    createdBy: "bbharathivel@nrl.com.au",
    updatedAt: new Date(),
    updatedBy: "bbharathivel@nrl.com.au",
  },
  {
    _id: new ObjectId("65def3f1de3deddff04f79a7"),
    name: "Executive General Manager",
    code: "executive-general-manager",
    description: "Executive General Manager",
    status: true,
    moduleId: [new ObjectId("65e3579de0ca70fe8f2e148e")],
    permissions: [
      {
        _id: new ObjectId("676d3997ccffb83c5ccf5d9b"),
        moduleId: new ObjectId("65e3579de0ca70fe8f2e148e"),
        permissionCode: "view-forms-menu",
        permissionName: "View Forms Menu",
        moduleCode: "contract",
        moduleName: "Contract Approval",
        moduleStatus: true,
        description: "Allows access to Forms Menu page",
        status: true,
        updatedBy: "vrameshbapu@nrl.com.au",
        createdAt: new Date("2025-04-10T08:11:33.992Z"),
        updatedAt: new Date("2025-04-10T08:11:33.992Z"),
      },
      {
        _id: new ObjectId("676d563eccffb83c5ccf5da5"),
        moduleId: new ObjectId("65e3579de0ca70fe8f2e148e"),
        permissionCode: "view-my-requests-tab",
        permissionName: "View My Requests Tab",
        moduleCode: "contract",
        moduleName: "Contract Approval",
        moduleStatus: true,
        description: "Allows access to enable My Requests Tab",
        status: true,
        updatedBy: "vrameshbapu@nrl.com.au",
        createdAt: new Date("2025-04-10T08:11:33.992Z"),
        updatedAt: new Date("2025-04-10T08:11:33.992Z"),
      },
      {
        _id: new ObjectId("676d3e3cccffb83c5ccf5da2"),
        moduleId: new ObjectId("65e3579de0ca70fe8f2e148e"),
        permissionCode: "view-approve-request-tab",
        permissionName: "View Approve Requests Tab",
        moduleCode: "contract",
        moduleName: "Contract Approval",
        moduleStatus: true,
        description: "Allows access to enable Approve Requests Tab",
        status: true,
        updatedBy: "vrameshbapu@nrl.com.au",
        createdAt: new Date("2025-04-10T08:11:33.992Z"),
        updatedAt: new Date("2025-04-10T08:11:33.992Z"),
      },
      {
        _id: new ObjectId("67e268a608b3f2bc83885e6c"),
        moduleId: new ObjectId("65e3579de0ca70fe8f2e148e"),
        permissionCode: "view-e-sign-requests-tab",
        permissionName: "View E Sign Requests Tab",
        moduleCode: "contract",
        moduleName: "Contract Approval",
        moduleStatus: true,
        description: "Allows access to enable E Sign Requests Tab",
        status: true,
        updatedBy: "vrameshbapu@nrl.com.au",
        createdAt: new Date("2025-04-10T08:11:33.992Z"),
        updatedAt: new Date("2025-04-10T08:11:33.992Z"),
      },
      {
        _id: new ObjectId("67e2888bdbce9cd169ecadc8"),
        moduleId: new ObjectId("65e3579de0ca70fe8f2e148e"),
        permissionCode: "view-my-approved-requests-tab",
        permissionName: "View My Approved Requests Tab",
        moduleCode: "contract",
        moduleName: "Contract Approval",
        moduleStatus: true,
        description: "Allows access to enable My Approved Requests Tab",
        status: true,
        updatedBy: "vrameshbapu@nrl.com.au",
        createdAt: new Date("2025-04-10T08:11:33.992Z"),
        updatedAt: new Date("2025-04-10T08:11:33.992Z"),
      },
    ],
    createdBy: "mmurugesan@nrl.com.au",
    updatedBy: "mmurugesan@nrl.com.au",
    createdAt: new Date("2024-02-28T11:06:18.974Z"),
    updatedAt: new Date("2025-04-10T08:11:33.992Z"),
  },
  {
    _id: new ObjectId("65def54ade3deddff04f79ad"),
    name: "CFO",
    code: "cfo",
    description: "Chief Financial Officer",
    status: true,
    moduleId: [new ObjectId("65e3579de0ca70fe8f2e148e")],
    permissions: [
      {
        _id: new ObjectId("676d3997ccffb83c5ccf5d9b"),
        moduleId: new ObjectId("65e3579de0ca70fe8f2e148e"),
        permissionCode: "view-forms-menu",
        permissionName: "View Forms Menu",
        moduleCode: "contract",
        moduleName: "Contract Approval",
        moduleStatus: true,
        description: "Allows access to Forms Menu page",
        status: true,
        updatedBy: "vrameshbapu@nrl.com.au",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        _id: new ObjectId("676d563eccffb83c5ccf5da5"),
        moduleId: new ObjectId("65e3579de0ca70fe8f2e148e"),
        permissionCode: "view-my-requests-tab",
        permissionName: "View My Requests Tab",
        moduleCode: "contract",
        moduleName: "Contract Approval",
        moduleStatus: true,
        description: "Allows access to enable My Requests Tab",
        status: true,
        updatedBy: "vrameshbapu@nrl.com.au",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        _id: new ObjectId("676d3e3cccffb83c5ccf5da2"),
        moduleId: new ObjectId("65e3579de0ca70fe8f2e148e"),
        permissionCode: "view-approve-request-tab",
        permissionName: "View Approve Requests Tab",
        moduleCode: "contract",
        moduleName: "Contract Approval",
        moduleStatus: true,
        description: "Allows access to enable Approve Requests Tab",
        status: true,
        updatedBy: "vrameshbapu@nrl.com.au",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        _id: new ObjectId("676d393accffb83c5ccf5d9a"),
        moduleId: new ObjectId("65e3579de0ca70fe8f2e148e"),
        permissionCode: "view-dashboard-menu",
        permissionName: "View Dashboard Menu",
        moduleCode: "contract",
        moduleName: "Contract Approval",
        moduleStatus: true,
        description: "Allows access to Dashboard page",
        status: true,
        updatedBy: "vrameshbapu@nrl.com.au",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        _id: new ObjectId("67e268a608b3f2bc83885e6c"),
        moduleId: new ObjectId("65e3579de0ca70fe8f2e148e"),
        permissionCode: "view-e-sign-requests-tab",
        permissionName: "View E Sign Requests Tab",
        moduleCode: "contract",
        moduleName: "Contract Approval",
        moduleStatus: true,
        description: "Allows access to enable E Sign Requests Tab",
        status: true,
        updatedBy: "vrameshbapu@nrl.com.au",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        _id: new ObjectId("67e2888bdbce9cd169ecadc8"),
        moduleId: new ObjectId("65e3579de0ca70fe8f2e148e"),
        permissionCode: "view-my-approved-requests-tab",
        permissionName: "View My Approved Requests Tab",
        moduleCode: "contract",
        moduleName: "Contract Approval",
        moduleStatus: true,
        description: "Allows access to enable My Approved Requests Tab",
        status: true,
        updatedBy: "vrameshbapu@nrl.com.au",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    createdBy: "mmurugesan@nrl.com.au",
    updatedBy: "mmurugesan@nrl.com.au",
    createdAt: new Date("2024-02-28T11:06:18.974Z"),
    updatedAt: new Date(),
  },
  {
    _id: new ObjectId("65def4b2de3deddff04f79a9"),
    name: "Insurance Admin",
    code: "insurance-admin",
    description: "Insurance Admin",
    status: true,
    moduleId: [new ObjectId("65e3579de0ca70fe8f2e148e")],
    permissions: [
      {
        _id: new ObjectId("676d3997ccffb83c5ccf5d9b"),
        moduleId: new ObjectId("65e3579de0ca70fe8f2e148e"),
        permissionCode: "view-forms-menu",
        permissionName: "View Forms Menu",
        moduleCode: "contract",
        moduleName: "Contract Approval",
        moduleStatus: true,
        description: "Allows access to Forms Menu page",
        status: true,
        updatedBy: "vrameshbapu@nrl.com.au",
        createdAt: new Date("2025-04-10T08:11:33.992Z"),
        updatedAt: new Date("2025-04-10T08:11:33.992Z"),
      },
      {
        _id: new ObjectId("676d563eccffb83c5ccf5da5"),
        moduleId: new ObjectId("65e3579de0ca70fe8f2e148e"),
        permissionCode: "view-my-requests-tab",
        permissionName: "View My Requests Tab",
        moduleCode: "contract",
        moduleName: "Contract Approval",
        moduleStatus: true,
        description: "Allows access to enable My Requests Tab",
        status: true,
        updatedBy: "vrameshbapu@nrl.com.au",
        createdAt: new Date("2025-04-10T08:11:33.992Z"),
        updatedAt: new Date("2025-04-10T08:11:33.992Z"),
      },
      {
        _id: new ObjectId("676d3e3cccffb83c5ccf5da2"),
        moduleId: new ObjectId("65e3579de0ca70fe8f2e148e"),
        permissionCode: "view-approve-request-tab",
        permissionName: "View Approve Requests Tab",
        moduleCode: "contract",
        moduleName: "Contract Approval",
        moduleStatus: true,
        description: "Allows access to enable Approve Requests Tab",
        status: true,
        updatedBy: "vrameshbapu@nrl.com.au",
        createdAt: new Date("2025-04-10T08:11:33.992Z"),
        updatedAt: new Date("2025-04-10T08:11:33.992Z"),
      },
      {
        _id: new ObjectId("67e268a608b3f2bc83885e6c"),
        moduleId: new ObjectId("65e3579de0ca70fe8f2e148e"),
        permissionCode: "view-e-sign-requests-tab",
        permissionName: "View E Sign Requests Tab",
        moduleCode: "contract",
        moduleName: "Contract Approval",
        moduleStatus: true,
        description: "Allows access to enable E Sign Requests Tab",
        status: true,
        updatedBy: "vrameshbapu@nrl.com.au",
        createdAt: new Date("2025-04-10T08:11:33.992Z"),
        updatedAt: new Date("2025-04-10T08:11:33.992Z"),
      },
      {
        _id: new ObjectId("67e2888bdbce9cd169ecadc8"),
        moduleId: new ObjectId("65e3579de0ca70fe8f2e148e"),
        permissionCode: "view-my-approved-requests-tab",
        permissionName: "View My Approved Requests Tab",
        moduleCode: "contract",
        moduleName: "Contract Approval",
        moduleStatus: true,
        description: "Allows access to enable My Approved Requests Tab",
        status: true,
        updatedBy: "vrameshbapu@nrl.com.au",
        createdAt: new Date("2025-04-10T08:11:33.992Z"),
        updatedAt: new Date("2025-04-10T08:11:33.992Z"),
      },
    ],
    createdBy: "bbharathivel@nrl.com.au",
    updatedBy: "mmurugesan@nrl.com.au",
    createdAt: new Date("2024-02-28T11:06:18.974Z"),
    updatedAt: new Date("2025-04-10T08:11:33.992Z"),
  },
  {
    _id: new ObjectId("65def477de3deddff04f79a8"),
    name: "Technology Admin",
    code: "technology-admin",
    description: "Technology Admin",
    status: true,
    moduleId: [new ObjectId("65e3579de0ca70fe8f2e148e")],
    permissions: [
      {
        _id: new ObjectId("676d3997ccffb83c5ccf5d9b"),
        moduleId: new ObjectId("65e3579de0ca70fe8f2e148e"),
        permissionCode: "view-forms-menu",
        permissionName: "View Forms Menu",
        moduleCode: "contract",
        moduleName: "Contract Approval",
        moduleStatus: true,
        description: "Allows access to Forms Menu page",
        status: true,
        updatedBy: "vrameshbapu@nrl.com.au",
        createdAt: new Date("2025-04-10T08:11:33.996Z"),
        updatedAt: new Date("2025-04-10T08:11:33.996Z"),
      },
      {
        _id: new ObjectId("676d563eccffb83c5ccf5da5"),
        moduleId: new ObjectId("65e3579de0ca70fe8f2e148e"),
        permissionCode: "view-my-requests-tab",
        permissionName: "View My Requests Tab",
        moduleCode: "contract",
        moduleName: "Contract Approval",
        moduleStatus: true,
        description: "Allows access to enable My Requests Tab",
        status: true,
        updatedBy: "vrameshbapu@nrl.com.au",
        createdAt: new Date("2025-04-10T08:11:33.996Z"),
        updatedAt: new Date("2025-04-10T08:11:33.996Z"),
      },
      {
        _id: new ObjectId("676d3e3cccffb83c5ccf5da2"),
        moduleId: new ObjectId("65e3579de0ca70fe8f2e148e"),
        permissionCode: "view-approve-request-tab",
        permissionName: "View Approve Requests Tab",
        moduleCode: "contract",
        moduleName: "Contract Approval",
        moduleStatus: true,
        description: "Allows access to enable Approve Requests Tab",
        status: true,
        updatedBy: "vrameshbapu@nrl.com.au",
        createdAt: new Date("2025-04-10T08:11:33.996Z"),
        updatedAt: new Date("2025-04-10T08:11:33.996Z"),
      },
      {
        _id: new ObjectId("67e268a608b3f2bc83885e6c"),
        moduleId: new ObjectId("65e3579de0ca70fe8f2e148e"),
        permissionCode: "view-e-sign-requests-tab",
        permissionName: "View E Sign Requests Tab",
        moduleCode: "contract",
        moduleName: "Contract Approval",
        moduleStatus: true,
        description: "Allows access to enable E Sign Requests Tab",
        status: true,
        updatedBy: "vrameshbapu@nrl.com.au",
        createdAt: new Date("2025-04-10T08:11:33.996Z"),
        updatedAt: new Date("2025-04-10T08:11:33.996Z"),
      },
      {
        _id: new ObjectId("67e2888bdbce9cd169ecadc8"),
        moduleId: new ObjectId("65e3579de0ca70fe8f2e148e"),
        permissionCode: "view-my-approved-requests-tab",
        permissionName: "View My Approved Requests Tab",
        moduleCode: "contract",
        moduleName: "Contract Approval",
        moduleStatus: true,
        description: "Allows access to enable My Approved Requests Tab",
        status: true,
        updatedBy: "vrameshbapu@nrl.com.au",
        createdAt: new Date("2025-04-10T08:11:33.996Z"),
        updatedAt: new Date("2025-04-10T08:11:33.996Z"),
      },
    ],
    createdBy: "mmurugesan@nrl.com.au",
    updatedBy: "mmurugesan@nrl.com.au",
    createdAt: new Date("2024-02-28T11:06:18.974Z"),
    updatedAt: new Date("2025-04-10T08:11:33.996Z"),
  },
  {
    _id: new ObjectId("65def510de3deddff04f79ac"),
    name: "Finance Admin",
    code: "finance-admin",
    description: "Finance Admin",
    status: true,
    moduleId: [new ObjectId("65e3579de0ca70fe8f2e148e")],
    permissions: [
      {
        _id: new ObjectId("676d3997ccffb83c5ccf5d9b"),
        moduleId: new ObjectId("65e3579de0ca70fe8f2e148e"),
        permissionCode: "view-forms-menu",
        permissionName: "View Forms Menu",
        moduleCode: "contract",
        moduleName: "Contract Approval",
        moduleStatus: true,
        description: "Allows access to Forms Menu page",
        status: true,
        updatedBy: "vrameshbapu@nrl.com.au",
        createdAt: new Date("2025-04-10T08:11:33.994Z"),
        updatedAt: new Date("2025-04-10T08:11:33.994Z"),
      },
      {
        _id: new ObjectId("676d563eccffb83c5ccf5da5"),
        moduleId: new ObjectId("65e3579de0ca70fe8f2e148e"),
        permissionCode: "view-my-requests-tab",
        permissionName: "View My Requests Tab",
        moduleCode: "contract",
        moduleName: "Contract Approval",
        moduleStatus: true,
        description: "Allows access to enable My Requests Tab",
        status: true,
        updatedBy: "vrameshbapu@nrl.com.au",
        createdAt: new Date("2025-04-10T08:11:33.994Z"),
        updatedAt: new Date("2025-04-10T08:11:33.994Z"),
      },
      {
        _id: new ObjectId("676d55a1ccffb83c5ccf5da4"),
        moduleId: new ObjectId("65e3579de0ca70fe8f2e148e"),
        permissionCode: "view-team-requests-tab",
        permissionName: "View Team Requests Tab",
        moduleCode: "contract",
        moduleName: "Contract Approval",
        moduleStatus: true,
        description: "Allows access to enable Team Requests Tab",
        status: true,
        updatedBy: "vrameshbapu@nrl.com.au",
        createdAt: new Date("2025-04-10T08:11:33.994Z"),
        updatedAt: new Date("2025-04-10T08:11:33.994Z"),
      },
      {
        _id: new ObjectId("676d3e3cccffb83c5ccf5da2"),
        moduleId: new ObjectId("65e3579de0ca70fe8f2e148e"),
        permissionCode: "view-approve-request-tab",
        permissionName: "View Approve Requests Tab",
        moduleCode: "contract",
        moduleName: "Contract Approval",
        moduleStatus: true,
        description: "Allows access to enable Approve Requests Tab",
        status: true,
        updatedBy: "vrameshbapu@nrl.com.au",
        createdAt: new Date("2025-04-10T08:11:33.994Z"),
        updatedAt: new Date("2025-04-10T08:11:33.994Z"),
      },
      {
        _id: new ObjectId("676d393accffb83c5ccf5d9a"),
        moduleId: new ObjectId("65e3579de0ca70fe8f2e148e"),
        permissionCode: "view-dashboard-menu",
        permissionName: "View Dashboard Menu",
        moduleCode: "contract",
        moduleName: "Contract Approval",
        moduleStatus: true,
        description: "Allows access to Dashboard page",
        status: true,
        updatedBy: "vrameshbapu@nrl.com.au",
        createdAt: new Date("2025-04-10T08:11:33.994Z"),
        updatedAt: new Date("2025-04-10T08:11:33.994Z"),
      },
      {
        _id: new ObjectId("67e268a608b3f2bc83885e6c"),
        moduleId: new ObjectId("65e3579de0ca70fe8f2e148e"),
        permissionCode: "view-e-sign-requests-tab",
        permissionName: "View E Sign Requests Tab",
        moduleCode: "contract",
        moduleName: "Contract Approval",
        moduleStatus: true,
        description: "Allows access to enable E Sign Requests Tab",
        status: true,
        updatedBy: "vrameshbapu@nrl.com.au",
        createdAt: new Date("2025-04-10T08:11:33.994Z"),
        updatedAt: new Date("2025-04-10T08:11:33.994Z"),
      },
      {
        _id: new ObjectId("67e2888bdbce9cd169ecadc8"),
        moduleId: new ObjectId("65e3579de0ca70fe8f2e148e"),
        permissionCode: "view-my-approved-requests-tab",
        permissionName: "View My Approved Requests Tab",
        moduleCode: "contract",
        moduleName: "Contract Approval",
        moduleStatus: true,
        description: "Allows access to enable My Approved Requests Tab",
        status: true,
        updatedBy: "vrameshbapu@nrl.com.au",
        createdAt: new Date("2025-04-10T08:11:33.994Z"),
        updatedAt: new Date("2025-04-10T08:11:33.994Z"),
      },
    ],
    createdBy: "mmurugesan@nrl.com.au",
    updatedBy: "mmurugesan@nrl.com.au",
    createdAt: new Date("2024-02-28T11:06:18.974Z"),
    updatedAt: new Date("2025-04-10T08:11:33.994Z"),
  },
  {
    _id: new ObjectId("65def586de3deddff04f79af"),
    name: "Requester",
    code: "guest-user",
    description: "Guest user",
    status: true,
    moduleId: [new ObjectId("65e3579de0ca70fe8f2e148e")],
    permissions: [
      {
        _id: new ObjectId("676d3997ccffb83c5ccf5d9b"),
        moduleId: new ObjectId("65e3579de0ca70fe8f2e148e"),
        permissionCode: "view-forms-menu",
        permissionName: "View Forms Menu",
        moduleCode: "contract",
        moduleName: "Contract Approval",
        moduleStatus: true,
        status: true,
        createdBy: "bbharathivel@nrl.com.au",
        updatedBy: "vrameshbapu@nrl.com.au",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        _id: new ObjectId("676d563eccffb83c5ccf5da5"),
        moduleId: new ObjectId("65e3579de0ca70fe8f2e148e"),
        permissionCode: "view-my-requests-tab",
        permissionName: "View My Requests Tab",
        moduleCode: "contract",
        moduleName: "Contract Approval",
        moduleStatus: true,
        description: "Allows access to enable My Requests Tab",
        status: true,
        createdBy: "bbharathivel@nrl.com.au",
        updatedBy: "vrameshbapu@nrl.com.au",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    createdBy: "bbharathivel@nrl.com.au",
    updatedBy: "vrameshbapu@nrl.com.au",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: new ObjectId("65def561de3deddff04f79ae"),
    name: "CEO",
    code: "ceo",
    description: "Chief Executive Officer",
    status: true,
    moduleId: [new ObjectId("65e3579de0ca70fe8f2e148e")],
    permissions: [
      {
        _id: new ObjectId("676d3997ccffb83c5ccf5d9b"),
        moduleId: new ObjectId("65e3579de0ca70fe8f2e148e"),
        permissionCode: "view-forms-menu",
        permissionName: "View Forms Menu",
        moduleCode: "contract",
        moduleName: "Contract Approval",
        moduleStatus: true,
        description: "Allows access to Forms Menu page",
        status: true,
        updatedBy: "vrameshbapu@nrl.com.au",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        _id: new ObjectId("676d563eccffb83c5ccf5da5"),
        moduleId: new ObjectId("65e3579de0ca70fe8f2e148e"),
        permissionCode: "view-my-requests-tab",
        permissionName: "View My Requests Tab",
        moduleCode: "contract",
        moduleName: "Contract Approval",
        moduleStatus: true,
        description: "Allows access to enable My Requests Tab",
        status: true,
        updatedBy: "vrameshbapu@nrl.com.au",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        _id: new ObjectId("676d3e3cccffb83c5ccf5da2"),
        moduleId: new ObjectId("65e3579de0ca70fe8f2e148e"),
        permissionCode: "view-approve-request-tab",
        permissionName: "View Approve Requests Tab",
        moduleCode: "contract",
        moduleName: "Contract Approval",
        moduleStatus: true,
        description: "Allows access to enable Approve Requests Tab",
        status: true,
        updatedBy: "vrameshbapu@nrl.com.au",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        _id: new ObjectId("676d393accffb83c5ccf5d9a"),
        moduleId: new ObjectId("65e3579de0ca70fe8f2e148e"),
        permissionCode: "view-dashboard-menu",
        permissionName: "View Dashboard Menu",
        moduleCode: "contract",
        moduleName: "Contract Approval",
        moduleStatus: true,
        description: "Allows access to Dashboard page",
        status: true,
        updatedBy: "vrameshbapu@nrl.com.au",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        _id: new ObjectId("67e268a608b3f2bc83885e6c"),
        moduleId: new ObjectId("65e3579de0ca70fe8f2e148e"),
        permissionCode: "view-e-sign-requests-tab",
        permissionName: "View E Sign Requests Tab",
        moduleCode: "contract",
        moduleName: "Contract Approval",
        moduleStatus: true,
        description: "Allows access to enable E Sign Requests Tab",
        status: true,
        updatedBy: "vrameshbapu@nrl.com.au",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        _id: new ObjectId("67e2888bdbce9cd169ecadc8"),
        moduleId: new ObjectId("65e3579de0ca70fe8f2e148e"),
        permissionCode: "view-my-approved-requests-tab",
        permissionName: "View My Approved Requests Tab",
        moduleCode: "contract",
        moduleName: "Contract Approval",
        moduleStatus: true,
        description: "Allows access to enable My Approved Requests Tab",
        status: true,
        updatedBy: "vrameshbapu@nrl.com.au",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    createdBy: "mmurugesan@nrl.com.au",
    updatedBy: "mmurugesan@nrl.com.au",
    createdAt: new Date("2024-02-28T11:06:18.974Z"),
    updatedAt: new Date(),
  },
  {
    _id: new ObjectId("65def330de3deddff04f79a1"),
    name: "Vendor Module Admin",
    code: "vendor-module-admin",
    description: "Vendor Module Admin",
    status: true,
    moduleId: [
      new ObjectId("65e3579de0ca70fe8f2e148e"),
      new ObjectId("65def137de3deddff04f799b"),
    ],
    permissions: [
      {
        _id: new ObjectId("676d55a1ccffb83c5ccf5da4"),
        moduleId: new ObjectId("65e3579de0ca70fe8f2e148e"),
        permissionCode: "view-team-requests-tab",
        permissionName: "View Team Requests Tab",
        moduleCode: "contract",
        moduleName: "Contract Approval",
        moduleStatus: true,
        description: "Allows access to enable Team Requests Tab",
        status: true,
        updatedBy: "vrameshbapu@nrl.com.au",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        _id: new ObjectId("676d3997ccffb83c5ccf5d9b"),
        moduleId: new ObjectId("65e3579de0ca70fe8f2e148e"),
        permissionCode: "view-forms-menu",
        permissionName: "View Forms Menu",
        moduleCode: "contract",
        moduleName: "Contract Approval",
        moduleStatus: true,
        description: "Allows access to Forms Menu page",
        status: true,
        updatedBy: "vrameshbapu@nrl.com.au",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        _id: new ObjectId("676d393accffb83c5ccf5d9a"),
        moduleId: new ObjectId("65e3579de0ca70fe8f2e148e"),
        permissionCode: "view-dashboard-menu",
        permissionName: "View Dashboard Menu",
        moduleCode: "contract",
        moduleName: "Contract Approval",
        moduleStatus: true,
        description: "Allows access to Dashboard page",
        status: true,
        updatedBy: "vrameshbapu@nrl.com.au",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        _id: new ObjectId("676d39f8ccffb83c5ccf5d9c"),
        moduleId: new ObjectId("65e3579de0ca70fe8f2e148e"),
        permissionCode: "view-configuration",
        permissionName: "View Configuration",
        moduleCode: "contract",
        moduleName: "Contract Approval",
        moduleStatus: true,
        description: "Allows access to Configuration page",
        status: true,
        updatedBy: "vrameshbapu@nrl.com.au",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        _id: new ObjectId("676d563eccffb83c5ccf5da5"),
        moduleId: new ObjectId("65e3579de0ca70fe8f2e148e"),
        permissionCode: "view-my-requests-tab",
        permissionName: "View My Requests Tab",
        moduleCode: "contract",
        moduleName: "Contract Approval",
        moduleStatus: true,
        description: "Allows access to enable My Requests Tab",
        status: true,
        updatedBy: "vrameshbapu@nrl.com.au",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        _id: new ObjectId("676d3e3cccffb83c5ccf5da2"),
        moduleId: new ObjectId("65e3579de0ca70fe8f2e148e"),
        permissionCode: "view-approve-request-tab",
        permissionName: "View Approve Requests Tab",
        moduleCode: "contract",
        moduleName: "Contract Approval",
        moduleStatus: true,
        description: "Allows access to enable Approve Requests Tab",
        status: true,
        updatedBy: "vrameshbapu@nrl.com.au",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        _id: new ObjectId("67e268a608b3f2bc83885e6c"),
        moduleId: new ObjectId("65e3579de0ca70fe8f2e148e"),
        permissionCode: "view-e-sign-requests-tab",
        permissionName: "View E Sign Requests Tab",
        moduleCode: "contract",
        moduleName: "Contract Approval",
        moduleStatus: true,
        description: "Allows access to enable E Sign Requests Tab",
        status: true,
        updatedBy: "vrameshbapu@nrl.com.au",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        _id: new ObjectId("67e2888bdbce9cd169ecadc8"),
        moduleId: new ObjectId("65e3579de0ca70fe8f2e148e"),
        permissionCode: "view-my-approved-requests-tab",
        permissionName: "View My Approved Requests Tab",
        moduleCode: "contract",
        moduleName: "Contract Approval",
        moduleStatus: true,
        description: "Allows access to enable My Approved Requests Tab",
        status: true,
        updatedBy: "vrameshbapu@nrl.com.au",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        _id: new ObjectId("676d57b6ccffb83c5ccf5da7"),
        moduleId: new ObjectId("65def137de3deddff04f799b"),
        permissionCode: "view-settings",
        permissionName: "View Settings",
        moduleCode: "settings",
        moduleName: "Settings",
        moduleStatus: true,
        description: "Allows access to settings page",
        status: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        _id: new ObjectId("676d5c65ccffb83c5ccf5daa"),
        moduleId: new ObjectId("65def137de3deddff04f799b"),
        permissionCode: "view-role-settings",
        permissionName: "View Role Settings",
        moduleCode: "settings",
        moduleName: "Settings",
        moduleStatus: true,
        description: "Allows access to role settings page",
        status: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        _id: new ObjectId("676d5cdfccffb83c5ccf5dab"),
        moduleId: new ObjectId("65def137de3deddff04f799b"),
        permissionCode: "view-permission-settings",
        permissionName: "View Permission Settings",
        moduleCode: "settings",
        moduleName: "Settings",
        moduleStatus: true,
        description: "Allows access to permission settings page",
        status: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        _id: new ObjectId("676d5d45ccffb83c5ccf5dac"),
        moduleId: new ObjectId("65def137de3deddff04f799b"),
        permissionCode: "view-module-settings",
        permissionName: "View Module Settings",
        moduleCode: "settings",
        moduleName: "Settings",
        moduleStatus: true,
        description: "Allows access to module settings page",
        status: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        _id: new ObjectId("676d58e9ccffb83c5ccf5da8"),
        moduleId: new ObjectId("65def137de3deddff04f799b"),
        permissionCode: "view-user-settings",
        permissionName: "View User Settings",
        moduleCode: "settings",
        moduleName: "Settings",
        moduleStatus: true,
        description: "Allows access to user settings page",
        status: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        _id: new ObjectId("676d5b7cccffb83c5ccf5da9"),
        moduleId: new ObjectId("65def137de3deddff04f799b"),
        permissionCode: "view-department-settings",
        permissionName: "View Department Settings",
        moduleCode: "settings",
        moduleName: "Settings",
        moduleStatus: true,
        description: "Allows access to department settings page",
        status: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    createdBy: "mmurugesan@nrl.com.au",
    updatedBy: "mmurugesan@nrl.com.au",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: new ObjectId("65def505de3deddff04f79ab"),
    name: "Legal Admin",
    code: "legal-admin",
    description: "Legal Admin",
    status: true,
    moduleId: [new ObjectId("65e3579de0ca70fe8f2e148e")],
    permissions: [
      {
        _id: new ObjectId("676d3997ccffb83c5ccf5d9b"),
        moduleId: new ObjectId("65e3579de0ca70fe8f2e148e"),
        permissionCode: "view-forms-menu",
        permissionName: "View Forms Menu",
        moduleCode: "contract",
        moduleName: "Contract Approval",
        moduleStatus: true,
        description: "Allows access to Forms Menu page",
        status: true,
        updatedBy: "vrameshbapu@nrl.com.au",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        _id: new ObjectId("676d563eccffb83c5ccf5da5"),
        moduleId: new ObjectId("65e3579de0ca70fe8f2e148e"),
        permissionCode: "view-my-requests-tab",
        permissionName: "View My Requests Tab",
        moduleCode: "contract",
        moduleName: "Contract Approval",
        moduleStatus: true,
        description: "Allows access to enable My Requests Tab",
        status: true,
        updatedBy: "vrameshbapu@nrl.com.au",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        _id: new ObjectId("676d3e3cccffb83c5ccf5da2"),
        moduleId: new ObjectId("65e3579de0ca70fe8f2e148e"),
        permissionCode: "view-approve-request-tab",
        permissionName: "View Approve Requests Tab",
        moduleCode: "contract",
        moduleName: "Contract Approval",
        moduleStatus: true,
        description: "Allows access to enable Approve Requests Tab",
        status: true,
        updatedBy: "vrameshbapu@nrl.com.au",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        _id: new ObjectId("67e268a608b3f2bc83885e6c"),
        moduleId: new ObjectId("65e3579de0ca70fe8f2e148e"),
        permissionCode: "view-e-sign-requests-tab",
        permissionName: "View E Sign Requests Tab",
        moduleCode: "contract",
        moduleName: "Contract Approval",
        moduleStatus: true,
        description: "Allows access to enable E Sign Requests Tab",
        status: true,
        updatedBy: "vrameshbapu@nrl.com.au",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        _id: new ObjectId("67e2888bdbce9cd169ecadc8"),
        moduleId: new ObjectId("65e3579de0ca70fe8f2e148e"),
        permissionCode: "view-my-approved-requests-tab",
        permissionName: "View My Approved Requests Tab",
        moduleCode: "contract",
        moduleName: "Contract Approval",
        moduleStatus: true,
        description: "Allows access to enable My Approved Requests Tab",
        status: true,
        updatedBy: "vrameshbapu@nrl.com.au",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    createdBy: "mmurugesan@nrl.com.au",
    updatedBy: "mmurugesan@nrl.com.au",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: new ObjectId("65def325de3deddff04f79a0"),
    name: "Super Admin",
    code: "super-admin",
    description: "Super Admin",
    status: true,
    moduleId: [
      new ObjectId("65e3579de0ca70fe8f2e148e"),
      new ObjectId("65def137de3deddff04f799b"),
    ],
    permissions: [
      {
        _id: new ObjectId("676d55a1ccffb83c5ccf5da4"),
        moduleId: new ObjectId("65e3579de0ca70fe8f2e148e"),
        permissionCode: "view-team-requests-tab",
        permissionName: "View Team Requests Tab",
        moduleCode: "contract",
        moduleName: "Contract Approval",
        moduleStatus: true,
        description: "Allows access to enable Team Requests Tab",
        status: true,
        updatedBy: "vrameshbapu@nrl.com.au",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        _id: new ObjectId("676d3997ccffb83c5ccf5d9b"),
        moduleId: new ObjectId("65e3579de0ca70fe8f2e148e"),
        permissionCode: "view-forms-menu",
        permissionName: "View Forms Menu",
        moduleCode: "contract",
        moduleName: "Contract Approval",
        moduleStatus: true,
        description: "Allows access to Forms Menu page",
        status: true,
        updatedBy: "vrameshbapu@nrl.com.au",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        _id: new ObjectId("676d393accffb83c5ccf5d9a"),
        moduleId: new ObjectId("65e3579de0ca70fe8f2e148e"),
        permissionCode: "view-dashboard-menu",
        permissionName: "View Dashboard Menu",
        moduleCode: "contract",
        moduleName: "Contract Approval",
        moduleStatus: true,
        description: "Allows access to Dashboard page",
        status: true,
        updatedBy: "vrameshbapu@nrl.com.au",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        _id: new ObjectId("676d39f8ccffb83c5ccf5d9c"),
        moduleId: new ObjectId("65e3579de0ca70fe8f2e148e"),
        permissionCode: "view-configuration",
        permissionName: "View Configuration",
        moduleCode: "contract",
        moduleName: "Contract Approval",
        moduleStatus: true,
        description: "Allows access to Configuration page",
        status: true,
        updatedBy: "vrameshbapu@nrl.com.au",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        _id: new ObjectId("676d563eccffb83c5ccf5da5"),
        moduleId: new ObjectId("65e3579de0ca70fe8f2e148e"),
        permissionCode: "view-my-requests-tab",
        permissionName: "View My Requests Tab",
        moduleCode: "contract",
        moduleName: "Contract Approval",
        moduleStatus: true,
        description: "Allows access to enable My Requests Tab",
        status: true,
        updatedBy: "vrameshbapu@nrl.com.au",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        _id: new ObjectId("676d3e3cccffb83c5ccf5da2"),
        moduleId: new ObjectId("65e3579de0ca70fe8f2e148e"),
        permissionCode: "view-approve-request-tab",
        permissionName: "View Approve Requests Tab",
        moduleCode: "contract",
        moduleName: "Contract Approval",
        moduleStatus: true,
        description: "Allows access to enable Approve Requests Tab",
        status: true,
        updatedBy: "vrameshbapu@nrl.com.au",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        _id: new ObjectId("67e268a608b3f2bc83885e6c"),
        moduleId: new ObjectId("65e3579de0ca70fe8f2e148e"),
        permissionCode: "view-e-sign-requests-tab",
        permissionName: "View E Sign Requests Tab",
        moduleCode: "contract",
        moduleName: "Contract Approval",
        moduleStatus: true,
        description: "Allows access to enable E Sign Requests Tab",
        status: true,
        updatedBy: "vrameshbapu@nrl.com.au",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        _id: new ObjectId("67e2888bdbce9cd169ecadc8"),
        moduleId: new ObjectId("65e3579de0ca70fe8f2e148e"),
        permissionCode: "view-my-approved-requests-tab",
        permissionName: "View My Approved Requests Tab",
        moduleCode: "contract",
        moduleName: "Contract Approval",
        moduleStatus: true,
        description: "Allows access to enable My Approved Requests Tab",
        status: true,
        updatedBy: "vrameshbapu@nrl.com.au",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        _id: new ObjectId("676d57b6ccffb83c5ccf5da7"),
        moduleId: new ObjectId("65def137de3deddff04f799b"),
        permissionCode: "view-settings",
        permissionName: "View Settings",
        moduleCode: "settings",
        moduleName: "Settings",
        moduleStatus: true,
        description: "Allows access to settings page",
        status: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        _id: new ObjectId("676d5c65ccffb83c5ccf5daa"),
        moduleId: new ObjectId("65def137de3deddff04f799b"),
        permissionCode: "view-role-settings",
        permissionName: "View Role Settings",
        moduleCode: "settings",
        moduleName: "Settings",
        moduleStatus: true,
        description: "Allows access to role settings page",
        status: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        _id: new ObjectId("676d5cdfccffb83c5ccf5dab"),
        moduleId: new ObjectId("65def137de3deddff04f799b"),
        permissionCode: "view-permission-settings",
        permissionName: "View Permission Settings",
        moduleCode: "settings",
        moduleName: "Settings",
        moduleStatus: true,
        description: "Allows access to permission settings page",
        status: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        _id: new ObjectId("676d5d45ccffb83c5ccf5dac"),
        moduleId: new ObjectId("65def137de3deddff04f799b"),
        permissionCode: "view-module-settings",
        permissionName: "View Module Settings",
        moduleCode: "settings",
        moduleName: "Settings",
        moduleStatus: true,
        description: "Allows access to module settings page",
        status: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        _id: new ObjectId("676d58e9ccffb83c5ccf5da8"),
        moduleId: new ObjectId("65def137de3deddff04f799b"),
        permissionCode: "view-user-settings",
        permissionName: "View User Settings",
        moduleCode: "settings",
        moduleName: "Settings",
        moduleStatus: true,
        description: "Allows access to user settings page",
        status: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        _id: new ObjectId("676d5b7cccffb83c5ccf5da9"),
        moduleId: new ObjectId("65def137de3deddff04f799b"),
        permissionCode: "view-department-settings",
        permissionName: "View Department Settings",
        moduleCode: "settings",
        moduleName: "Settings",
        moduleStatus: true,
        description: "Allows access to department settings page",
        status: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    createdBy: "mmurugesan@nrl.com.au",
    updatedBy: "mmurugesan@nrl.com.au",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export async function up(db: Db) {
  console.log("Starting roles migration");
  try {
    // Count documents before archiving
    const countBefore = await db.collection("roles").countDocuments();
    console.log(`Documents in roles before archiving: ${countBefore}`);

    // Archive existing roles
    const existingRoles = await db.collection("roles").find({}).toArray();
    if (existingRoles.length > 0) {
      const archivedRoles = existingRoles.map((role) => ({
        ...role,
        archivedAt: new Date(),
        source: "roles_migration",
      }));
      const archiveResult = await db
        .collection("archived_roles")
        .insertMany(archivedRoles);
      console.log(
        `Archived ${archiveResult.insertedCount} documents to archived_roles`,
      );
    } else {
      console.log("No roles to archive");
    }

    // Delete existing roles
    const deleteResult = await db.collection("roles").deleteMany({});
    console.log(`Deleted ${deleteResult.deletedCount} documents from roles`);

    // Insert new roles
    const insertResult = await db.collection("roles").insertMany(rolesData);
    console.log(`Inserted ${insertResult.insertedCount} documents into roles`);

    console.log("Roles migration completed successfully");
  } catch (error) {
    console.error("Error in roles migration:", error);
    throw error;
  }
}

export async function down(db: Db) {
  console.log("Starting roles migration rollback");
  try {
    // Delete roles added in up migration
    const deleteResult = await db.collection("roles").deleteMany({
      _id: { $in: rolesData.map((r) => r._id) },
    });
    console.log(`Deleted ${deleteResult.deletedCount} documents from roles`);

    // Restore archived roles
    const archivedRoles = await db
      .collection("archived_roles")
      .find({
        source: "roles_migration",
      })
      .toArray();
    if (archivedRoles.length > 0) {
      // Remove archive-specific fields
      const rolesToRestore = archivedRoles.map(
        ({ archivedAt, source, ...role }) => role,
      );
      const restoreResult = await db
        .collection("roles")
        .insertMany(rolesToRestore);
      console.log(`Restored ${restoreResult.insertedCount} documents to roles`);

      // Clean up archived_roles
      await db.collection("archived_roles").deleteMany({
        source: "roles_migration",
      });
      console.log("Cleaned up archived_roles collection");
    } else {
      console.log("No archived roles to restore");
    }

    console.log("Roles migration rolled back successfully");
  } catch (error) {
    console.error("Error in roles rollback:", error);
    throw error;
  }
}
