/**
 * Generated by @openapi-codegen
 *
 * @version 1.0.0
 */
export type SchemaObjectId = {};

export type ObjectId = {};

export type IsObject = {};

export type WorkflowOrderDTO = {
  /**
   * The level of the workflow order
   *
   * @example 1
   */
  level: number;
  /**
   * The ID of the role associated with this workflow order
   *
   * @example 65def586de3deddff04f79af
   */
  roleId?: SchemaObjectId;
  /**
   * Flag indicating whether there is a limit in this workflow
   *
   * @example true
   */
  limitFlag?: boolean;
  /**
   * The minimum value for this workflow order
   *
   * @example 10
   */
  min?: number;
  /**
   * The maximum value for this workflow order
   *
   * @example 100
   */
  max?: number;
  /**
   * Name of the workflow order
   *
   * @example General Manager
   */
  name?: string;
  /**
   * Status of the workflow order
   *
   * @example active
   */
  status: string;
  /**
   * Flag indicating whether a specific department approver is required
   *
   * @example true
   */
  isSpecificDeptApprover?: boolean;
  /**
   * Flag indicating whether the workflow should include requester checks
   *
   * @example true
   */
  includeOnRequesterCheck?: boolean;
};

export type CreateFormDto = {
  /**
   * ID of the form being updated
   *
   * @example 65f47c35de3deddff04f79c1
   */
  formId?: SchemaObjectId;
  /**
   * Module ID
   *
   * @example 65e3579de0ca70fe8f2e148e
   */
  moduleId: ObjectId;
  /**
   * Code for the transaction
   *
   * @example SST-2025011709394366241
   */
  code: string;
  /**
   * Department ID
   *
   * @example 672acf6706b004004c729d08
   */
  department: ObjectId;
  /**
   * Name of the department
   *
   * @example Technology
   */
  departmentName: string;
  /**
   * Information about the form
   */
  formInfo: IsObject;
  /**
   * List of attachments
   *
   * @example formdocuments/SST_Leave_policy_20250117T041228100Z_36346.pdf
   */
  attachments: string[];
  /**
   * List of MSA attachments
   *
   * @example msadocuments/SST_Leave_policy_20250117T041210343Z_40421.pdf
   */
  msaAttachments: string[];
  /**
   * Email of the user who created the form
   *
   * @example bbharathivel@nrl.com.au
   */
  createdBy: string;
  /**
   * Email of the user who created the form
   *
   * @example bbharathivel@nrl.com.au
   */
  updatedBy: string;
  /**
   * History of the form
   */
  formHistory: IsObject[];
  /**
   * Redirect path for email notifications
   *
   * @example /finance/vendor-contract/requests/detail/formDetailId?page=approveRequest&moduleId=65e3579de0ca70fe8f2e148e
   */
  mailRedirectPath: string;
  /**
   * ID of the workflow associated with the form
   *
   * @example 65def477de3deddff04f79a8
   */
  workflow?: ObjectId;
  /**
   * Name of the workflow
   *
   * @example Technology Admin Workflow
   */
  workflowName?: string;
  /**
   * Version ID of the workflow
   *
   * @example 65def477de3deddff04f79b2
   */
  workflowVersion?: ObjectId;
  /**
   * Workflow order details
   *
   * @example {"level":1,"roleId":"65def586de3deddff04f79af","limitFlag":true,"min":1,"max":100,"name":"Manager","status":"active","isSpecificDeptApprover":true,"includeOnRequesterCheck":false}
   */
  workflowOrder?: WorkflowOrderDTO[];
  /**
   * Indicates if there is a active form
   *
   * @example false
   */
  active: boolean;
  /**
   * Status of the form
   *
   * @example pedning
   */
  status?: string;
  /**
   * Envelope ID for document signing
   *
   * @example env_123456789
   */
  envelopeId?: string;
  /**
   * Code of the module
   *
   * @example MOD-IT-2025
   */
  moduleCode?: string;
  /**
   * Additional information for the form
   *
   * @example {"priority":"high","category":"IT"}
   */
  formAdditionalInfo?: Record<string, any>;
  /**
   * Envelope summary details
   *
   * @example {"status":"signed","documentName":"contract.pdf"}
   */
  envelopeSummary?: Record<string, any>;
  /**
   * Status of the DocuSign envelope
   *
   * @example completed
   */
  docusignStatus?: string;
  /**
   * User id of the specific user
   *
   * @example 678e14daca332048be97fa69
   */
  specificApproverUserId?: string;
};

export type CreateUpdateFormResponseDto = {
  /**
   * Message indicating the result of the operation
   *
   * @example Form has been created/resubmitted successfully!
   */
  message: string;
};

export type CreateDraftFormDto = {
  /**
   * ID of the form being updated
   *
   * @example 65f47c35de3deddff04f79c1
   */
  formId?: SchemaObjectId;
  /**
   * Module ID
   *
   * @example 65e3579de0ca70fe8f2e148e
   */
  moduleId: ObjectId;
  /**
   * Code for the transaction
   *
   * @example SST-2025011709394366241
   */
  code: string;
  /**
   * Department ID
   *
   * @example 672acf6706b004004c729d08
   */
  department: ObjectId;
  /**
   * Name of the department
   *
   * @example Technology
   */
  departmentName: string;
  /**
   * Information about the form
   */
  formInfo: IsObject;
  /**
   * List of attachments
   *
   * @example formdocuments/SST_Leave_policy_20250117T041228100Z_36346.pdf
   */
  attachments: string[];
  /**
   * List of MSA attachments
   *
   * @example msadocuments/SST_Leave_policy_20250117T041210343Z_40421.pdf
   */
  msaAttachments: string[];
  /**
   * Email of the user who created the form
   *
   * @example bbharathivel@nrl.com.au
   */
  createdBy: string;
  /**
   * Email of the user who created the form
   *
   * @example bbharathivel@nrl.com.au
   */
  updatedBy: string;
  /**
   * History of the form
   */
  formHistory: IsObject[];
  /**
   * Redirect path for email notifications
   *
   * @example /finance/vendor-contract/requests/detail/formDetailId?page=approveRequest&moduleId=65e3579de0ca70fe8f2e148e
   */
  mailRedirectPath: string;
  /**
   * ID of the workflow associated with the form
   *
   * @example 65def477de3deddff04f79a8
   */
  workflow?: ObjectId;
  /**
   * Name of the workflow
   *
   * @example Technology Admin Workflow
   */
  workflowName?: string;
  /**
   * Version ID of the workflow
   *
   * @example 65def477de3deddff04f79b2
   */
  workflowVersion?: ObjectId;
  /**
   * Workflow order details
   *
   * @example {"level":1,"roleId":"65def586de3deddff04f79af","limitFlag":true,"min":1,"max":100,"name":"Manager","status":"active","isSpecificDeptApprover":true,"includeOnRequesterCheck":false}
   */
  workflowOrder?: WorkflowOrderDTO[];
  /**
   * Indicates if there is a active form
   *
   * @example false
   */
  active: boolean;
  /**
   * Status of the form
   *
   * @example draft
   */
  status?: string;
  /**
   * Code of the module
   *
   * @example MOD-IT-2025
   */
  moduleCode?: string;
  /**
   * User id of the specific user
   *
   * @example 678e14daca332048be97fa69
   */
  specificApproverUserId?: string;
};

export type CreateDraftFormResponseDto = {
  /**
   * Message indicating the result of the operation
   *
   * @example Draft Form has been created successfully!
   */
  message: string;
};

export type ContractFormListDto = {
  /**
   * Unique identifier of the form
   *
   * @example 673f2a34ac9471b25fdb5792
   */
  _id: ObjectId;
  /**
   * Module ID associated with the form
   *
   * @example 65e3579de0ca70fe8f2e148e
   */
  moduleId: ObjectId;
  /**
   * Unique form code
   *
   * @example SST-2024112106053799897
   */
  code: string;
  /**
   * Form information object
   *
   * @example {"counter_party":"SST-TechHub","monetary_value":"20000.50","start_date":"Sun Nov 28 202421 10:38:27 GMT+0530 ","end_date":"Sun Nov 28 202421 10:38:27 GMT+0530 "}
   */
  formInfo: IsObject;
  /**
   * Department identifier
   *
   * @example 672acf6706b004004c729d08
   */
  department: ObjectId;
  /**
   * Name of the department associated with the form
   *
   * @example Technology
   */
  departmentName: string;
  /**
   * Workflow identifier
   *
   * @example 65def3f1de3deddff04f79a7
   */
  workflow: ObjectId;
  /**
   * Name of the workflow for the form
   *
   * @example CEO
   */
  workflowName: string;
  /**
   * Current status of the form
   *
   * @example fulfilled
   */
  status: string;
  /**
   * Email of the user who created the form
   *
   * @example bbharathivel@nrl.com.au
   */
  createdBy: string;
  /**
   * Date when the form was created
   *
   * @example 2024-11-21T12:40:20.340+00:00
   */
  createdAt: string;
};

export type ContractPaginationDto = {
  /**
   * Total number of rows available
   *
   * @example 0
   */
  totalRowCount: number;
};

export type ContractMetaDto = {
  /**
   * Pagination information
   */
  pagination: ContractPaginationDto;
};

export type ContractFormListResponseDto = {
  /**
   * Data array containing the forms
   */
  data: ContractFormListDto[];
  /**
   * Meta data related to the response
   */
  meta: ContractMetaDto;
};

export type IsString = {};

export type FromHistory = {
  /**
   * Email of the approver
   *
   * @example bbharathivel@nrl.com.au
   */
  approvedBy: string;
  /**
   * Current status of the workflow
   *
   * @example initiated
   */
  status: string;
  /**
   * Workflow identifier
   *
   * @example 65def3f1de3deddff04f79a7
   */
  workflow: ObjectId;
  /**
   * Name of the workflow
   *
   * @example Executive General Manager
   */
  workflowName: string;
  /**
   * Department identifier
   *
   * @example 672acf6706b004004c729d08
   */
  department: string;
  /**
   * Name of the department
   *
   * @example Technology
   */
  departmentName: string;
  /**
   * Creation timestamp in milliseconds
   *
   * @example 1732192820391
   */
  createdAt: string;
};

export type WorkFlowOrder = {
  /**
   * Level of the role in the workflow hierarchy
   *
   * @example 1
   */
  level: number;
  /**
   * Unique identifier for the role
   *
   * @example 65def3f1de3deddff04f79a7
   */
  roleId: ObjectId;
  /**
   * Name of the role
   *
   * @example Executive General Manager
   */
  name: string;
  /**
   * Flag to indicate if a limit is applied
   *
   * @example false
   */
  limitFlag: boolean;
  /**
   * Minimum limit value (can be empty)
   *
   * @example
   */
  min: string;
  /**
   * Maximum limit value
   *
   * @example 250000
   */
  max: number;
  /**
   * Status of the role
   *
   * @example completed
   */
  status: string;
};

export type FormAdditionalInfo = {
  /**
   * Name of the finance partner
   *
   * @example Finance
   */
  finance_partner_name: string;
  /**
   * Indicates if the clearance is acceptable
   *
   * @example yes
   */
  clear_acceptable: string;
  /**
   * Indicates if tax is required
   *
   * @example no
   */
  tax_required: string;
  /**
   * Indicates if insurance is required
   *
   * @example yes
   */
  insurance_required: string;
  /**
   * Details if the expense is within the budget
   *
   * @example No costs incurred SST
   */
  within_budget: string;
  /**
   * Indicates if there is an expenditure
   *
   * @example yes
   */
  expenditure: string;
  /**
   * Indicates if a commission is involved
   *
   * @example no
   */
  commission: string;
  /**
   * Additional comments, if any
   *
   * @example
   */
  comments: string;
  /**
   * Indicates if the Head of PnC is the final approver
   *
   * @example false
   */
  isHeadOfPnCFinalApprover: string;
};

export type EnvelopeSummary = {
  /**
   * Unique identifier for the envelope
   *
   * @example b6056961-d0b9-4f84-8c66-7aa1a3d39afe
   */
  envelopeId: string;
  /**
   * Current status of the envelope
   *
   * @example sent
   */
  status: string;
  /**
   * Timestamp of the status update in ISO8601 format
   *
   * @example 2024-11-21T13:29:41.6730000Z
   */
  statusDateTime: string;
  /**
   * URI of the envelope resource
   *
   * @example /envelopes/b6056961-d0b9-4f84-8c66-7aa1a3d39afe
   */
  uri: string;
};

export type WorkFlowDetails = {
  /**
   * Approval level
   *
   * @example 1
   */
  level: number;
  /**
   * Role ID associated with this level
   *
   * @example 65def3f1de3deddff04f79a7
   */
  roleId: SchemaObjectId;
  /**
   * Role name
   *
   * @example Executive General Manager
   */
  name: string;
  /**
   * Indicates if there is a limit flag
   *
   * @example false
   */
  limitFlag: boolean;
  /**
   * Minimum limit for approval
   *
   * @example 250000
   */
  min?: number;
  /**
   * Maximum limit for approval
   *
   * @example 100000
   */
  max: number;
  /**
   * Approval status
   *
   * @example completed
   */
  status: string;
};

export type GetFormDetailDto = {
  /**
   * Unique identifier of the form
   *
   * @example 673f2a34ac9471b25fdb5792
   */
  _id: ObjectId;
  /**
   * Module ID associated with the form
   *
   * @example 65e3579de0ca70fe8f2e148e
   */
  moduleId: ObjectId;
  /**
   * Unique form code
   *
   * @example SST-2024112106053799897
   */
  code: string;
  /**
   * Form information object
   */
  formInfo: IsObject;
  /**
   * List of attachments related to the form
   *
   * @example formdocuments/filesample_150kB_te_20241121T132148413Z_62048.pdf
   */
  attachments: IsString[];
  /**
   * List of MSA attachments
   *
   * @example msadocuments/file_sam_ple_150kB__20241121T124014426Z_23514.pdf
   * @example approverSignedMSADocument/file_sam_ple_150kB__20241121T124014426Z_2351…
   */
  msaAttachments: IsString[];
  /**
   * History of the form
   */
  formHistory: FromHistory[];
  /**
   * Department ID associated with the form
   *
   * @example 672acf6706b004004c729d08
   */
  department: string;
  /**
   * Workflow ID related to the form
   *
   * @example 65def561de3deddff04f79ae
   */
  workflow: string;
  /**
   * Name of the department associated with the form
   *
   * @example Technology
   */
  departmentName: string;
  /**
   * Name of the requester associated with the form
   *
   * @example mohan
   */
  requesterName: string;
  /**
   * Email of the requester associated with the form
   *
   * @example bbharathivel@nrl.com.au
   */
  requesterEmail: string;
  /**
   * Name of the workflow for the form
   *
   * @example CEO
   */
  workflowName: string;
  /**
   * Workflow version ID
   *
   * @example 65e6c40f1bc6174e00ce714b
   */
  workflowVersion: ObjectId;
  /**
   * Current status of the form
   *
   * @example fulfilled
   */
  status: string;
  /**
   * Indicates if the form is active or not
   *
   * @example true
   */
  active: boolean;
  /**
   * List of workflow order IDs
   */
  workflowOrder: WorkFlowOrder[];
  /**
   * Module code associated with the form
   *
   * @example vendor-contract
   */
  moduleCode: string;
  /**
   * Additional information specific to the form
   */
  formAdditionalInfo: FormAdditionalInfo;
  /**
   * Current status of the form in DocuSign
   *
   * @example envelope-completed
   */
  docusignStatus: string;
  /**
   * Unique envelope ID from DocuSign
   *
   * @example b6056961-d0b9-4f84-8c66-7aa1a3d39afe
   */
  envelopeId: string;
  /**
   * Summary information of the envelope
   */
  envelopeSummary: EnvelopeSummary;
  /**
   * Email of the user who created the form
   *
   * @example bbharathivel@nrl.com.au
   */
  createdBy: string;
  /**
   * Email of the user who updated the form
   *
   * @example bbharathivel@nrl.com.au
   */
  updatedBy: string;
  /**
   * Date and time when the permission is been created
   *
   * @format date-time
   * @example 2024-03-02T16:45:17.346+00:00
   */
  createdAt: string;
  /**
   * Date and time when the permission is been updated
   *
   * @format date-time
   * @example 2024-03-02T16:45:17.346+00:00
   */
  updatedAt?: string;
  /**
   * Indicates if additional access is enabled
   *
   * @example false
   */
  isAdditionalAccess: boolean;
  /**
   * Indicates if the MSA flag is set
   *
   * @example false
   */
  MSAflag: boolean;
  /**
   * Workflow details list
   */
  workflowDetails: WorkFlowDetails[];
  /**
   * Indicates if the workflow is in the last approver table or not
   *
   * @example false
   */
  isFinalApprover: boolean;
  /**
   * This flag is used to find the contract has to be moved to draft or not
   *
   * @example false
   */
  isRecallFlag: boolean;
  /**
   * This flag is used to esign is required or not
   *
   * @example false
   */
  eSignRequired: boolean;
  /**
   * This flag is used to find out workflow can be reset or not
   *
   * @example false
   */
  isWorkflowReset: boolean;
  /**
   * This flag is used to find out docusign has to be retriggered or not
   *
   * @example false
   */
  isDocuSignRetrigger: boolean;
  /**
   * Current status of the workflow
   *
   * @example {"userId":"678e14daca332048be97fa69","name":"Varunkumar Rameshbapu","email":"vrameshbapu@nrl.com.au","roleName":"First Reviewer","roleId":"676435d455a50e076bedab81","roleCode":"first-reviewer"}
   */
  specificApproverDetails?: Record<string, any>;
  /**
   * version of the form
   *
   * @example V2
   */
  version: string;
  /**
   * This describes the the singing is required or not
   *
   * @example Expenditure no contract for signing
   */
  approvalBeingSought: string;
  /**
   * This flag is used to find out edit button to be showed or not
   *
   * @example false
   */
  isFirstReviewerEditFlag: boolean;
};

export type GetFormDetailResponseDto = {
  /**
   * Form Detail found successfully
   *
   * @example Form Detail found successfully
   */
  message: string;
  /**
   * Form Detail found successfully
   */
  data: GetFormDetailDto;
};

export type UpdateFormDetailsDto = {
  /**
   * ID of the form being updated
   *
   * @example 65f47c35de3deddff04f79c1
   */
  formId: SchemaObjectId;
  /**
   * Module ID
   *
   * @example 65e3579de0ca70fe8f2e148e
   */
  moduleId: string;
  /**
   * Code for the transaction
   *
   * @example SST-2025011709394366241
   */
  code: string;
  /**
   * Department ID
   *
   * @example 672acf6706b004004c729d08
   */
  department: string;
  /**
   * Name of the department
   *
   * @example Technology
   */
  departmentName: string;
  /**
   * Information about the form
   */
  formInfo: IsObject;
  /**
   * List of attachments
   *
   * @example formdocuments/SST_Leave_policy_20250117T041228100Z_36346.pdf
   */
  attachments: string[];
  /**
   * List of MSA attachments
   *
   * @example msadocuments/SST_Leave_policy_20250117T041210343Z_40421.pdf
   */
  msaAttachments: string[];
  /**
   * Email of the user who created the form
   *
   * @example bbharathivel@nrl.com.au
   */
  createdBy: string;
  /**
   * Email of the user who updated the form
   *
   * @example bbharathivel@nrl.com.au
   */
  updatedBy: string;
  /**
   * Redirect path for email notifications
   *
   * @example /finance/vendor-contract/requests/detail/formDetailId?page=approveRequest&moduleId=65e3579de0ca70fe8f2e148e
   */
  mailRedirectPath: string;
};

export type FormHistoryDto = {
  /**
   * Email of the user who approved the workflow
   *
   * @example sshanmugasundaram@nrl.com.au
   */
  approvedBy: string;
  /**
   * Current status of the workflow
   *
   * @example approved
   */
  status: string;
  /**
   * ID of the workflow
   *
   * @example 65def477de3deddff04f79a8
   */
  workflow: string;
  /**
   * Name of the workflow
   *
   * @example Technology Admin
   */
  workflowName: string;
  /**
   * ID of the department
   *
   * @example 672acf6706b004004c729d08
   */
  department: string;
  /**
   * Name of the department
   *
   * @example Technology
   */
  departmentName: string;
  /**
   * Timestamp when the record was created
   *
   * @example 1732193541530
   */
  createdAt: number;
  /**
   * Comments about the workflow approval
   *
   * @example
   */
  comments?: string;
};

export type FormHistroyResponseDto = {
  /**
   * The data of the form history
   *
   * @example {"approvedBy":"bbharathivel@nrl.com.au","status":"initiated","workflow":"65def3f1de3deddff04f79a7","workflowName":"Executive General Manager","department":"672acf6706b004004c729d08","departmentName":"Technology","createdAt":1732192820391}
   */
  data: FormHistoryDto[];
};

export type FilterMetaResponseDto = {
  /**
   * Status of the users allowed to do permission
   *
   * @example pending
   * @example completed
   * @example rejected
   */
  status: string[];
  /**
   * Workflow order for the user
   *
   * @example {"_id":"65def3f1de3deddff04f79a7","name":"Executive General Manager"}
   * @example {"_id":"65def477de3deddff04f79a8","name":"Technology Admin"}
   */
  workflow: string[];
  /**
   * Workflow order for the user
   *
   * @example {"_id":"65e391006d98432f2ac48ab8","name":"Risk, Legal and Integrity"}
   * @example {"_id":"65e391c36d98432f2ac48abd","name":"Finance"}
   */
  department: string[];
};

export type ResetResponseDto = {
  /**
   * Message related to the retrigger
   *
   * @example The form has been Reset successfully
   */
  message: string;
};

export type DeleteResponseDto = {
  /**
   * Message related to the retrigger
   *
   * @example Form has been successfully deactivated
   */
  message: string;
};

export type RecallResponseDto = {
  /**
   * Message related to the recall
   *
   * @example The form has been successfully recalled and all users have been notified.
   */
  message: string;
};

export type GMDetailsDto = {
  /**
   * Unique identifier of the user
   *
   * @example 65e3f9bde1ca7af2e142b9c7
   */
  userId: string;
  /**
   * Full name of the user
   *
   * @example John Doe
   */
  userName: string;
  /**
   * Email address of the user
   *
   * @example john.doe@example.com
   */
  email: string;
};

export type GMDetailsResponseDto = {
  /**
   * Message indicating the result of the operation
   *
   * @example GM users are retrived!
   */
  message: string;
  /**
   * List of General Manager Users
   */
  data: GMDetailsDto[];
};

export type HeadCountWorkflowOrderDTO = {
  /**
   * The level of the workflow order
   *
   * @example 1
   */
  level: number;
  /**
   * The ID of the role associated with this workflow order
   *
   * @example 65def586de3deddff04f79af
   */
  roleId?: SchemaObjectId;
  /**
   * Flag indicating whether there is a limit in this workflow
   *
   * @example true
   */
  limitFlag?: boolean;
  /**
   * The minimum value for this workflow order
   *
   * @example 10
   */
  min?: number;
  /**
   * The maximum value for this workflow order
   *
   * @example 100
   */
  max?: number;
  /**
   * Name of the workflow order
   *
   * @example General Manager
   */
  name?: string;
  /**
   * Status of the workflow order
   *
   * @example active
   */
  status: string;
  /**
   * Flag indicating whether a specific department approver is required
   *
   * @example true
   */
  isSpecificDeptApprover?: boolean;
  /**
   * Flag indicating whether the workflow should include requester checks
   *
   * @example true
   */
  includeOnRequesterCheck?: boolean;
  /**
   * Flag indicating whether the headcount P&C final approver
   *
   * @example true
   */
  isHeadOfPnCFinalApprover?: boolean;
};

export type CreateHeadcountFormDto = {
  /**
   * Module ID
   *
   * @example 65e3579de0ca70fe8f2e148e
   */
  moduleId: ObjectId;
  /**
   * Code for the transaction
   *
   * @example SST-2025011709394366241
   */
  code: string;
  /**
   * Department ID
   *
   * @example 672acf6706b004004c729d08
   */
  department: ObjectId;
  /**
   * Name of the department
   *
   * @example Technology
   */
  departmentName: string;
  /**
   * Information about the form
   */
  formInfo: IsObject;
  /**
   * List of attachments
   *
   * @example formdocuments/SST_Leave_policy_20250117T041228100Z_36346.pdf
   */
  attachments: string[];
  /**
   * Email of the user who created the form
   *
   * @example bbharathivel@nrl.com.au
   */
  createdBy: string;
  /**
   * Email of the user who created the form
   *
   * @example bbharathivel@nrl.com.au
   */
  updatedBy: string;
  /**
   * History of the form
   */
  formHistory: IsObject[];
  /**
   * Redirect path for email notifications
   *
   * @example /finance/vendor-contract/requests/detail/formDetailId?page=approveRequest&moduleId=65e3579de0ca70fe8f2e148e
   */
  mailRedirectPath: string;
  /**
   * ID of the workflow associated with the form
   *
   * @example 65def477de3deddff04f79a8
   */
  workflow?: ObjectId;
  /**
   * Name of the workflow
   *
   * @example Technology Admin Workflow
   */
  workflowName?: string;
  /**
   * Version ID of the workflow
   *
   * @example 65def477de3deddff04f79b2
   */
  workflowVersion?: ObjectId;
  /**
   * Workflow order details
   *
   * @example {"level":1,"roleId":"65def586de3deddff04f79af","limitFlag":true,"min":1,"max":100,"name":"Manager","status":"active","isSpecificDeptApprover":true,"includeOnRequesterCheck":false,"isHeadOfPnCFinalApprover":false}
   */
  workflowOrder?: HeadCountWorkflowOrderDTO[];
  /**
   * Indicates if there is a active form
   *
   * @example false
   */
  active: boolean;
  /**
   * Status of the form
   *
   * @example pedning
   */
  status?: string;
  /**
   * Code of the module
   *
   * @example MOD-IT-2025
   */
  moduleCode?: string;
};

export type HeadcountFormDetailsDto = {
  /**
   * Unique identifier of the form
   *
   * @example 673f2a34ac9471b25fdb5792
   */
  _id: ObjectId;
  /**
   * Module ID associated with the form
   *
   * @example 65e3579de0ca70fe8f2e148e
   */
  moduleId: ObjectId;
  /**
   * Unique form code
   *
   * @example SST-2024112106053799897
   */
  code: string;
  /**
   * Form information object
   */
  formInfo: IsObject;
  /**
   * List of attachments related to the form
   *
   * @example formdocuments/filesample_150kB_te_20241121T132148413Z_62048.pdf
   */
  attachments: IsString[];
  /**
   * History of the form
   */
  formHistory: FromHistory[];
  /**
   * Department ID associated with the form
   *
   * @example 672acf6706b004004c729d08
   */
  department: string;
  /**
   * Name of the requester associated with the form
   *
   * @example BB
   */
  requesterName: string;
  /**
   * Email of the requester associated with the form
   *
   * @example bbharathivel@nrl.com.au
   */
  requesterEmail: string;
  /**
   * Workflow ID related to the form
   *
   * @example 65def561de3deddff04f79ae
   */
  workflow: string;
  /**
   * Name of the department associated with the form
   *
   * @example Technology
   */
  departmentName: string;
  /**
   * Name of the workflow for the form
   *
   * @example CEO
   */
  workflowName: string;
  /**
   * Workflow version ID
   *
   * @example 65e6c40f1bc6174e00ce714b
   */
  workflowVersion: ObjectId;
  /**
   * Current status of the form
   *
   * @example fulfilled
   */
  status: string;
  /**
   * Indicates if the form is active or not
   *
   * @example true
   */
  active: boolean;
  /**
   * List of workflow order IDs
   */
  workflowOrder: WorkFlowOrder[];
  /**
   * Module code associated with the form
   *
   * @example vendor-contract
   */
  moduleCode: string;
  /**
   * Additional information specific to the form
   */
  formAdditionalInfo: FormAdditionalInfo;
  /**
   * Email of the user who created the form
   *
   * @example bbharathivel@nrl.com.au
   */
  createdBy: string;
  /**
   * Email of the user who updated the form
   *
   * @example bbharathivel@nrl.com.au
   */
  updatedBy: string;
  /**
   * Date and time when the permission is been created
   *
   * @format date-time
   * @example 2024-03-02T16:45:17.346+00:00
   */
  createdAt: string;
  /**
   * Date and time when the permission is been updated
   *
   * @format date-time
   * @example 2024-03-02T16:45:17.346+00:00
   */
  updatedAt?: string;
};

export type CreateHeadCountResponseDto = {
  /**
   * Message indicating the result of the operation
   *
   * @example New Form has been created successfully
   */
  message: string;
  /**
   * Details of the created form
   */
  data: HeadcountFormDetailsDto;
};

export type HeadcountFormListDto = {
  /**
   * Unique identifier of the form
   *
   * @example 673f2a34ac9471b25fdb5792
   */
  _id: ObjectId;
  /**
   * Module ID associated with the form
   *
   * @example 65e3579de0ca70fe8f2e148e
   */
  moduleId: ObjectId;
  /**
   * Unique form code
   *
   * @example SST-2024112106053799897
   */
  code: string;
  /**
   * Form information object
   *
   * @example {"role_name":"developer"}
   */
  formInfo: IsObject;
  /**
   * Department identifier
   *
   * @example 672acf6706b004004c729d08
   */
  department: ObjectId;
  /**
   * Name of the department associated with the form
   *
   * @example Technology
   */
  departmentName: string;
  /**
   * Workflow identifier
   *
   * @example 65def3f1de3deddff04f79a7
   */
  workflow: ObjectId;
  /**
   * Name of the workflow for the form
   *
   * @example CEO
   */
  workflowName: string;
  /**
   * Current status of the form
   *
   * @example fulfilled
   */
  status: string;
  /**
   * Email of the user who created the form
   *
   * @example bbharathivel@nrl.com.au
   */
  createdBy: string;
  /**
   * Date when the form was created
   *
   * @example 2024-11-21T12:40:20.340+00:00
   */
  createdAt: string;
};

export type HeadcountPaginationDto = {
  /**
   * Total number of rows available
   *
   * @example 0
   */
  totalRowCount: number;
};

export type HeadcountMetaDto = {
  /**
   * Pagination information
   */
  pagination: HeadcountPaginationDto;
};

export type HeadcountFormListResponseDto = {
  /**
   * Data array containing the forms
   */
  data: HeadcountFormListDto[];
  /**
   * Meta data related to the response
   */
  meta: HeadcountMetaDto;
};

export type GetHeadcountFormDetailDto = {
  /**
   * Unique identifier of the form
   *
   * @example 673f2a34ac9471b25fdb5792
   */
  _id: ObjectId;
  /**
   * Module ID associated with the form
   *
   * @example 65e3579de0ca70fe8f2e148e
   */
  moduleId: ObjectId;
  /**
   * Unique form code
   *
   * @example SST-2024112106053799897
   */
  code: string;
  /**
   * Form information object
   */
  formInfo: IsObject;
  /**
   * List of attachments related to the form
   *
   * @example formdocuments/filesample_150kB_te_20241121T132148413Z_62048.pdf
   */
  attachments: IsString[];
  /**
   * History of the form
   */
  formHistory: FromHistory[];
  /**
   * Department ID associated with the form
   *
   * @example 672acf6706b004004c729d08
   */
  department: string;
  /**
   * Name of the requester associated with the form
   *
   * @example BB
   */
  requesterName: string;
  /**
   * Email of the requester associated with the form
   *
   * @example bbharathivel@nrl.com.au
   */
  requesterEmail: string;
  /**
   * Workflow ID related to the form
   *
   * @example 65def561de3deddff04f79ae
   */
  workflow: string;
  /**
   * Name of the department associated with the form
   *
   * @example Technology
   */
  departmentName: string;
  /**
   * Name of the workflow for the form
   *
   * @example CEO
   */
  workflowName: string;
  /**
   * Workflow version ID
   *
   * @example 65e6c40f1bc6174e00ce714b
   */
  workflowVersion: ObjectId;
  /**
   * Current status of the form
   *
   * @example fulfilled
   */
  status: string;
  /**
   * Indicates if the form is active or not
   *
   * @example true
   */
  active: boolean;
  /**
   * List of workflow order IDs
   */
  workflowOrder: WorkFlowOrder[];
  /**
   * Module code associated with the form
   *
   * @example vendor-contract
   */
  moduleCode: string;
  /**
   * Additional information specific to the form
   */
  formAdditionalInfo: FormAdditionalInfo;
  /**
   * Email of the user who created the form
   *
   * @example bbharathivel@nrl.com.au
   */
  createdBy: string;
  /**
   * Email of the user who updated the form
   *
   * @example bbharathivel@nrl.com.au
   */
  updatedBy: string;
  /**
   * Date and time when the permission is been created
   *
   * @format date-time
   * @example 2024-03-02T16:45:17.346+00:00
   */
  createdAt: string;
  /**
   * Date and time when the permission is been updated
   *
   * @format date-time
   * @example 2024-03-02T16:45:17.346+00:00
   */
  updatedAt?: string;
  /**
   * Workflow details list
   */
  workflowDetails: WorkFlowDetails[];
};

export type GetHeadcountFormDetailResponseDto = {
  /**
   * Form Detail found successfully
   *
   * @example Form Detail found successfully
   */
  message: string;
  /**
   * Form Detail found successfully
   */
  data: GetHeadcountFormDetailDto;
};

export type UpdateHeadCountResponseDto = {
  /**
   * Form has been resubmitted successfully!
   *
   * @example Form has been resubmitted successfully!
   */
  message: string;
};

export type CreateFormModuleDto = {
  /**
   * Id of the Module
   *
   * @example 65e3579de0ca70fe8f2e148e
   */
  menuModuleId: string;
  /**
   * Name of the form Module
   *
   * @example contract
   */
  name: string;
  /**
   * code of the form Module
   *
   * @example contract
   */
  code: string;
  /**
   * Description of the form Module
   *
   * @example Vendor Contract
   */
  description: string;
  /**
   * status of the form Module
   *
   * @example true
   */
  status?: boolean;
  /**
   * User who created this record
   *
   * @example vrameshbapu@nrl.com.au
   */
  createdBy: string;
  /**
   * User who updated this record
   *
   * @example vrameshbapu@nrl.com.au
   */
  updatedBy: string;
};

export type CreateUpdateModuleResponseDto = {
  /**
   * Module data created successfully
   *
   * @example The Form Module has been successfully created/deleted.
   */
  message: string;
};

export type FormModuleResponseDto = {
  /**
   * Id of the Module
   *
   * @example 65e3579de0ca70fe8f2e148e
   */
  _id: ObjectId;
  /**
   * Name of the form Module
   *
   * @example contract
   */
  name: string;
  /**
   * code of the form Module
   *
   * @example contract
   */
  code: string;
  /**
   * Descripton of the form Module
   *
   * @example Vendor Contract
   */
  description: string;
  /**
   * status of Module
   *
   * @example true
   */
  status: boolean;
  /**
   * User who created the module
   *
   * @example vrameshbapu.nrl.com.au
   */
  createdBy: string;
  /**
   * User who updated the module
   *
   * @example vrameshbapu.nrl.com.au
   */
  updatedBy?: string;
  /**
   * Date and time when the module is been created
   *
   * @format date-time
   * @example 2024-03-02T16:45:17.346+00:00
   */
  createdAt: string;
  /**
   * Date and time when the module is been updated
   *
   * @format date-time
   * @example 2024-03-02T16:45:17.346+00:00
   */
  updateAt?: string;
};

export type MetaDto = {
  /**
   * Total number of rows available
   *
   * @example 10
   */
  totalRowCount: number;
};

export type GetAllFormModuleResponseDto = {
  /**
   * list of Form Modules
   */
  data: FormModuleResponseDto[];
  /**
   * Meta information
   */
  meta: MetaDto;
};

export type GetModuleByIdResponseDto = {
  /**
   * Message describing the result of the operation
   *
   * @example Form Module found successfully
   */
  message: string;
  /**
   * The data returned by the operation
   */
  data: FormModuleResponseDto;
};

export type UpdateFormModuleResponseDto = {
  /**
   * Message describing the result of the operation
   *
   * @example Form Module has been successfully updated
   */
  message: string;
  /**
   * The updated Form Module data
   */
  data: FormModuleResponseDto;
};

export type PermissionModuleResponseDto = {
  /**
   * Id of the permission
   *
   * @example  677d567870dc1af598b322a7
   */
  _id: ObjectId;
  /**
   * Name of the permission
   *
   * @example Contract
   */
  permissionName: string;
};

export type FormModuleDropDownResponseDto = {
  /**
   * Id of the Module
   *
   * @example 65e3579de0ca70fe8f2e148e
   */
  _id: ObjectId;
  /**
   * Name of the form Module
   *
   * @example contract
   */
  name: string;
  /**
   * Name of the module
   */
  permissions: PermissionModuleResponseDto[];
};

export type GetAllModulesResponseDto = {
  /**
   * Message describing the result of the operation
   *
   * @example Form Module found successfully
   */
  message: string;
  /**
   * The data returned by the operation
   */
  data: FormModuleDropDownResponseDto[];
};

export type UpdateFormApprovalDto = {
  /**
   * ID of the module
   *
   * @example 64e4567de12a6f23b6548c92
   */
  moduleId: string;
  /**
   * Email ID of the user approving or updating the form
   *
   * @example user@example.com
   */
  emailId: string;
  /**
   * ID of the form being approved
   *
   * @example 64f6789bcde23a4567df8901
   */
  formId: SchemaObjectId;
  /**
   * Comments or notes related to the update
   *
   * @example Approved by the manager for further processing.
   */
  comments?: string;
  /**
   * Approval status of the form
   *
   * @example approved
   */
  status?: string;
  /**
   * Flag indicating if additional access is required
   *
   * @example true
   */
  isAdditionalAccess?: boolean;
  /**
   * Additional information related to the form in object format
   *
   * @example {"key":"value","additionalNotes":"Some additional information."}
   */
  formAdditionalInfo?: Record<string, any>;
  /**
   * Mail redirect path to be used for notifications
   *
   * @example /redirect/path
   */
  mailRedirectPath: string;
  /**
   * Indicator for final approval by the head of PnC
   *
   * @example true
   */
  isHeadOfPnCFinalApprover?: boolean;
  /**
   * Indicates esign is required for this contract
   *
   * @example true
   */
  eSignRequired: boolean;
  /**
   * Indicates witness for esign is required or not
   *
   * @example true
   */
  witnessFlag: boolean;
  /**
   * Name of the witness
   *
   * @example Varun
   */
  witnessName?: string;
  /**
   * Name of the witness
   *
   * @example Vrameshbapu@nrl.com.au
   */
  witnessEmail?: string;
};

export type FormApprovalMessageDto = {
  /**
   * Message related to the form
   *
   * @example Form approved successfully!
   */
  message: string;
  /**
   * Signing url
   *
   * @example Form approved successfully!
   */
  signingUrl: string;
};

export type SignerDto = {
  /**
   * Name of the signer
   *
   * @example Sagar S
   */
  name: string;
  /**
   * Email of the signer
   *
   * @example sagarsrinivas94@gmail.com
   */
  email: string;
  /**
   * Status of the signer (e.g., completed, declined)
   *
   * @example completed
   */
  status: string;
  /**
   * The routing order for the signer in the signing process
   *
   * @example 1
   */
  routingOrder: string;
  /**
   * Date and time the document was signed by the signer
   *
   * @example 2024-09-11T05:14:29.903Z
   */
  signedDateTime: string;
  /**
   * Reason for the signer’s inclusion in the process
   *
   * @example sender
   */
  creationReason: string;
};

export type DeclinedUserDto = {
  /**
   * Email of the user who declined the envelope
   *
   * @example sagarsrinivas94+2@gmail.com
   */
  email: string;
  /**
   * Name of the user who declined the envelope
   *
   * @example Sagar Srini
   */
  name: string;
  /**
   * Reason for declining the envelope
   *
   * @example Test decline reason
   */
  reason: string;
};

export type EnvelopeDetailsDto = {
  /**
   * Unique identifier for the envelope
   *
   * @example 14ed4515-27ec-48e9-8c88-aa677827649f
   */
  envelopeId: string;
  /**
   * Status of the envelope
   *
   * @example envelope-completed
   */
  envelopeStatus: string;
  /**
   * List of signers involved in the envelope process
   */
  signers: SignerDto[];
  /**
   * Details of the user who declined the envelope, if applicable
   */
  declinedUser: DeclinedUserDto;
  /**
   * The bucket name where the document needs to be updated by the signature servicee
   *
   * @example bucket-name
   */
  signedBucketName: string;
  /**
   * Dockey of the envelope
   *
   * @example 14ed4515-27ec-48e9-8c88-aa677827649f
   */
  signedDocKey: string;
};

export type CallbackMessageDto = {
  /**
   * Message related to the form
   *
   * @example Callback event envelope-completed  hit successfully
   */
  message: string;
};

export type RetriggerResponseDto = {
  /**
   * Message related to the retrigger
   *
   * @example E-sign Resend Successfully! You will soon receive an email from DocuSign to sign the agreement. Please check your inbox!
   */
  message: string;
};

export type FormMessageDto = {
  /**
   * Message related to the form
   *
   * @example Form approved successfully!
   */
  message: string;
};

export type CreateDepartmentsDto = {
  /**
   * Id of the Module
   *
   * @example 65e3579de0ca70fe8f2e148e
   */
  menuModuleId: string;
  /**
   * Name of the department
   *
   * @example Technology
   */
  name: string;
  /**
   * Code of the department
   *
   * @example technology
   */
  code?: string;
  /**
   * Description of the department
   *
   * @example Technology - Department
   */
  description?: string;
  /**
   * Id of the modules
   *
   * @example 65e3579de0ca70fe8f2e148e
   */
  moduleId?: string[];
  /**
   * Role of the department
   *
   * @example 65e3579de0ca70fe8f2e148e
   */
  roles?: string[];
  /**
   * status of the department
   *
   * @example true
   */
  status?: boolean;
  /**
   * User who created this record
   *
   * @example bbharathivel@nrl.com.au
   */
  createdBy: string;
  /**
   * User who updated this record
   *
   * @example bbharathivel@nrl.com.au
   */
  updatedBy: string;
};

export type CreateUpdateDepartmentResponseDto = {
  /**
   * Department data created successfully
   *
   * @example The Department has been successfully created/updated/deleted.
   */
  message: string;
};

export type DeptModuleResponse = {
  /**
   * Id of the module
   *
   * @example  677d567870dc1af598b322a7
   */
  _id: string;
  /**
   * Name of the module
   *
   * @example Contract
   */
  name: string;
};

export type DeptRoleResponse = {
  /**
   * Id of the role
   *
   * @example  677d567870dc1af598b322a7
   */
  _id: string;
  /**
   * Name of the role
   *
   * @example Contract
   */
  name: string;
};

export type GetDepartmentResponseDto = {
  /**
   * Id of the department
   *
   * @example  677d567870dc1af598b322a7
   */
  _id: string;
  /**
   * Name of the department
   *
   * @example Technology
   */
  name: string;
  /**
   * Code of the department
   *
   * @example technology
   */
  code: string;
  /**
   * description of the department
   *
   * @example technology
   */
  description: string;
  /**
   * Code of the department
   */
  module: DeptModuleResponse[];
  /**
   * roles of the department
   */
  roles: DeptRoleResponse[];
  /**
   * status of the department
   *
   * @example true
   */
  status: boolean;
  /**
   * user created the department
   *
   * @example bbharathivel@nrl.com.au
   */
  createdBy: string;
  /**
   * user updated the department
   *
   * @example bbharathivel@nrl.com.au
   */
  updatedBy: string;
  /**
   * Date and time when the department is been created
   *
   * @format date-time
   * @example 2024-03-02T16:45:17.346+00:00
   */
  createdAt: string;
  /**
   * Date and time when the department is been updated
   *
   * @format date-time
   * @example 2024-03-02T16:45:17.346+00:00
   */
  updateAt?: string;
};

export type GetAllPerissionsAdminResponseDto = {
  /**
   * Message describing the result of the operation
   *
   * @example  All Departments data found successfully
   */
  message: string;
  /**
   * list of Departments
   */
  data: GetDepartmentResponseDto[];
  /**
   * Meta information
   */
  meta: MetaDto;
};

export type GetDepartmentByIdResponseDto = {
  /**
   * The data returned by the operation
   */
  data: GetDepartmentResponseDto;
};

export type GetDropDownResponseDto = {
  /**
   * Id of the department
   *
   * @example 65e3923a6d98432f2ac48ac1
   */
  _id: ObjectId;
  /**
   * Name of the department
   *
   * @example Technology
   */
  name: string;
};

export type GetAllDepartmentResponseDto = {
  /**
   * Message describing the result of the operation
   *
   * @example  All Departments  data found successfully
   */
  message: string;
  /**
   * The data returned by the operation
   */
  data: GetDropDownResponseDto[];
};

export type RoleDto = {
  /**
   * Unique identifier of the role
   *
   * @example 65def4b2de3deddff04f79a9
   */
  _id: string;
  /**
   * Name of the role
   *
   * @example Insurance Admin
   */
  name: string;
};

export type DepartmentWithRolesDto = {
  /**
   * Unique identifier of the department
   *
   * @example 65e3923a6d98432f2ac48ac1
   */
  _id: string;
  /**
   * Name of the department
   *
   * @example Insurance
   */
  name: string;
  /**
   * List of roles associated with the department
   */
  roles: RoleDto[];
};

export type GetAllDepartmentsWithRolesResponseDto = {
  /**
   * Response message
   *
   * @example All departments retrieved successfully
   */
  message: string;
  /**
   * Array of department objects with associated roles
   */
  data: DepartmentWithRolesDto[];
};

export type CreatePermissionsDto = {
  /**
   * Id of the Module
   *
   * @example 65e3579de0ca70fe8f2e148e
   */
  menuModuleId: string;
  /**
   * Id of the Module
   *
   * @example 67724451c6fdbee05f9644f8
   */
  moduleId: ObjectId;
  /**
   * Premission code
   *
   * @example view-Contract-request
   */
  permissionCode?: string;
  /**
   * Premission name
   *
   * @example view-Contract-request
   */
  permissionName: string;
  /**
   * Module code
   *
   * @example contract
   */
  moduleCode?: string;
  /**
   * Module name
   *
   * @example contract
   */
  moduleName?: string;
  /**
   * description of the module
   *
   * @example Allows access to module settings page
   */
  description: string;
  /**
   * status of the permission
   *
   * @example true
   */
  status?: boolean;
  /**
   * status of the module
   *
   * @example true
   */
  moduleStatus?: boolean;
  /**
   * User who created this record
   *
   * @example vrameshbapu@nrl.com.au
   */
  createdBy: string;
  /**
   * User who updated this record
   *
   * @example vrameshbapu@nrl.com.au
   */
  updatedBy: string;
};

export type CreateUpdatePermissionResponseDto = {
  /**
   * Permission data created successfully
   *
   * @example The Permission has been successfully created/updated/deleted.
   */
  message: string;
};

export type PermissionResponseDto = {
  /**
   * Id of the Permission
   *
   * @example  677d567870dc1af598b322a7
   */
  _id: string;
  /**
   * Id of the Permission
   *
   * @example 67724451c6fdbee05f9644f8
   */
  moduleId: ObjectId;
  /**
   * Premission code
   *
   * @example view-Contract-request
   */
  permissionCode: string;
  /**
   * Premission name
   *
   * @example view-Contract-request
   */
  permissionName: string;
  /**
   * Module code
   *
   * @example contract
   */
  moduleCode: string;
  /**
   * Module name
   *
   * @example contract
   */
  moduleName: string;
  /**
   * description of the module
   *
   * @example Allows access to module settings page
   */
  description: string;
  /**
   * Status of permission
   *
   * @example true
   */
  status: boolean;
  /**
   * Status of module
   *
   * @example true
   */
  moduleStatus: boolean;
  /**
   * User who created the permission
   *
   * @example vrameshbapu.nrl.com.au
   */
  createdBy: string;
  /**
   * User who updated the permission
   *
   * @example vrameshbapu.nrl.com.au
   */
  updatedBy: string;
  /**
   * Date and time when the permission is been created
   *
   * @format date-time
   * @example 2024-03-02T16:45:17.346+00:00
   */
  createdAt: string;
  /**
   * Date and time when the permission is been updated
   *
   * @format date-time
   * @example 2024-03-02T16:45:17.346+00:00
   */
  updateAt?: string;
};

export type GetAllPerissionsResponseDto = {
  /**
   * list of Permissions
   */
  data: PermissionResponseDto[];
  /**
   * Meta information
   */
  meta: MetaDto;
};

export type GetPerissionsDetailsResponseDto = {
  /**
   * Detail of Permissions
   */
  data: PermissionResponseDto;
};

export type GetAllPermissionDto = {
  /**
   * Id of the permission
   *
   * @example  6764830f06b3bf201a390f86
   */
  _id: ObjectId;
  /**
   * Code of the permission
   *
   * @example  view-contract-request
   */
  permissionCode: string;
  /**
   * Name of the permission
   *
   * @example  view-contract-request
   */
  permissionName: string;
};

export type GetAllPermissionResponseDto = {
  /**
   * Message describing the result of the operation
   *
   * @example  All Permission data found successfully
   */
  message: string;
  /**
   * The data returned by the operation
   */
  data: GetAllPermissionDto[];
};

export type CreateRolesDto = {
  /**
   * Id of the Module
   *
   * @example 65e3579de0ca70fe8f2e148e
   */
  menuModuleId: string;
  /**
   * name of the role
   *
   * @example Requester
   */
  name: string;
  /**
   * name of the role
   *
   * @example Requester
   */
  code: string;
  /**
   * description of the role
   *
   * @example Guest user
   */
  description: string;
  /**
   * module accessible for the role
   *
   * @example 65def54ade3deddff04f79ad
   * @example 65def561de3deddff04f79ae
   * @example 65def325de3deddff04f79a0
   */
  moduleId: string[];
  /**
   * Status of the role
   *
   * @example true
   */
  status?: boolean;
  /**
   * Is this Module Admin
   *
   * @example 65e3579de0ca70fe8f2e148e
   */
  permissions?: string[];
  /**
   * who created the role
   *
   * @example vrameshbapu@nrl.com.au
   */
  createdBy: string;
  /**
   * who updated the role
   *
   * @example vrameshbapu@nrl.com.au
   */
  updatedBy: string;
};

export type CreateUpdateRoleResponseDto = {
  /**
   * Role data created successfully
   *
   * @example The Role has been successfully created/updated/deleted.
   */
  message: string;
};

export type PermissionsDto = {
  /**
   * Unique identifier of the module entity
   *
   * @example 65e3579de0ca70fe8f2e148e
   */
  _id: ObjectId;
  /**
   * Unique identifier for the module
   *
   * @example 65e3579de0ca70fe8f2e148e
   */
  moduleId: ObjectId;
  /**
   * Code representing the permission
   *
   * @example read-access
   */
  permissionCode: string;
  /**
   * Name of the permission
   *
   * @example Read Access
   */
  permissionName: string;
  /**
   * Code representing the module
   *
   * @example user-management
   */
  moduleCode: string;
  /**
   * Name of the module
   *
   * @example User Management
   */
  moduleName: string;
  /**
   * Status of the module
   *
   * @example true
   */
  moduleStatus: boolean;
  /**
   * Description of the module
   *
   * @example This module handles user-related operations.
   */
  description: string;
  /**
   * Overall status of the entity
   *
   * @example true
   */
  status: boolean;
};

export type RolesListDto = {
  /**
   * Id of the role
   *
   * @example 677dfb7a8baf600dfa524bb4
   */
  _id: ObjectId;
  /**
   * name of the role
   *
   * @example Requester
   */
  name: string;
  /**
   * name of the role
   *
   * @example Requester
   */
  code: string;
  /**
   * description of the role
   *
   * @example Guest user
   */
  description: string;
  /**
   * module accessible for the role
   *
   * @example 65e3579de0ca70fe8f2e148e
   * @example 65e357e0e0ca70fe8f2e1490
   * @example 65def137de3deddff04f799b
   */
  moduleId: string[];
  /**
   * Status of the role
   *
   * @example true
   */
  status?: boolean;
  /**
   * Is this Module Admin
   */
  permissions?: PermissionsDto[];
  /**
   * User name who created the role
   *
   * @example bbharathivel@nrl.com.au
   */
  createdBy?: string;
  /**
   * User name who updated the role
   *
   * @example bbharathivel@nrl.com.au
   */
  updatedBy?: string;
  /**
   * Date and time when the permission is been created
   *
   * @format date-time
   * @example 2024-03-02T16:45:17.346+00:00
   */
  createdAt: string;
  /**
   * Date and time when the permission is been updated
   *
   * @format date-time
   * @example 2024-03-02T16:45:17.346+00:00
   */
  updateAt?: string;
};

export type AdminRolesResponseDto = {
  /**
   * Message describing the result of the operation
   *
   * @example  Users data found successfully
   */
  message: string;
  /**
   * The data returned by the operation
   */
  data: UserListResponseDto[];
  /**
   * Meta data related to the response
   */
  meta: MetaDto;
};

export type ModulePermissionResponseDto = {
  /**
   * Id of the permission
   *
   * @example  677d567870dc1af598b322a7
   */
  _id: ObjectId;
  /**
   * Name of the permission
   *
   * @example Contract
   */
  name: string;
};

export type ModuleResponseDto = {
  /**
   * Id of the module
   *
   * @example  677d567870dc1af598b322a7
   */
  _id: ObjectId;
  /**
   * Name of the module
   *
   * @example Contract
   */
  name: string;
  /**
   * Name of the module
   */
  permissions: ModulePermissionResponseDto[];
};

export type RolesDto = {
  /**
   * Id of the role
   *
   * @example 677dfb7a8baf600dfa524bb4
   */
  _id: ObjectId;
  /**
   * name of the role
   *
   * @example Requester
   */
  name: string;
  /**
   * name of the role
   *
   * @example Requester
   */
  code: string;
  /**
   * description of the role
   *
   * @example Guest user
   */
  description: string;
  /**
   * module accessible for the role
   */
  module: ModuleResponseDto[];
  /**
   * Status of the role
   *
   * @example true
   */
  status?: boolean;
  /**
   * User name who created the role
   *
   * @example bbharathivel@nrl.com.au
   */
  createdBy?: string;
  /**
   * User name who updated the role
   *
   * @example bbharathivel@nrl.com.au
   */
  updatedBy?: string;
  /**
   * Date and time when the permission is been created
   *
   * @format date-time
   * @example 2024-03-02T16:45:17.346+00:00
   */
  createdAt: string;
  /**
   * Date and time when the permission is been updated
   *
   * @format date-time
   * @example 2024-03-02T16:45:17.346+00:00
   */
  updateAt?: string;
};

export type GetRoleByIdResponseDto = {
  /**
   * Message describing the result of the operation
   *
   * @example  All Role data found successfully
   */
  message: string;
  /**
   * The data returned by the operation
   */
  data: RolesDto;
};

export type ConfigurationDto = {
  /**
   * Id of the role
   *
   * @example 677dfb7a8baf600dfa524bb4
   */
  _id: ObjectId;
  /**
   * name of the role
   *
   * @example Requester
   */
  name: string;
  /**
   * name of the role
   *
   * @example Requester
   */
  code: string;
};

export type ConfigurationResponseDto = {
  /**
   * Message describing the result of the operation
   *
   * @example  All Roles data found successfully
   */
  message: string;
  /**
   * The data returned by the operation
   */
  data: ConfigurationDto[];
};

export type RolesDropDownDto = {
  /**
   * Id of the role
   *
   * @example 677dfb7a8baf600dfa524bb4
   */
  _id: ObjectId;
  /**
   * name of the role
   *
   * @example Requester
   */
  name: string;
  /**
   * name of the code
   *
   * @example Requester
   */
  code: string;
};

export type GetAllRolesResponseDto = {
  /**
   * Message describing the result of the operation
   *
   * @example  All Roles data found successfully
   */
  message: string;
  /**
   * The data returned by the operation
   */
  data: RolesDropDownDto[];
};

export type UrlDto = {
  /**
   * The URL for accessing the object in S3
   *
   * @example https://dev-form-builder-ent-bucket.s3.ap-southeast-2.amazonaws.com/sample.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=ASIA2SFQEUYDQJY3IFC3%2F20250115%2Fap-southeast-2%2Fs3%2Faws4_request&X-Amz-Date=20250115T061248Z&X-Amz-Expires=3600&X-Amz-Security-Token=FwoGZXIvYXdzEEAaDA7z7%2FUx9pOluKIQUiKcAjX4Nw%2BTsZke5bMKKLJSRO9qGmURHFhAwtLnevQVBG4Z9shcFDR3tQ4sE2yeTgKq7KEBOrAJuMKWY13u%2FncJMR%2FmXWlapStZS5giML8mW%2BcmcbFUMnysdUMduVMCXAYV%2F5kul1Rq8NSnYz%2BVkC67hDjS%2B78QRGiC0yUB8JLw3F%2BQ02dhtXDferMZoSNsBe6TBDIayWw9OVjHRlSGE7GDYvRbw5Wf319alW8qPWUlzMp%2BruSeYQyVxVJrvrP4JriBcd6plEbJ6yOCsC2sGPqbzF7ciFJEW2am2yd2u6qEAu74Tb6M1F5hk899s3ZgtsuG0PUiex8z7w%2F1UW8%2FabrO9FRTDcq7jGAVXQLt7ZD1yE6Hb7iFP5y7yYg6SQ1hKIGjnbwGMiqLZf9iGcvSatG6x7s%2Bp5o%2FYY69Qtn08nLtsWzGR7G8UJ1Y0nsNORKxZVA%3D&X-Amz-Signature=16b24def903c8acb307bd10caa7bdf95a45d708516f540a3ae29d1e2e814109c&X-Amz-SignedHeaders=host&x-id=PutObject
   */
  url: string;
};

export type UpdateFormRequestDto = {
  /**
   * Id of the form
   *
   * @example 673f2a34ac9471b25fdb5792
   */
  formId: string;
  /**
   * Location path of s3
   *
   * @example s3://my-sample-bucket/documents/sample.pdf ./local-directory/
   */
  s3Location: string;
};

export type UploadResponseDto = {
  /**
   * Status message of the upload operation
   *
   * @example Document successfully uploaded
   */
  message: string;
  /**
   * HTTP status code of the response
   *
   * @example 200
   */
  status: number;
  /**
   * The S3 location of the uploaded document
   *
   * @example https://my-sample-bucket.s3.ap-southeast-2.amazonaws.com/documents/sample.pdf
   */
  data: string;
};

export type HeadersDto = {
  /**
   * Amazon S3 unique ID for the request
   *
   * @example Vr9gGcRQUgYUvr9zrvvGjodqvmuHy5RUFiJuzWE6AdiEGVxaTPyImfH6nvoWtCArNvMBn/edNvaidcaANmQBtgwEto8DhbsGKs221EUtfno=
   */
  xAmzId2: string;
  /**
   * Amazon S3 request ID for tracking
   *
   * @example XM5S9PNS8SNR45ST
   */
  xAmzRequestId: string;
  /**
   * Response date in GMT
   *
   * @example Wed, 22 Jan 2025 04:42:07 GMT
   */
  date: string;
  /**
   * Last modified timestamp of the file
   *
   * @example Thu, 21 Nov 2024 13:36:26 GMT
   */
  lastModified: string;
  /**
   * ETag value for the file
   *
   * @example "c7c238f45449268e4475c439327ba5d8"
   */
  etag: string;
  /**
   * Number of tags associated with the file
   *
   * @example 2
   */
  xAmzTaggingCount: string;
  /**
   * Type of server-side encryption used
   *
   * @example AES256
   */
  xAmzServerSideEncryption: string;
  /**
   * Range units accepted by the server
   *
   * @example bytes
   */
  acceptRanges: string;
  /**
   * Content type of the file
   *
   * @example application/pdf
   */
  contentType: string;
  /**
   * Size of the file in bytes
   *
   * @example 314761
   */
  contentLength: string;
  /**
   * Server responding to the request
   *
   * @example AmazonS3
   */
  server: string;
};

export type GenerateDownloadResponseDto = {
  /**
   * Data content as a string
   *
   * @example JVBERi0xLjUKJfv8/f4KMTYgMCBvYmoKPDwvTGVuZ3RoIDI3MTYvRmlsdGVyL0ZsYXRlRGVjb2RlPj5zdHJlYW0KeJytGk2LLDfu3r+izoHpteSPsmFo6JmeCeSW3YE9hJySzYbw3sLmkr8fWbZlub5ed14YmLbLsiTrW64yZ5j+OP1/MpOhkU/+jFN0cI7T7/85/fub6X8nmPLf7/89+XCeJ/oXJxfhnKYZ49kT2PTLNwUB/RHYy8cJTZhmN08fP0//eIcJ4/Txyw/PBgwaa5zxJlye4NnM/D9e7LNJ5sqPf/z47vT2cfp+gXB2RDVEQ8xVnJBxDijNbGLDY17o+SuvBXo2mxv9vtGKo9G7CWAMAtCKo9GNn14Z9o12ZjyzSbQyAwCd5fLx2xZTLIrgEwlhZMoRaSIJ
   */
  data: string;
  /**
   * Headers containing metadata and file information
   */
  headers: HeadersDto;
};

export type GeneratePreSignedUrlResponseDto = {
  /**
   * The URL of the client
   *
   * @example https://example.com/resource/12345
   */
  getUrl: string;
};

export type DepartmentDto = {
  /**
   * Unique identifier of the department
   *
   * @example 65e767af49834fc6088bfba7
   */
  _id: string;
  /**
   * List of roles associated with the department
   *
   * @example 65def325de3deddff04f79a0
   * @example 65def561de3deddff04f79ae
   */
  roles: string[];
};

export type CreateUsersDto = {
  /**
   * Id of the Module
   *
   * @example 65e3579de0ca70fe8f2e148e
   */
  menuModuleId: string;
  /**
   * Name of the user
   *
   * @example Mohan Murugesan
   */
  name: string;
  /**
   * Email address of the user
   *
   * @example mmurugesan@nrl.com.au
   */
  email: string;
  /**
   * List of departments the user belongs to
   */
  departments: DepartmentDto[];
  /**
   * Status of the user
   *
   * @example true
   */
  status: boolean;
  /**
   * User who created this record
   *
   * @example bbharathivel@nrl.com.au
   */
  createdBy: string;
  /**
   * User who created this record
   *
   * @example bbharathivel@nrl.com.au
   */
  updatedBy: string;
};

export type CreateUpdateUserResponseDto = {
  /**
   * User data created successfully
   *
   * @example The User has been successfully created/updated/deleted.
   */
  message: string;
};

export type DepartmentsListDto = {
  /**
   * Name of the department
   *
   * @example Chief Department
   */
  name: string;
  /**
   * Array of roles associated with the department
   *
   * @example CEO
   * @example EGM
   */
  roles: string[];
};

export type UserListResponseDto = {
  /**
   * Unique identifier for the user
   *
   * @example 677d567870dc1af598b322a7
   */
  _id: ObjectId;
  /**
   * Name of the user
   *
   * @example Adamtest2
   */
  name: string;
  /**
   * Email address of the user
   *
   * @example vrameshbapu1@nrl.com.au
   */
  email: string;
  /**
   * List of departments the user is associated with
   */
  departments: DepartmentsListDto[];
  /**
   * Array of modules associated with the role
   *
   * @example Contract
   * @example Headcount
   * @example Settings
   */
  modules: string[];
  /**
   * Array of permisions associated with the role
   *
   * @example View Forms Menu
   * @example View Configuration
   * @example View My Requests Tab
   */
  permissions: string[];
  /**
   * Status of the user account
   *
   * @example true
   */
  status: boolean;
  /**
   * User who created this record
   *
   * @example bbharathivel@nrl.com.au
   */
  createdBy: string;
  /**
   * User who last updated this record
   *
   * @example bbharathivel@nrl.com.au
   */
  updatedBy: string;
};

export type PermissionDto = {
  /**
   * Unique identifier for the permission
   *
   * @example 6764830f06b3bf201a390f86
   */
  _id: ObjectId;
  /**
   * Status of the permission
   *
   * @example true
   */
  status: boolean;
  /**
   * Permission code
   *
   * @example view-contract-request
   */
  permissionCode: string;
  /**
   * Human-readable name for the permission
   *
   * @example view-configuration
   */
  permissionName: string;
  /**
   * Module ID associated with the permission
   *
   * @example 65e3579de0ca70fe8f2e148e
   */
  moduleId: ObjectId;
  /**
   * Code representing the module
   *
   * @example contract
   */
  moduleCode: string;
  /**
   * Name of the module
   *
   * @example Contract
   */
  moduleName: string;
  /**
   * Status of the module
   *
   * @example true
   */
  moduleStatus: boolean;
};

export type RoleResponseDto = {
  /**
   * Unique identifier of the role
   *
   * @example 65def325de3deddff04f79a0
   */
  _id: ObjectId;
  /**
   * Name of the role
   *
   * @example Super Admin
   */
  name: string;
  /**
   * Code of the role
   *
   * @example super-admin
   */
  code: string;
  /**
   * Description of the role
   *
   * @example Super Admin
   */
  description: string;
  /**
   * Array of module IDs associated with the role
   *
   * @example 65e3579de0ca70fe8f2e148e
   * @example 65e357e0e0ca70fe8f2e1490
   * @example 65def137de3deddff04f799b
   */
  moduleId: ObjectId[];
  /**
   * Permissions associated with the role
   */
  permissions: PermissionDto[];
  /**
   * Status of the role
   *
   * @example true
   */
  status: boolean;
};

export type DepartmentsDto = {
  /**
   * Unique identifier of the department
   *
   * @example 65e767af49834fc6088bfba7
   */
  _id: ObjectId;
  /**
   * Code of the department
   *
   * @example chief-department
   */
  code: string;
  /**
   * Name of the department
   *
   * @example Chief Department
   */
  name: string;
  /**
   * Array of roles associated with the department
   */
  roles: RoleResponseDto[];
};

export type UserResponseDto = {
  /**
   * Unique identifier for the user
   *
   * @example 677d567870dc1af598b322a7
   */
  _id: ObjectId;
  /**
   * Name of the user
   *
   * @example Adamtest2
   */
  name: string;
  /**
   * Email address of the user
   *
   * @example vrameshbapu1@nrl.com.au
   */
  email: string;
  /**
   * List of departments the user is associated with
   */
  departments: DepartmentsDto[];
  /**
   * Status of the user account
   *
   * @example true
   */
  status: boolean;
  /**
   * User who created this record
   *
   * @example bbharathivel@nrl.com.au
   */
  createdBy: string;
  /**
   * User who last updated this record
   *
   * @example bbharathivel@nrl.com.au
   */
  updatedBy: string;
};

export type GetUserByIdResponseDto = {
  /**
   * Message describing the result of the operation
   *
   * @example  User data found successfully
   */
  message: string;
  /**
   * The data returned by the operation
   */
  data: UserResponseDto;
};

export type GetDropDownResponse = {
  /**
   * Id of the user
   *
   * @example  677d567870dc1af598b322a7
   */
  _id: ObjectId;
  /**
   * Name of the user
   *
   * @example  Adam
   */
  name: string;
};

export type GetAllUsersResponseDto = {
  /**
   * Message describing the result of the operation
   *
   * @example  User data found
   */
  message: string;
  /**
   * The data returned by the operation
   */
  data: GetDropDownResponse[];
};

export type ModuleDto = {
  /**
   * Unique identifier for the module
   *
   * @example 65e3579de0ca70fe8f2e148e
   */
  _id: ObjectId;
  /**
   * Name of the module
   *
   * @example Contract
   */
  name: string;
  /**
   * Code representing the module
   *
   * @example contract
   */
  code: string;
  /**
   * Status of the module
   *
   * @example true
   */
  status: boolean;
  /**
   * List of permissions for the module
   *
   * @example view-forms-menu
   * @example view-my-requests-tab
   */
  permissions: string[];
};

export type UserDataDto = {
  /**
   * Username of the user
   *
   * @example
   */
  username: string;
  /**
   * Email address of the user
   *
   * @example bala@nrl.com.auff
   */
  email: string;
  /**
   * Roles assigned to the user
   */
  roles: RoleDto[];
  /**
   * Modules accessible to the user
   */
  modules: ModuleDto[];
};

export type UserMetaResponseDto = {
  /**
   * Data payload containing user information
   */
  data: UserDataDto;
};

export type ImpersonateUserDto = {
  /**
   * Name of the user
   *
   * @example Mohan
   */
  name: string;
  /**
   * Email Id of the user
   *
   * @example bbharathivel@nrl.com.au
   */
  email: string;
  /**
   * Department of users
   *
   * @example Chief Department - Super Admin, CEO
   * @example Technology - Executive General Manager, General Manager
   */
  departments: string[];
};

export type UserImpersonateResponseDto = {
  /**
   * Data payload containing user information
   */
  data: ImpersonateUserDto[];
};

export type WorkflowOrdertDTO = {
  /**
   * id of the workflow order for frontend purpose
   *
   * @example 676435d455a50e076bedab81
   */
  id?: string;
  /**
   * level of the workflow order
   *
   * @example 1
   */
  level: number;
  /**
   * role of the workflow order
   *
   * @example 676435d455a50e076bedab81
   */
  role?: SchemaObjectId;
  /**
   * limit flag of the workflow order
   *
   * @example true
   */
  limitFlag?: boolean;
  /**
   * min number of the workflow order
   *
   * @example 1
   */
  min?: number;
  /**
   * max number of the workflow order
   *
   * @example 1
   */
  max?: number;
  /**
   * Specific Department Approver
   *
   * @example true
   */
  isSpecificDeptApprover?: boolean;
  /**
   * Include On Requester Check
   *
   * @example true
   */
  includeOnRequesterCheck?: boolean;
  /**
   * If it is true then only legal and cfo workflow will be added
   *
   * @example true
   */
  deedOfNovation?: boolean;
  /**
   * If it is true, then we can bypass the technology admin workflow
   *
   * @example true
   */
  byPassWorkflow?: boolean;
  /**
   * Code of the workflow order
   *
   * @example first-reviewer
   */
  code?: string;
  /**
   * name of the workflow order
   *
   * @example First Reviewer
   */
  name?: string;
};

export type CreateWorkflowDto = {
  /**
   * Id of the workflow
   *
   * @example 65e6c40f1bc6174e00ce714b
   */
  _id: ObjectId;
  /**
   * Id of the moduleId
   *
   * @example 65e3579de0ca70fe8f2e148e
   */
  moduleId: ObjectId;
  /**
   * Version Number
   *
   * @example 1
   */
  version?: number;
  /**
   * Order of the workflow
   */
  workflowOrder?: WorkflowOrdertDTO[];
  /**
   * Status of the workflow
   *
   * @example true
   */
  status?: boolean;
};

export type CreateUpdateWorkflowResponseDto = {
  /**
   * Workflow data created successfully
   *
   * @example The Workflow has been successfully created/updated/deleted.
   */
  message: string;
};

export type WorkflowDto = {
  /**
   * Id of the workflow
   *
   * @example 65e6c40f1bc6174e00ce714b
   */
  _id: ObjectId;
  /**
   * Id of the moduleId
   *
   * @example 65e3579de0ca70fe8f2e148e
   */
  moduleId: ObjectId;
  /**
   * Version Number
   *
   * @example 1
   */
  version?: number;
  /**
   * Order of the workflow
   */
  workflowOrder?: WorkflowOrdertDTO[];
  /**
   * Order of the workflow
   *
   * @example bala@nrl.com.au
   */
  createdBy?: string;
  /**
   * Order of the workflow
   *
   * @example bala@nrl.com.au
   */
  updatedBy?: string;
  /**
   * Status of the workflow
   *
   * @example true
   */
  status?: boolean;
  /**
   * Date and time when the workflow has been created
   *
   * @format date-time
   * @example 2024-03-02T16:45:17.346+00:00
   */
  createdAt: string;
  /**
   * Date and time when the workflow has been updated
   *
   * @format date-time
   * @example 2024-03-02T16:45:17.346+00:00
   */
  updateAt?: string;
};

export type WorkflowByMouduleIdResponseDto = {
  /**
   * Message describing the result of the operation
   *
   * @example  All workflow data found successfully
   */
  message: string;
  /**
   * The data returned by the operation
   *
   * @example {"summary":"Sample Workflow Response","value":{"_id":"65e3579de0ca70fe8f2e148e","moduleId":"65e3579de0ca70fe8f2e148e","version":1,"workflowOrder":[{"level":1,"role":"676435d455a50e076bedab81","limitFlag":true,"min":0,"max":100,"isSpecificDeptApprover":false,"includeOnRequesterCheck":true,"deedOfNovation":true,"byPassWorkflow":true,"code":"first-reviewer","name":"First Reviewer"}],"createdBy":"user123","updatedBy":"user456","status":true,"createdAt":"2024-03-02T16:45:17.346+00:00","updateAt":"2024-03-03T10:20:00.000+00:00"}}
   */
  data: WorkflowDto[];
};

export type WorkflowResponseDto = {
  /**
   * Message describing the result of the operation
   *
   * @example  All workflow data found successfully
   */
  message: string;
  /**
   * The data returned by the operation
   *
   * @example {"summary":"Sample Workflow Response","value":{"moduleId":"65e3579de0ca70fe8f2e148e","version":1,"workflowOrder":[{"level":1,"role":"676435d455a50e076bedab81","limitFlag":true,"min":0,"max":100,"isSpecificDeptApprover":false,"includeOnRequesterCheck":true,"deedOfNovation":false,"byPassWorkflow":false,"code":"first-reviewer","name":"First Reviewer"}],"createdBy":"user123","updatedBy":"user456","status":true,"createdAt":"2024-03-02T16:45:17.346+00:00","updateAt":"2024-03-03T10:20:00.000+00:00"}}
   */
  data: WorkflowDto;
};

export type DeleteWorkflowResponseDto = {
  /**
   * Workflow has been successfully deleted
   *
   * @example Workflow has been successfully deleted.
   */
  message: string;
};
