/**
 * Generated by @openapi-codegen
 *
 * @version 1.0.0
 */
import * as reactQuery from "@tanstack/react-query";
import { useBackendContext, BackendContext } from "./backendContext";
import type * as Fetcher from "./backendFetcher";
import { backendFetch } from "./backendFetcher";
import type * as Schemas from "./backendSchemas";

export type CreateContractFormError = Fetcher.ErrorWrapper<undefined>;

export type CreateContractFormVariables = {
  body: Schemas.CreateFormDto;
} & BackendContext["fetcherOptions"];

export const fetchCreateContractForm = (
  variables: CreateContractFormVariables,
  signal?: AbortSignal,
) =>
  backendFetch<
    Schemas.CreateUpdateFormResponseDto,
    CreateContractFormError,
    Schemas.CreateFormDto,
    {},
    {},
    {}
  >({ url: "/forms/contract/create", method: "post", ...variables, signal });

export const useCreateContractForm = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      Schemas.CreateUpdateFormResponseDto,
      CreateContractFormError,
      CreateContractFormVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useBackendContext();
  return reactQuery.useMutation<
    Schemas.CreateUpdateFormResponseDto,
    CreateContractFormError,
    CreateContractFormVariables
  >({
    mutationFn: (variables: CreateContractFormVariables) =>
      fetchCreateContractForm({ ...fetcherOptions, ...variables }),
    ...options,
  });
};

export type CreateDraftContractFormError = Fetcher.ErrorWrapper<undefined>;

export type CreateDraftContractFormVariables = {
  body: Schemas.CreateDraftFormDto;
} & BackendContext["fetcherOptions"];

export const fetchCreateDraftContractForm = (
  variables: CreateDraftContractFormVariables,
  signal?: AbortSignal,
) =>
  backendFetch<
    Schemas.CreateDraftFormResponseDto,
    CreateDraftContractFormError,
    Schemas.CreateDraftFormDto,
    {},
    {},
    {}
  >({
    url: "/forms/draft/contract/create",
    method: "post",
    ...variables,
    signal,
  });

export const useCreateDraftContractForm = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      Schemas.CreateDraftFormResponseDto,
      CreateDraftContractFormError,
      CreateDraftContractFormVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useBackendContext();
  return reactQuery.useMutation<
    Schemas.CreateDraftFormResponseDto,
    CreateDraftContractFormError,
    CreateDraftContractFormVariables
  >({
    mutationFn: (variables: CreateDraftContractFormVariables) =>
      fetchCreateDraftContractForm({ ...fetcherOptions, ...variables }),
    ...options,
  });
};

export type GetFormListPathParams = {
  /**
   * email of the user
   *
   * @example mmurugesan@nrl.com.au
   */
  email: string;
};

export type GetFormListQueryParams = {
  /**
   * The type of the form myRequest, teamRequest approveRequest, myApprovedRequest and myEsignRequest
   *
   * @example myRequest
   */
  type: string;
  /**
   * Module ID associated with the form
   *
   * @example 65e3579de0ca70fe8f2e148e
   */
  moduleId: string;
};

export type GetFormListError = Fetcher.ErrorWrapper<undefined>;

export type GetFormListVariables = {
  pathParams: GetFormListPathParams;
  queryParams: GetFormListQueryParams;
} & BackendContext["fetcherOptions"];

export const fetchGetFormList = (
  variables: GetFormListVariables,
  signal?: AbortSignal,
) =>
  backendFetch<
    Schemas.ContractFormListResponseDto,
    GetFormListError,
    undefined,
    {},
    GetFormListQueryParams,
    GetFormListPathParams
  >({
    url: "/forms/contract/list/{email}",
    method: "get",
    ...variables,
    signal,
  });

export const useGetFormList = <TData = Schemas.ContractFormListResponseDto,>(
  variables: GetFormListVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      Schemas.ContractFormListResponseDto,
      GetFormListError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { fetcherOptions, queryOptions, queryKeyFn } =
    useBackendContext(options);
  return reactQuery.useQuery<
    Schemas.ContractFormListResponseDto,
    GetFormListError,
    TData
  >({
    queryKey: queryKeyFn({
      path: "/forms/contract/list/{email}",
      operationId: "getFormList",
      variables,
    }),
    queryFn: ({ signal }) =>
      fetchGetFormList({ ...fetcherOptions, ...variables }, signal),
    ...options,
    ...queryOptions,
  });
};

export type GetFormDetailPathParams = {
  /**
   * id of the form
   *
   * @example 675bc035952414810b9eab40
   */
  id: string;
};

export type GetFormDetailQueryParams = {
  /**
   * The type of the form myRequest, teamRequest approveRequest, myApprovedRequest and myEsignRequest
   *
   * @example myRequest
   */
  type: string;
  /**
   * Module ID associated with the form
   *
   * @example 65e3579de0ca70fe8f2e148e
   */
  moduleId: string;
  /**
   * email of the user
   *
   * @example mmurugesan@nrl.com.au
   */
  email: string;
};

export type GetFormDetailError = Fetcher.ErrorWrapper<undefined>;

export type GetFormDetailVariables = {
  pathParams: GetFormDetailPathParams;
  queryParams: GetFormDetailQueryParams;
} & BackendContext["fetcherOptions"];

export const fetchGetFormDetail = (
  variables: GetFormDetailVariables,
  signal?: AbortSignal,
) =>
  backendFetch<
    Schemas.GetFormDetailResponseDto,
    GetFormDetailError,
    undefined,
    {},
    GetFormDetailQueryParams,
    GetFormDetailPathParams
  >({
    url: "/forms/contract/detail/{id}",
    method: "get",
    ...variables,
    signal,
  });

export const useGetFormDetail = <TData = Schemas.GetFormDetailResponseDto,>(
  variables: GetFormDetailVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      Schemas.GetFormDetailResponseDto,
      GetFormDetailError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { fetcherOptions, queryOptions, queryKeyFn } =
    useBackendContext(options);
  return reactQuery.useQuery<
    Schemas.GetFormDetailResponseDto,
    GetFormDetailError,
    TData
  >({
    queryKey: queryKeyFn({
      path: "/forms/contract/detail/{id}",
      operationId: "getFormDetail",
      variables,
    }),
    queryFn: ({ signal }) =>
      fetchGetFormDetail({ ...fetcherOptions, ...variables }, signal),
    ...options,
    ...queryOptions,
  });
};

export type UpdateContractFormError = Fetcher.ErrorWrapper<undefined>;

export type UpdateContractFormVariables = {
  body: Schemas.UpdateFormDetailsDto;
} & BackendContext["fetcherOptions"];

export const fetchUpdateContractForm = (
  variables: UpdateContractFormVariables,
  signal?: AbortSignal,
) =>
  backendFetch<
    Schemas.CreateUpdateFormResponseDto,
    UpdateContractFormError,
    Schemas.UpdateFormDetailsDto,
    {},
    {},
    {}
  >({ url: "/forms/contract/resubmit", method: "put", ...variables, signal });

export const useUpdateContractForm = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      Schemas.CreateUpdateFormResponseDto,
      UpdateContractFormError,
      UpdateContractFormVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useBackendContext();
  return reactQuery.useMutation<
    Schemas.CreateUpdateFormResponseDto,
    UpdateContractFormError,
    UpdateContractFormVariables
  >({
    mutationFn: (variables: UpdateContractFormVariables) =>
      fetchUpdateContractForm({ ...fetcherOptions, ...variables }),
    ...options,
  });
};

export type GetFormHistoryPathParams = {
  /**
   * id of the form
   *
   * @example 675bc035952414810b9eab40
   */
  id: string;
};

export type GetFormHistoryError = Fetcher.ErrorWrapper<undefined>;

export type GetFormHistoryVariables = {
  pathParams: GetFormHistoryPathParams;
} & BackendContext["fetcherOptions"];

export const fetchGetFormHistory = (
  variables: GetFormHistoryVariables,
  signal?: AbortSignal,
) =>
  backendFetch<
    Schemas.FormHistroyResponseDto,
    GetFormHistoryError,
    undefined,
    {},
    {},
    GetFormHistoryPathParams
  >({
    url: "/forms/contract/history/{id}",
    method: "get",
    ...variables,
    signal,
  });

export const useGetFormHistory = <TData = Schemas.FormHistroyResponseDto,>(
  variables: GetFormHistoryVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      Schemas.FormHistroyResponseDto,
      GetFormHistoryError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { fetcherOptions, queryOptions, queryKeyFn } =
    useBackendContext(options);
  return reactQuery.useQuery<
    Schemas.FormHistroyResponseDto,
    GetFormHistoryError,
    TData
  >({
    queryKey: queryKeyFn({
      path: "/forms/contract/history/{id}",
      operationId: "getFormHistory",
      variables,
    }),
    queryFn: ({ signal }) =>
      fetchGetFormHistory({ ...fetcherOptions, ...variables }, signal),
    ...options,
    ...queryOptions,
  });
};

export type GetFilterMetaQueryParams = {
  /**
   * Email ID of the user
   *
   * @example user@example.com
   */
  emailId: string;
  /**
   * Type of the item
   *
   * @example myRequest
   */
  type: string;
  /**
   * Module ID associated with the item
   *
   * @example 65e3579de0ca70fe8f2e148e
   */
  moduleId: string;
};

export type GetFilterMetaError = Fetcher.ErrorWrapper<undefined>;

export type GetFilterMetaVariables = {
  queryParams: GetFilterMetaQueryParams;
} & BackendContext["fetcherOptions"];

export const fetchGetFilterMeta = (
  variables: GetFilterMetaVariables,
  signal?: AbortSignal,
) =>
  backendFetch<
    Schemas.FilterMetaResponseDto,
    GetFilterMetaError,
    undefined,
    {},
    GetFilterMetaQueryParams,
    {}
  >({ url: "/forms/filter/meta", method: "get", ...variables, signal });

export const useGetFilterMeta = <TData = Schemas.FilterMetaResponseDto,>(
  variables: GetFilterMetaVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      Schemas.FilterMetaResponseDto,
      GetFilterMetaError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { fetcherOptions, queryOptions, queryKeyFn } =
    useBackendContext(options);
  return reactQuery.useQuery<
    Schemas.FilterMetaResponseDto,
    GetFilterMetaError,
    TData
  >({
    queryKey: queryKeyFn({
      path: "/forms/filter/meta",
      operationId: "getFilterMeta",
      variables,
    }),
    queryFn: ({ signal }) =>
      fetchGetFilterMeta({ ...fetcherOptions, ...variables }, signal),
    ...options,
    ...queryOptions,
  });
};

export type ResetFormStatusPathParams = {
  /**
   * id of the form
   *
   * @example 65e3579de0ca70fe8f2e148e
   */
  id: string;
};

export type ResetFormStatusQueryParams = {
  /**
   * ID of the module
   *
   * @example 64e4567de12a6f23b6548c92
   */
  moduleId: string;
  /**
   * Email ID of the user approving or updating the form
   *
   * @example user@example.com
   */
  emailId: string;
  /**
   * type of request
   *
   * @example myRequest
   */
  type: string;
};

export type ResetFormStatusError = Fetcher.ErrorWrapper<undefined>;

export type ResetFormStatusVariables = {
  pathParams: ResetFormStatusPathParams;
  queryParams: ResetFormStatusQueryParams;
} & BackendContext["fetcherOptions"];

export const fetchResetFormStatus = (
  variables: ResetFormStatusVariables,
  signal?: AbortSignal,
) =>
  backendFetch<
    Schemas.ResetResponseDto,
    ResetFormStatusError,
    undefined,
    {},
    ResetFormStatusQueryParams,
    ResetFormStatusPathParams
  >({
    url: "/forms/contract/reset/{id}",
    method: "post",
    ...variables,
    signal,
  });

export const useResetFormStatus = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      Schemas.ResetResponseDto,
      ResetFormStatusError,
      ResetFormStatusVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useBackendContext();
  return reactQuery.useMutation<
    Schemas.ResetResponseDto,
    ResetFormStatusError,
    ResetFormStatusVariables
  >({
    mutationFn: (variables: ResetFormStatusVariables) =>
      fetchResetFormStatus({ ...fetcherOptions, ...variables }),
    ...options,
  });
};

export type DeleteFormByIdPathParams = {
  /**
   * id of the form
   *
   * @example 65e3579de0ca70fe8f2e148e
   */
  id: string;
};

export type DeleteFormByIdQueryParams = {
  /**
   * ID of the module
   *
   * @example 64e4567de12a6f23b6548c92
   */
  moduleId: string;
  /**
   * comments for deleting the form
   *
   * @example The monetory value is not reasonable
   */
  comments: string;
};

export type DeleteFormByIdError = Fetcher.ErrorWrapper<undefined>;

export type DeleteFormByIdVariables = {
  pathParams: DeleteFormByIdPathParams;
  queryParams: DeleteFormByIdQueryParams;
} & BackendContext["fetcherOptions"];

export const fetchDeleteFormById = (
  variables: DeleteFormByIdVariables,
  signal?: AbortSignal,
) =>
  backendFetch<
    Schemas.DeleteResponseDto,
    DeleteFormByIdError,
    undefined,
    {},
    DeleteFormByIdQueryParams,
    DeleteFormByIdPathParams
  >({ url: "/forms/contract/{id}", method: "delete", ...variables, signal });

export const useDeleteFormById = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      Schemas.DeleteResponseDto,
      DeleteFormByIdError,
      DeleteFormByIdVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useBackendContext();
  return reactQuery.useMutation<
    Schemas.DeleteResponseDto,
    DeleteFormByIdError,
    DeleteFormByIdVariables
  >({
    mutationFn: (variables: DeleteFormByIdVariables) =>
      fetchDeleteFormById({ ...fetcherOptions, ...variables }),
    ...options,
  });
};

export type RecallFormByIdPathParams = {
  /**
   * id of the form
   *
   * @example 65e3579de0ca70fe8f2e148e
   */
  id: string;
};

export type RecallFormByIdQueryParams = {
  /**
   * ID of the module
   *
   * @example 64e4567de12a6f23b6548c92
   */
  moduleId: string;
  /**
   * comments for recalling the function
   *
   * @example The monetory value is not adequate
   */
  comments: string;
  /**
   * email of the user who is recalling the form
   *
   * @example vrameshbapu@nrl.com.au
   */
  emailId: string;
};

export type RecallFormByIdError = Fetcher.ErrorWrapper<undefined>;

export type RecallFormByIdVariables = {
  pathParams: RecallFormByIdPathParams;
  queryParams: RecallFormByIdQueryParams;
} & BackendContext["fetcherOptions"];

export const fetchRecallFormById = (
  variables: RecallFormByIdVariables,
  signal?: AbortSignal,
) =>
  backendFetch<
    Schemas.RecallResponseDto,
    RecallFormByIdError,
    undefined,
    {},
    RecallFormByIdQueryParams,
    RecallFormByIdPathParams
  >({
    url: "/forms/contract/recall/{id}",
    method: "post",
    ...variables,
    signal,
  });

export const useRecallFormById = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      Schemas.RecallResponseDto,
      RecallFormByIdError,
      RecallFormByIdVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useBackendContext();
  return reactQuery.useMutation<
    Schemas.RecallResponseDto,
    RecallFormByIdError,
    RecallFormByIdVariables
  >({
    mutationFn: (variables: RecallFormByIdVariables) =>
      fetchRecallFormById({ ...fetcherOptions, ...variables }),
    ...options,
  });
};

export type GetGMUserQueryParams = {
  /**
   * ID of the module
   *
   * @example 64e4567de12a6f23b6548c92
   */
  moduleId: string;
  /**
   * email of the user
   *
   * @example vrameshbapu@nrl.com.au
   */
  email: string;
  /**
   * id of the department
   *
   * @example 65e3579de0ca70fe8f2e148e
   */
  deptId: string;
};

export type GetGMUserError = Fetcher.ErrorWrapper<undefined>;

export type GetGMUserVariables = {
  queryParams: GetGMUserQueryParams;
} & BackendContext["fetcherOptions"];

export const fetchGetGMUser = (
  variables: GetGMUserVariables,
  signal?: AbortSignal,
) =>
  backendFetch<
    Schemas.GMDetailsResponseDto,
    GetGMUserError,
    undefined,
    {},
    GetGMUserQueryParams,
    {}
  >({ url: "/forms/gmUser/check", method: "get", ...variables, signal });

export const useGetGMUser = <TData = Schemas.GMDetailsResponseDto,>(
  variables: GetGMUserVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      Schemas.GMDetailsResponseDto,
      GetGMUserError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { fetcherOptions, queryOptions, queryKeyFn } =
    useBackendContext(options);
  return reactQuery.useQuery<
    Schemas.GMDetailsResponseDto,
    GetGMUserError,
    TData
  >({
    queryKey: queryKeyFn({
      path: "/forms/gmUser/check",
      operationId: "getGMUser",
      variables,
    }),
    queryFn: ({ signal }) =>
      fetchGetGMUser({ ...fetcherOptions, ...variables }, signal),
    ...options,
    ...queryOptions,
  });
};

export type FixMonetaryValueError = Fetcher.ErrorWrapper<undefined>;

export type FixMonetaryValueVariables = BackendContext["fetcherOptions"];

export const fetchFixMonetaryValue = (
  variables: FixMonetaryValueVariables,
  signal?: AbortSignal,
) =>
  backendFetch<undefined, FixMonetaryValueError, undefined, {}, {}, {}>({
    url: "/forms/monetary-value",
    method: "get",
    ...variables,
    signal,
  });

export const useFixMonetaryValue = <TData = undefined,>(
  variables: FixMonetaryValueVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<undefined, FixMonetaryValueError, TData>,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { fetcherOptions, queryOptions, queryKeyFn } =
    useBackendContext(options);
  return reactQuery.useQuery<undefined, FixMonetaryValueError, TData>({
    queryKey: queryKeyFn({
      path: "/forms/monetary-value",
      operationId: "fixMonetaryValue",
      variables,
    }),
    queryFn: ({ signal }) =>
      fetchFixMonetaryValue({ ...fetcherOptions, ...variables }, signal),
    ...options,
    ...queryOptions,
  });
};

export type CreateHeadcountError = Fetcher.ErrorWrapper<undefined>;

export type CreateHeadcountVariables = {
  body: Schemas.CreateHeadcountFormDto;
} & BackendContext["fetcherOptions"];

export const fetchCreateHeadcount = (
  variables: CreateHeadcountVariables,
  signal?: AbortSignal,
) =>
  backendFetch<
    Schemas.CreateHeadCountResponseDto,
    CreateHeadcountError,
    Schemas.CreateHeadcountFormDto,
    {},
    {},
    {}
  >({ url: "/forms/headcount/create", method: "post", ...variables, signal });

export const useCreateHeadcount = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      Schemas.CreateHeadCountResponseDto,
      CreateHeadcountError,
      CreateHeadcountVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useBackendContext();
  return reactQuery.useMutation<
    Schemas.CreateHeadCountResponseDto,
    CreateHeadcountError,
    CreateHeadcountVariables
  >({
    mutationFn: (variables: CreateHeadcountVariables) =>
      fetchCreateHeadcount({ ...fetcherOptions, ...variables }),
    ...options,
  });
};

export type GetHeadcountFormListPathParams = {
  /**
   * email of the user
   *
   * @example mmurugesan@nrl.com.au
   */
  email: string;
};

export type GetHeadcountFormListQueryParams = {
  /**
   * The type of the form myRequest, teamRequest and approveRequest
   *
   * @example myRequest
   */
  type: string;
  /**
   * Module ID associated with the form
   *
   * @example 65e3579de0ca70fe8f2e148e
   */
  moduleId: string;
};

export type GetHeadcountFormListError = Fetcher.ErrorWrapper<undefined>;

export type GetHeadcountFormListVariables = {
  pathParams: GetHeadcountFormListPathParams;
  queryParams: GetHeadcountFormListQueryParams;
} & BackendContext["fetcherOptions"];

export const fetchGetHeadcountFormList = (
  variables: GetHeadcountFormListVariables,
  signal?: AbortSignal,
) =>
  backendFetch<
    Schemas.HeadcountFormListResponseDto,
    GetHeadcountFormListError,
    undefined,
    {},
    GetHeadcountFormListQueryParams,
    GetHeadcountFormListPathParams
  >({
    url: "/forms/headcount/list/{email}",
    method: "get",
    ...variables,
    signal,
  });

export const useGetHeadcountFormList = <
  TData = Schemas.HeadcountFormListResponseDto,
>(
  variables: GetHeadcountFormListVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      Schemas.HeadcountFormListResponseDto,
      GetHeadcountFormListError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { fetcherOptions, queryOptions, queryKeyFn } =
    useBackendContext(options);
  return reactQuery.useQuery<
    Schemas.HeadcountFormListResponseDto,
    GetHeadcountFormListError,
    TData
  >({
    queryKey: queryKeyFn({
      path: "/forms/headcount/list/{email}",
      operationId: "getHeadcountFormList",
      variables,
    }),
    queryFn: ({ signal }) =>
      fetchGetHeadcountFormList({ ...fetcherOptions, ...variables }, signal),
    ...options,
    ...queryOptions,
  });
};

export type GetHeadcountFormDetailPathParams = {
  /**
   * id of the form
   *
   * @example 675bc035952414810b9eab40
   */
  id: string;
};

export type GetHeadcountFormDetailQueryParams = {
  /**
   * The type of the form myRequest, teamRequest and approveRequest
   *
   * @example myRequest
   */
  type: string;
  /**
   * Module ID associated with the form
   *
   * @example 65e3579de0ca70fe8f2e148e
   */
  moduleId: string;
  /**
   * email of the user
   *
   * @example mmurugesan@nrl.com.au
   */
  email: string;
};

export type GetHeadcountFormDetailError = Fetcher.ErrorWrapper<undefined>;

export type GetHeadcountFormDetailVariables = {
  pathParams: GetHeadcountFormDetailPathParams;
  queryParams: GetHeadcountFormDetailQueryParams;
} & BackendContext["fetcherOptions"];

export const fetchGetHeadcountFormDetail = (
  variables: GetHeadcountFormDetailVariables,
  signal?: AbortSignal,
) =>
  backendFetch<
    Schemas.GetHeadcountFormDetailResponseDto,
    GetHeadcountFormDetailError,
    undefined,
    {},
    GetHeadcountFormDetailQueryParams,
    GetHeadcountFormDetailPathParams
  >({
    url: "/forms/headcount/detail/{id}",
    method: "get",
    ...variables,
    signal,
  });

export const useGetHeadcountFormDetail = <
  TData = Schemas.GetHeadcountFormDetailResponseDto,
>(
  variables: GetHeadcountFormDetailVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      Schemas.GetHeadcountFormDetailResponseDto,
      GetHeadcountFormDetailError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { fetcherOptions, queryOptions, queryKeyFn } =
    useBackendContext(options);
  return reactQuery.useQuery<
    Schemas.GetHeadcountFormDetailResponseDto,
    GetHeadcountFormDetailError,
    TData
  >({
    queryKey: queryKeyFn({
      path: "/forms/headcount/detail/{id}",
      operationId: "getHeadcountFormDetail",
      variables,
    }),
    queryFn: ({ signal }) =>
      fetchGetHeadcountFormDetail({ ...fetcherOptions, ...variables }, signal),
    ...options,
    ...queryOptions,
  });
};

export type UpdateHeadCountError = Fetcher.ErrorWrapper<undefined>;

export type UpdateHeadCountVariables = {
  body: Schemas.UpdateFormDetailsDto;
} & BackendContext["fetcherOptions"];

export const fetchUpdateHeadCount = (
  variables: UpdateHeadCountVariables,
  signal?: AbortSignal,
) =>
  backendFetch<
    Schemas.UpdateHeadCountResponseDto,
    UpdateHeadCountError,
    Schemas.UpdateFormDetailsDto,
    {},
    {},
    {}
  >({ url: "/forms/headcount/resubmit", method: "post", ...variables, signal });

export const useUpdateHeadCount = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      Schemas.UpdateHeadCountResponseDto,
      UpdateHeadCountError,
      UpdateHeadCountVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useBackendContext();
  return reactQuery.useMutation<
    Schemas.UpdateHeadCountResponseDto,
    UpdateHeadCountError,
    UpdateHeadCountVariables
  >({
    mutationFn: (variables: UpdateHeadCountVariables) =>
      fetchUpdateHeadCount({ ...fetcherOptions, ...variables }),
    ...options,
  });
};

export type ExportCsvFormDetailsError = Fetcher.ErrorWrapper<undefined>;

export type ExportCsvFormDetailsVariables = BackendContext["fetcherOptions"];

export const fetchExportCsvFormDetails = (
  variables: ExportCsvFormDetailsVariables,
  signal?: AbortSignal,
) =>
  backendFetch<undefined, ExportCsvFormDetailsError, undefined, {}, {}, {}>({
    url: "/forms/export/csv",
    method: "get",
    ...variables,
    signal,
  });

export const useExportCsvFormDetails = <TData = undefined,>(
  variables: ExportCsvFormDetailsVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<undefined, ExportCsvFormDetailsError, TData>,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { fetcherOptions, queryOptions, queryKeyFn } =
    useBackendContext(options);
  return reactQuery.useQuery<undefined, ExportCsvFormDetailsError, TData>({
    queryKey: queryKeyFn({
      path: "/forms/export/csv",
      operationId: "exportCsvFormDetails",
      variables,
    }),
    queryFn: ({ signal }) =>
      fetchExportCsvFormDetails({ ...fetcherOptions, ...variables }, signal),
    ...options,
    ...queryOptions,
  });
};

export type CreateFormModuleError = Fetcher.ErrorWrapper<undefined>;

export type CreateFormModuleVariables = {
  body: Schemas.CreateFormModuleDto;
} & BackendContext["fetcherOptions"];

export const fetchCreateFormModule = (
  variables: CreateFormModuleVariables,
  signal?: AbortSignal,
) =>
  backendFetch<
    Schemas.CreateUpdateModuleResponseDto,
    CreateFormModuleError,
    Schemas.CreateFormModuleDto,
    {},
    {},
    {}
  >({ url: "/form-module", method: "post", ...variables, signal });

export const useCreateFormModule = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      Schemas.CreateUpdateModuleResponseDto,
      CreateFormModuleError,
      CreateFormModuleVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useBackendContext();
  return reactQuery.useMutation<
    Schemas.CreateUpdateModuleResponseDto,
    CreateFormModuleError,
    CreateFormModuleVariables
  >({
    mutationFn: (variables: CreateFormModuleVariables) =>
      fetchCreateFormModule({ ...fetcherOptions, ...variables }),
    ...options,
  });
};

export type GetAdminFormModulesQueryParams = {
  /**
   * Id of the Module
   *
   * @example 65e3579de0ca70fe8f2e148e
   */
  menuModuleId: string;
  /**
   * Email address of the user
   *
   * @example balak@nrl.com.au
   */
  email: string;
};

export type GetAdminFormModulesError = Fetcher.ErrorWrapper<undefined>;

export type GetAdminFormModulesVariables = {
  queryParams: GetAdminFormModulesQueryParams;
} & BackendContext["fetcherOptions"];

export const fetchGetAdminFormModules = (
  variables: GetAdminFormModulesVariables,
  signal?: AbortSignal,
) =>
  backendFetch<
    Schemas.GetAllFormModuleResponseDto,
    GetAdminFormModulesError,
    undefined,
    {},
    GetAdminFormModulesQueryParams,
    {}
  >({ url: "/form-module/list", method: "get", ...variables, signal });

export const useGetAdminFormModules = <
  TData = Schemas.GetAllFormModuleResponseDto,
>(
  variables: GetAdminFormModulesVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      Schemas.GetAllFormModuleResponseDto,
      GetAdminFormModulesError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { fetcherOptions, queryOptions, queryKeyFn } =
    useBackendContext(options);
  return reactQuery.useQuery<
    Schemas.GetAllFormModuleResponseDto,
    GetAdminFormModulesError,
    TData
  >({
    queryKey: queryKeyFn({
      path: "/form-module/list",
      operationId: "getAdminFormModules",
      variables,
    }),
    queryFn: ({ signal }) =>
      fetchGetAdminFormModules({ ...fetcherOptions, ...variables }, signal),
    ...options,
    ...queryOptions,
  });
};

export type GetFormModuleByIdPathParams = {
  /**
   * id of the module
   *
   * @example 65e3579de0ca70fe8f2e148e
   */
  id: string;
};

export type GetFormModuleByIdQueryParams = {
  /**
   * Id of the Module
   *
   * @example 65e3579de0ca70fe8f2e148e
   */
  menuModuleId: string;
  /**
   * Email address of the user
   *
   * @example balak@nrl.com.au
   */
  email: string;
};

export type GetFormModuleByIdError = Fetcher.ErrorWrapper<undefined>;

export type GetFormModuleByIdVariables = {
  pathParams: GetFormModuleByIdPathParams;
  queryParams: GetFormModuleByIdQueryParams;
} & BackendContext["fetcherOptions"];

export const fetchGetFormModuleById = (
  variables: GetFormModuleByIdVariables,
  signal?: AbortSignal,
) =>
  backendFetch<
    Schemas.GetModuleByIdResponseDto,
    GetFormModuleByIdError,
    undefined,
    {},
    GetFormModuleByIdQueryParams,
    GetFormModuleByIdPathParams
  >({ url: "/form-module/detail/{id}", method: "get", ...variables, signal });

export const useGetFormModuleById = <TData = Schemas.GetModuleByIdResponseDto,>(
  variables: GetFormModuleByIdVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      Schemas.GetModuleByIdResponseDto,
      GetFormModuleByIdError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { fetcherOptions, queryOptions, queryKeyFn } =
    useBackendContext(options);
  return reactQuery.useQuery<
    Schemas.GetModuleByIdResponseDto,
    GetFormModuleByIdError,
    TData
  >({
    queryKey: queryKeyFn({
      path: "/form-module/detail/{id}",
      operationId: "getFormModuleById",
      variables,
    }),
    queryFn: ({ signal }) =>
      fetchGetFormModuleById({ ...fetcherOptions, ...variables }, signal),
    ...options,
    ...queryOptions,
  });
};

export type UpdateFormModulePathParams = {
  /**
   * id of the module
   *
   * @example 65e3579de0ca70fe8f2e148e
   */
  id: string;
};

export type UpdateFormModuleError = Fetcher.ErrorWrapper<undefined>;

export type UpdateFormModuleVariables = {
  body: Schemas.CreateFormModuleDto;
  pathParams: UpdateFormModulePathParams;
} & BackendContext["fetcherOptions"];

export const fetchUpdateFormModule = (
  variables: UpdateFormModuleVariables,
  signal?: AbortSignal,
) =>
  backendFetch<
    Schemas.UpdateFormModuleResponseDto,
    UpdateFormModuleError,
    Schemas.CreateFormModuleDto,
    {},
    {},
    UpdateFormModulePathParams
  >({ url: "/form-module/{id}", method: "put", ...variables, signal });

export const useUpdateFormModule = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      Schemas.UpdateFormModuleResponseDto,
      UpdateFormModuleError,
      UpdateFormModuleVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useBackendContext();
  return reactQuery.useMutation<
    Schemas.UpdateFormModuleResponseDto,
    UpdateFormModuleError,
    UpdateFormModuleVariables
  >({
    mutationFn: (variables: UpdateFormModuleVariables) =>
      fetchUpdateFormModule({ ...fetcherOptions, ...variables }),
    ...options,
  });
};

export type DeleteFormModuleByIdPathParams = {
  /**
   * id of the module
   *
   * @example 65e3579de0ca70fe8f2e148e
   */
  id: string;
};

export type DeleteFormModuleByIdError = Fetcher.ErrorWrapper<undefined>;

export type DeleteFormModuleByIdVariables = {
  pathParams: DeleteFormModuleByIdPathParams;
} & BackendContext["fetcherOptions"];

export const fetchDeleteFormModuleById = (
  variables: DeleteFormModuleByIdVariables,
  signal?: AbortSignal,
) =>
  backendFetch<
    Schemas.CreateUpdateModuleResponseDto,
    DeleteFormModuleByIdError,
    undefined,
    {},
    {},
    DeleteFormModuleByIdPathParams
  >({ url: "/form-module/{id}", method: "delete", ...variables, signal });

export const useDeleteFormModuleById = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      Schemas.CreateUpdateModuleResponseDto,
      DeleteFormModuleByIdError,
      DeleteFormModuleByIdVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useBackendContext();
  return reactQuery.useMutation<
    Schemas.CreateUpdateModuleResponseDto,
    DeleteFormModuleByIdError,
    DeleteFormModuleByIdVariables
  >({
    mutationFn: (variables: DeleteFormModuleByIdVariables) =>
      fetchDeleteFormModuleById({ ...fetcherOptions, ...variables }),
    ...options,
  });
};

export type GetFormModulesError = Fetcher.ErrorWrapper<undefined>;

export type GetFormModulesVariables = BackendContext["fetcherOptions"];

export const fetchGetFormModules = (
  variables: GetFormModulesVariables,
  signal?: AbortSignal,
) =>
  backendFetch<
    Schemas.GetAllModulesResponseDto,
    GetFormModulesError,
    undefined,
    {},
    {},
    {}
  >({ url: "/form-module/dropdown", method: "get", ...variables, signal });

export const useGetFormModules = <TData = Schemas.GetAllModulesResponseDto,>(
  variables: GetFormModulesVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      Schemas.GetAllModulesResponseDto,
      GetFormModulesError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { fetcherOptions, queryOptions, queryKeyFn } =
    useBackendContext(options);
  return reactQuery.useQuery<
    Schemas.GetAllModulesResponseDto,
    GetFormModulesError,
    TData
  >({
    queryKey: queryKeyFn({
      path: "/form-module/dropdown",
      operationId: "getFormModules",
      variables,
    }),
    queryFn: ({ signal }) =>
      fetchGetFormModules({ ...fetcherOptions, ...variables }, signal),
    ...options,
    ...queryOptions,
  });
};

export type CreateAprrovalFormError = Fetcher.ErrorWrapper<undefined>;

export type CreateAprrovalFormVariables = {
  body: Schemas.UpdateFormApprovalDto;
} & BackendContext["fetcherOptions"];

export const fetchCreateAprrovalForm = (
  variables: CreateAprrovalFormVariables,
  signal?: AbortSignal,
) =>
  backendFetch<
    Schemas.FormApprovalMessageDto,
    CreateAprrovalFormError,
    Schemas.UpdateFormApprovalDto,
    {},
    {},
    {}
  >({ url: "/form-approval/contract", method: "post", ...variables, signal });

export const useCreateAprrovalForm = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      Schemas.FormApprovalMessageDto,
      CreateAprrovalFormError,
      CreateAprrovalFormVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useBackendContext();
  return reactQuery.useMutation<
    Schemas.FormApprovalMessageDto,
    CreateAprrovalFormError,
    CreateAprrovalFormVariables
  >({
    mutationFn: (variables: CreateAprrovalFormVariables) =>
      fetchCreateAprrovalForm({ ...fetcherOptions, ...variables }),
    ...options,
  });
};

export type HandleCallBackError = Fetcher.ErrorWrapper<undefined>;

export type HandleCallBackVariables = {
  body: Schemas.EnvelopeDetailsDto;
} & BackendContext["fetcherOptions"];

export const fetchHandleCallBack = (
  variables: HandleCallBackVariables,
  signal?: AbortSignal,
) =>
  backendFetch<
    Schemas.CallbackMessageDto,
    HandleCallBackError,
    Schemas.EnvelopeDetailsDto,
    {},
    {},
    {}
  >({ url: "/form-approval/callback", method: "post", ...variables, signal });

export const useHandleCallBack = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      Schemas.CallbackMessageDto,
      HandleCallBackError,
      HandleCallBackVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useBackendContext();
  return reactQuery.useMutation<
    Schemas.CallbackMessageDto,
    HandleCallBackError,
    HandleCallBackVariables
  >({
    mutationFn: (variables: HandleCallBackVariables) =>
      fetchHandleCallBack({ ...fetcherOptions, ...variables }),
    ...options,
  });
};

export type DocusignRetriggerPathParams = {
  /**
   * id of the form
   *
   * @example 65e3579de0ca70fe8f2e148e
   */
  id: string;
};

export type DocusignRetriggerQueryParams = {
  /**
   * ID of the module
   *
   * @example 64e4567de12a6f23b6548c92
   */
  moduleId: string;
  /**
   * Email ID of the user approving or updating the form
   *
   * @example user@example.com
   */
  emailId: string;
  /**
   * The type of the form myRequest, teamRequest ,approveRequest, myApprovedRequest and myEsignRequest
   *
   * @example myRequest
   */
  type: string;
};

export type DocusignRetriggerError = Fetcher.ErrorWrapper<undefined>;

export type DocusignRetriggerVariables = {
  pathParams: DocusignRetriggerPathParams;
  queryParams: DocusignRetriggerQueryParams;
} & BackendContext["fetcherOptions"];

export const fetchDocusignRetrigger = (
  variables: DocusignRetriggerVariables,
  signal?: AbortSignal,
) =>
  backendFetch<
    Schemas.RetriggerResponseDto,
    DocusignRetriggerError,
    undefined,
    {},
    DocusignRetriggerQueryParams,
    DocusignRetriggerPathParams
  >({
    url: "/form-approval/docusignRetrigger/{id}",
    method: "post",
    ...variables,
    signal,
  });

export const useDocusignRetrigger = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      Schemas.RetriggerResponseDto,
      DocusignRetriggerError,
      DocusignRetriggerVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useBackendContext();
  return reactQuery.useMutation<
    Schemas.RetriggerResponseDto,
    DocusignRetriggerError,
    DocusignRetriggerVariables
  >({
    mutationFn: (variables: DocusignRetriggerVariables) =>
      fetchDocusignRetrigger({ ...fetcherOptions, ...variables }),
    ...options,
  });
};

export type HeadcountFormApprovalError = Fetcher.ErrorWrapper<undefined>;

export type HeadcountFormApprovalVariables = {
  body: Schemas.UpdateFormApprovalDto;
} & BackendContext["fetcherOptions"];

export const fetchHeadcountFormApproval = (
  variables: HeadcountFormApprovalVariables,
  signal?: AbortSignal,
) =>
  backendFetch<
    Schemas.FormMessageDto,
    HeadcountFormApprovalError,
    Schemas.UpdateFormApprovalDto,
    {},
    {},
    {}
  >({ url: "/form-approval/headcount", method: "post", ...variables, signal });

export const useHeadcountFormApproval = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      Schemas.FormMessageDto,
      HeadcountFormApprovalError,
      HeadcountFormApprovalVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useBackendContext();
  return reactQuery.useMutation<
    Schemas.FormMessageDto,
    HeadcountFormApprovalError,
    HeadcountFormApprovalVariables
  >({
    mutationFn: (variables: HeadcountFormApprovalVariables) =>
      fetchHeadcountFormApproval({ ...fetcherOptions, ...variables }),
    ...options,
  });
};

export type CreateDepartmentError = Fetcher.ErrorWrapper<undefined>;

export type CreateDepartmentVariables = {
  body: Schemas.CreateDepartmentsDto;
} & BackendContext["fetcherOptions"];

export const fetchCreateDepartment = (
  variables: CreateDepartmentVariables,
  signal?: AbortSignal,
) =>
  backendFetch<
    Schemas.CreateUpdateDepartmentResponseDto,
    CreateDepartmentError,
    Schemas.CreateDepartmentsDto,
    {},
    {},
    {}
  >({ url: "/departments", method: "post", ...variables, signal });

export const useCreateDepartment = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      Schemas.CreateUpdateDepartmentResponseDto,
      CreateDepartmentError,
      CreateDepartmentVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useBackendContext();
  return reactQuery.useMutation<
    Schemas.CreateUpdateDepartmentResponseDto,
    CreateDepartmentError,
    CreateDepartmentVariables
  >({
    mutationFn: (variables: CreateDepartmentVariables) =>
      fetchCreateDepartment({ ...fetcherOptions, ...variables }),
    ...options,
  });
};

export type GetAllDepartmentsAdminQueryParams = {
  /**
   * Id of the Module
   *
   * @example 65e3579de0ca70fe8f2e148e
   */
  menuModuleId: string;
  /**
   * Email address of the user
   *
   * @example balak@nrl.com.au
   */
  email: string;
};

export type GetAllDepartmentsAdminError = Fetcher.ErrorWrapper<undefined>;

export type GetAllDepartmentsAdminVariables = {
  queryParams: GetAllDepartmentsAdminQueryParams;
} & BackendContext["fetcherOptions"];

export const fetchGetAllDepartmentsAdmin = (
  variables: GetAllDepartmentsAdminVariables,
  signal?: AbortSignal,
) =>
  backendFetch<
    Schemas.GetAllPerissionsAdminResponseDto,
    GetAllDepartmentsAdminError,
    undefined,
    {},
    GetAllDepartmentsAdminQueryParams,
    {}
  >({ url: "/departments/list", method: "get", ...variables, signal });

export const useGetAllDepartmentsAdmin = <
  TData = Schemas.GetAllPerissionsAdminResponseDto,
>(
  variables: GetAllDepartmentsAdminVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      Schemas.GetAllPerissionsAdminResponseDto,
      GetAllDepartmentsAdminError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { fetcherOptions, queryOptions, queryKeyFn } =
    useBackendContext(options);
  return reactQuery.useQuery<
    Schemas.GetAllPerissionsAdminResponseDto,
    GetAllDepartmentsAdminError,
    TData
  >({
    queryKey: queryKeyFn({
      path: "/departments/list",
      operationId: "getAllDepartmentsAdmin",
      variables,
    }),
    queryFn: ({ signal }) =>
      fetchGetAllDepartmentsAdmin({ ...fetcherOptions, ...variables }, signal),
    ...options,
    ...queryOptions,
  });
};

export type GetDepartmentByIdPathParams = {
  /**
   * id of the department
   *
   * @example 65e3579de0ca70fe8f2e148e
   */
  id: string;
};

export type GetDepartmentByIdQueryParams = {
  /**
   * Id of the Module
   *
   * @example 65e3579de0ca70fe8f2e148e
   */
  menuModuleId: string;
  /**
   * Email address of the user
   *
   * @example balak@nrl.com.au
   */
  email: string;
};

export type GetDepartmentByIdError = Fetcher.ErrorWrapper<undefined>;

export type GetDepartmentByIdVariables = {
  pathParams: GetDepartmentByIdPathParams;
  queryParams: GetDepartmentByIdQueryParams;
} & BackendContext["fetcherOptions"];

export const fetchGetDepartmentById = (
  variables: GetDepartmentByIdVariables,
  signal?: AbortSignal,
) =>
  backendFetch<
    Schemas.GetDepartmentByIdResponseDto,
    GetDepartmentByIdError,
    undefined,
    {},
    GetDepartmentByIdQueryParams,
    GetDepartmentByIdPathParams
  >({ url: "/departments/detail/{id}", method: "get", ...variables, signal });

export const useGetDepartmentById = <
  TData = Schemas.GetDepartmentByIdResponseDto,
>(
  variables: GetDepartmentByIdVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      Schemas.GetDepartmentByIdResponseDto,
      GetDepartmentByIdError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { fetcherOptions, queryOptions, queryKeyFn } =
    useBackendContext(options);
  return reactQuery.useQuery<
    Schemas.GetDepartmentByIdResponseDto,
    GetDepartmentByIdError,
    TData
  >({
    queryKey: queryKeyFn({
      path: "/departments/detail/{id}",
      operationId: "getDepartmentById",
      variables,
    }),
    queryFn: ({ signal }) =>
      fetchGetDepartmentById({ ...fetcherOptions, ...variables }, signal),
    ...options,
    ...queryOptions,
  });
};

export type UpdateDepartmentPathParams = {
  /**
   * id of the department
   *
   * @example 65e3579de0ca70fe8f2e148e
   */
  id: string;
};

export type UpdateDepartmentError = Fetcher.ErrorWrapper<undefined>;

export type UpdateDepartmentVariables = {
  body: Schemas.CreateDepartmentsDto;
  pathParams: UpdateDepartmentPathParams;
} & BackendContext["fetcherOptions"];

export const fetchUpdateDepartment = (
  variables: UpdateDepartmentVariables,
  signal?: AbortSignal,
) =>
  backendFetch<
    Schemas.CreateUpdateDepartmentResponseDto,
    UpdateDepartmentError,
    Schemas.CreateDepartmentsDto,
    {},
    {},
    UpdateDepartmentPathParams
  >({ url: "/departments/{id}", method: "put", ...variables, signal });

export const useUpdateDepartment = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      Schemas.CreateUpdateDepartmentResponseDto,
      UpdateDepartmentError,
      UpdateDepartmentVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useBackendContext();
  return reactQuery.useMutation<
    Schemas.CreateUpdateDepartmentResponseDto,
    UpdateDepartmentError,
    UpdateDepartmentVariables
  >({
    mutationFn: (variables: UpdateDepartmentVariables) =>
      fetchUpdateDepartment({ ...fetcherOptions, ...variables }),
    ...options,
  });
};

export type DeleteDepartmentByIdPathParams = {
  /**
   * id of the department
   *
   * @example 65e3579de0ca70fe8f2e148e
   */
  id: string;
};

export type DeleteDepartmentByIdError = Fetcher.ErrorWrapper<undefined>;

export type DeleteDepartmentByIdVariables = {
  pathParams: DeleteDepartmentByIdPathParams;
} & BackendContext["fetcherOptions"];

export const fetchDeleteDepartmentById = (
  variables: DeleteDepartmentByIdVariables,
  signal?: AbortSignal,
) =>
  backendFetch<
    Schemas.CreateUpdateDepartmentResponseDto,
    DeleteDepartmentByIdError,
    undefined,
    {},
    {},
    DeleteDepartmentByIdPathParams
  >({ url: "/departments/{id}", method: "delete", ...variables, signal });

export const useDeleteDepartmentById = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      Schemas.CreateUpdateDepartmentResponseDto,
      DeleteDepartmentByIdError,
      DeleteDepartmentByIdVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useBackendContext();
  return reactQuery.useMutation<
    Schemas.CreateUpdateDepartmentResponseDto,
    DeleteDepartmentByIdError,
    DeleteDepartmentByIdVariables
  >({
    mutationFn: (variables: DeleteDepartmentByIdVariables) =>
      fetchDeleteDepartmentById({ ...fetcherOptions, ...variables }),
    ...options,
  });
};

export type GetAllDepartmentsError = Fetcher.ErrorWrapper<undefined>;

export type GetAllDepartmentsVariables = BackendContext["fetcherOptions"];

export const fetchGetAllDepartments = (
  variables: GetAllDepartmentsVariables,
  signal?: AbortSignal,
) =>
  backendFetch<
    Schemas.GetAllDepartmentResponseDto,
    GetAllDepartmentsError,
    undefined,
    {},
    {},
    {}
  >({ url: "/departments/dropdown", method: "get", ...variables, signal });

export const useGetAllDepartments = <
  TData = Schemas.GetAllDepartmentResponseDto,
>(
  variables: GetAllDepartmentsVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      Schemas.GetAllDepartmentResponseDto,
      GetAllDepartmentsError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { fetcherOptions, queryOptions, queryKeyFn } =
    useBackendContext(options);
  return reactQuery.useQuery<
    Schemas.GetAllDepartmentResponseDto,
    GetAllDepartmentsError,
    TData
  >({
    queryKey: queryKeyFn({
      path: "/departments/dropdown",
      operationId: "getAllDepartments",
      variables,
    }),
    queryFn: ({ signal }) =>
      fetchGetAllDepartments({ ...fetcherOptions, ...variables }, signal),
    ...options,
    ...queryOptions,
  });
};

export type GetAllDepartmentsByModuleIdPathParams = {
  /**
   * id of the module
   *
   * @example 65e3579de0ca70fe8f2e148e
   */
  moduleId: string;
};

export type GetAllDepartmentsByModuleIdError = Fetcher.ErrorWrapper<undefined>;

export type GetAllDepartmentsByModuleIdVariables = {
  pathParams: GetAllDepartmentsByModuleIdPathParams;
} & BackendContext["fetcherOptions"];

export const fetchGetAllDepartmentsByModuleId = (
  variables: GetAllDepartmentsByModuleIdVariables,
  signal?: AbortSignal,
) =>
  backendFetch<
    Schemas.GetAllDepartmentResponseDto,
    GetAllDepartmentsByModuleIdError,
    undefined,
    {},
    {},
    GetAllDepartmentsByModuleIdPathParams
  >({
    url: "/departments/forms/dropdown/{moduleId}",
    method: "get",
    ...variables,
    signal,
  });

export const useGetAllDepartmentsByModuleId = <
  TData = Schemas.GetAllDepartmentResponseDto,
>(
  variables: GetAllDepartmentsByModuleIdVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      Schemas.GetAllDepartmentResponseDto,
      GetAllDepartmentsByModuleIdError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { fetcherOptions, queryOptions, queryKeyFn } =
    useBackendContext(options);
  return reactQuery.useQuery<
    Schemas.GetAllDepartmentResponseDto,
    GetAllDepartmentsByModuleIdError,
    TData
  >({
    queryKey: queryKeyFn({
      path: "/departments/forms/dropdown/{moduleId}",
      operationId: "getAllDepartmentsByModuleId",
      variables,
    }),
    queryFn: ({ signal }) =>
      fetchGetAllDepartmentsByModuleId(
        { ...fetcherOptions, ...variables },
        signal,
      ),
    ...options,
    ...queryOptions,
  });
};

export type GetAllUserDepartmentsError = Fetcher.ErrorWrapper<undefined>;

export type GetAllUserDepartmentsVariables = BackendContext["fetcherOptions"];

export const fetchGetAllUserDepartments = (
  variables: GetAllUserDepartmentsVariables,
  signal?: AbortSignal,
) =>
  backendFetch<
    Schemas.GetAllDepartmentsWithRolesResponseDto,
    GetAllUserDepartmentsError,
    undefined,
    {},
    {},
    {}
  >({ url: "/departments/User/dropdown", method: "get", ...variables, signal });

export const useGetAllUserDepartments = <
  TData = Schemas.GetAllDepartmentsWithRolesResponseDto,
>(
  variables: GetAllUserDepartmentsVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      Schemas.GetAllDepartmentsWithRolesResponseDto,
      GetAllUserDepartmentsError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { fetcherOptions, queryOptions, queryKeyFn } =
    useBackendContext(options);
  return reactQuery.useQuery<
    Schemas.GetAllDepartmentsWithRolesResponseDto,
    GetAllUserDepartmentsError,
    TData
  >({
    queryKey: queryKeyFn({
      path: "/departments/User/dropdown",
      operationId: "getAllUserDepartments",
      variables,
    }),
    queryFn: ({ signal }) =>
      fetchGetAllUserDepartments({ ...fetcherOptions, ...variables }, signal),
    ...options,
    ...queryOptions,
  });
};

export type CreatePermissionError = Fetcher.ErrorWrapper<undefined>;

export type CreatePermissionVariables = {
  body: Schemas.CreatePermissionsDto;
} & BackendContext["fetcherOptions"];

export const fetchCreatePermission = (
  variables: CreatePermissionVariables,
  signal?: AbortSignal,
) =>
  backendFetch<
    Schemas.CreateUpdatePermissionResponseDto,
    CreatePermissionError,
    Schemas.CreatePermissionsDto,
    {},
    {},
    {}
  >({ url: "/permission", method: "post", ...variables, signal });

export const useCreatePermission = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      Schemas.CreateUpdatePermissionResponseDto,
      CreatePermissionError,
      CreatePermissionVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useBackendContext();
  return reactQuery.useMutation<
    Schemas.CreateUpdatePermissionResponseDto,
    CreatePermissionError,
    CreatePermissionVariables
  >({
    mutationFn: (variables: CreatePermissionVariables) =>
      fetchCreatePermission({ ...fetcherOptions, ...variables }),
    ...options,
  });
};

export type GetPermissionListQueryParams = {
  /**
   * Id of the Module
   *
   * @example 65e3579de0ca70fe8f2e148e
   */
  menuModuleId: string;
  /**
   * Email address of the user
   *
   * @example balak@nrl.com.au
   */
  email: string;
};

export type GetPermissionListError = Fetcher.ErrorWrapper<undefined>;

export type GetPermissionListVariables = {
  queryParams: GetPermissionListQueryParams;
} & BackendContext["fetcherOptions"];

export const fetchGetPermissionList = (
  variables: GetPermissionListVariables,
  signal?: AbortSignal,
) =>
  backendFetch<
    Schemas.GetAllPerissionsResponseDto,
    GetPermissionListError,
    undefined,
    {},
    GetPermissionListQueryParams,
    {}
  >({ url: "/permission/list", method: "get", ...variables, signal });

export const useGetPermissionList = <
  TData = Schemas.GetAllPerissionsResponseDto,
>(
  variables: GetPermissionListVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      Schemas.GetAllPerissionsResponseDto,
      GetPermissionListError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { fetcherOptions, queryOptions, queryKeyFn } =
    useBackendContext(options);
  return reactQuery.useQuery<
    Schemas.GetAllPerissionsResponseDto,
    GetPermissionListError,
    TData
  >({
    queryKey: queryKeyFn({
      path: "/permission/list",
      operationId: "getPermissionList",
      variables,
    }),
    queryFn: ({ signal }) =>
      fetchGetPermissionList({ ...fetcherOptions, ...variables }, signal),
    ...options,
    ...queryOptions,
  });
};

export type GetPermissionByIdPathParams = {
  /**
   * id of the Permission
   *
   * @example 65e3579de0ca70fe8f2e148e
   */
  id: string;
};

export type GetPermissionByIdQueryParams = {
  /**
   * Id of the Module
   *
   * @example 65e3579de0ca70fe8f2e148e
   */
  menuModuleId: string;
  /**
   * Email address of the user
   *
   * @example balak@nrl.com.au
   */
  email: string;
};

export type GetPermissionByIdError = Fetcher.ErrorWrapper<undefined>;

export type GetPermissionByIdVariables = {
  pathParams: GetPermissionByIdPathParams;
  queryParams: GetPermissionByIdQueryParams;
} & BackendContext["fetcherOptions"];

export const fetchGetPermissionById = (
  variables: GetPermissionByIdVariables,
  signal?: AbortSignal,
) =>
  backendFetch<
    Schemas.GetPerissionsDetailsResponseDto,
    GetPermissionByIdError,
    undefined,
    {},
    GetPermissionByIdQueryParams,
    GetPermissionByIdPathParams
  >({ url: "/permission/detail/{id}", method: "get", ...variables, signal });

export const useGetPermissionById = <
  TData = Schemas.GetPerissionsDetailsResponseDto,
>(
  variables: GetPermissionByIdVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      Schemas.GetPerissionsDetailsResponseDto,
      GetPermissionByIdError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { fetcherOptions, queryOptions, queryKeyFn } =
    useBackendContext(options);
  return reactQuery.useQuery<
    Schemas.GetPerissionsDetailsResponseDto,
    GetPermissionByIdError,
    TData
  >({
    queryKey: queryKeyFn({
      path: "/permission/detail/{id}",
      operationId: "getPermissionById",
      variables,
    }),
    queryFn: ({ signal }) =>
      fetchGetPermissionById({ ...fetcherOptions, ...variables }, signal),
    ...options,
    ...queryOptions,
  });
};

export type UpdatePermissionPathParams = {
  /**
   * id of the Permission
   *
   * @example 65e3579de0ca70fe8f2e148e
   */
  id: string;
};

export type UpdatePermissionError = Fetcher.ErrorWrapper<undefined>;

export type UpdatePermissionVariables = {
  body: Schemas.CreatePermissionsDto;
  pathParams: UpdatePermissionPathParams;
} & BackendContext["fetcherOptions"];

export const fetchUpdatePermission = (
  variables: UpdatePermissionVariables,
  signal?: AbortSignal,
) =>
  backendFetch<
    Schemas.CreateUpdatePermissionResponseDto,
    UpdatePermissionError,
    Schemas.CreatePermissionsDto,
    {},
    {},
    UpdatePermissionPathParams
  >({ url: "/permission/{id}", method: "put", ...variables, signal });

export const useUpdatePermission = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      Schemas.CreateUpdatePermissionResponseDto,
      UpdatePermissionError,
      UpdatePermissionVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useBackendContext();
  return reactQuery.useMutation<
    Schemas.CreateUpdatePermissionResponseDto,
    UpdatePermissionError,
    UpdatePermissionVariables
  >({
    mutationFn: (variables: UpdatePermissionVariables) =>
      fetchUpdatePermission({ ...fetcherOptions, ...variables }),
    ...options,
  });
};

export type DeletePermissionByIdPathParams = {
  /**
   * id of the Permission
   *
   * @example 65e3579de0ca70fe8f2e148e
   */
  id: string;
};

export type DeletePermissionByIdError = Fetcher.ErrorWrapper<undefined>;

export type DeletePermissionByIdVariables = {
  pathParams: DeletePermissionByIdPathParams;
} & BackendContext["fetcherOptions"];

export const fetchDeletePermissionById = (
  variables: DeletePermissionByIdVariables,
  signal?: AbortSignal,
) =>
  backendFetch<
    Schemas.CreateUpdatePermissionResponseDto,
    DeletePermissionByIdError,
    undefined,
    {},
    {},
    DeletePermissionByIdPathParams
  >({ url: "/permission/{id}", method: "delete", ...variables, signal });

export const useDeletePermissionById = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      Schemas.CreateUpdatePermissionResponseDto,
      DeletePermissionByIdError,
      DeletePermissionByIdVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useBackendContext();
  return reactQuery.useMutation<
    Schemas.CreateUpdatePermissionResponseDto,
    DeletePermissionByIdError,
    DeletePermissionByIdVariables
  >({
    mutationFn: (variables: DeletePermissionByIdVariables) =>
      fetchDeletePermissionById({ ...fetcherOptions, ...variables }),
    ...options,
  });
};

export type GetAllPermissionDropdownQueryParams = {
  /**
   * Id of the module
   *
   * @example  65e3579de0ca70fe8f2e148e
   */
  moduleId?: string;
};

export type GetAllPermissionDropdownError = Fetcher.ErrorWrapper<undefined>;

export type GetAllPermissionDropdownVariables = {
  queryParams?: GetAllPermissionDropdownQueryParams;
} & BackendContext["fetcherOptions"];

export const fetchGetAllPermissionDropdown = (
  variables: GetAllPermissionDropdownVariables,
  signal?: AbortSignal,
) =>
  backendFetch<
    Schemas.GetAllPermissionResponseDto,
    GetAllPermissionDropdownError,
    undefined,
    {},
    GetAllPermissionDropdownQueryParams,
    {}
  >({ url: "/permission/dropdown", method: "get", ...variables, signal });

export const useGetAllPermissionDropdown = <
  TData = Schemas.GetAllPermissionResponseDto,
>(
  variables: GetAllPermissionDropdownVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      Schemas.GetAllPermissionResponseDto,
      GetAllPermissionDropdownError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { fetcherOptions, queryOptions, queryKeyFn } =
    useBackendContext(options);
  return reactQuery.useQuery<
    Schemas.GetAllPermissionResponseDto,
    GetAllPermissionDropdownError,
    TData
  >({
    queryKey: queryKeyFn({
      path: "/permission/dropdown",
      operationId: "getAllPermissionDropdown",
      variables,
    }),
    queryFn: ({ signal }) =>
      fetchGetAllPermissionDropdown(
        { ...fetcherOptions, ...variables },
        signal,
      ),
    ...options,
    ...queryOptions,
  });
};

export type CreateRoleError = Fetcher.ErrorWrapper<undefined>;

export type CreateRoleVariables = {
  body: Schemas.CreateRolesDto;
} & BackendContext["fetcherOptions"];

export const fetchCreateRole = (
  variables: CreateRoleVariables,
  signal?: AbortSignal,
) =>
  backendFetch<
    Schemas.CreateUpdateRoleResponseDto,
    CreateRoleError,
    Schemas.CreateRolesDto,
    {},
    {},
    {}
  >({ url: "/role", method: "post", ...variables, signal });

export const useCreateRole = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      Schemas.CreateUpdateRoleResponseDto,
      CreateRoleError,
      CreateRoleVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useBackendContext();
  return reactQuery.useMutation<
    Schemas.CreateUpdateRoleResponseDto,
    CreateRoleError,
    CreateRoleVariables
  >({
    mutationFn: (variables: CreateRoleVariables) =>
      fetchCreateRole({ ...fetcherOptions, ...variables }),
    ...options,
  });
};

export type GetRoleListQueryParams = {
  /**
   * Id of the Module
   *
   * @example 65e3579de0ca70fe8f2e148e
   */
  menuModuleId: string;
  /**
   * Email address of the user
   *
   * @example balak@nrl.com.au
   */
  email: string;
};

export type GetRoleListError = Fetcher.ErrorWrapper<undefined>;

export type GetRoleListVariables = {
  queryParams: GetRoleListQueryParams;
} & BackendContext["fetcherOptions"];

export const fetchGetRoleList = (
  variables: GetRoleListVariables,
  signal?: AbortSignal,
) =>
  backendFetch<
    Schemas.AdminRolesResponseDto,
    GetRoleListError,
    undefined,
    {},
    GetRoleListQueryParams,
    {}
  >({ url: "/role/list", method: "get", ...variables, signal });

export const useGetRoleList = <TData = Schemas.AdminRolesResponseDto,>(
  variables: GetRoleListVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      Schemas.AdminRolesResponseDto,
      GetRoleListError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { fetcherOptions, queryOptions, queryKeyFn } =
    useBackendContext(options);
  return reactQuery.useQuery<
    Schemas.AdminRolesResponseDto,
    GetRoleListError,
    TData
  >({
    queryKey: queryKeyFn({
      path: "/role/list",
      operationId: "getRoleList",
      variables,
    }),
    queryFn: ({ signal }) =>
      fetchGetRoleList({ ...fetcherOptions, ...variables }, signal),
    ...options,
    ...queryOptions,
  });
};

export type GetRoleDetailByIdPathParams = {
  /**
   * id of the role
   *
   * @example 65e3579de0ca70fe8f2e148e
   */
  id: string;
};

export type GetRoleDetailByIdQueryParams = {
  /**
   * Id of the Module
   *
   * @example 65e3579de0ca70fe8f2e148e
   */
  menuModuleId: string;
  /**
   * Email address of the user
   *
   * @example balak@nrl.com.au
   */
  email: string;
};

export type GetRoleDetailByIdError = Fetcher.ErrorWrapper<undefined>;

export type GetRoleDetailByIdVariables = {
  pathParams: GetRoleDetailByIdPathParams;
  queryParams: GetRoleDetailByIdQueryParams;
} & BackendContext["fetcherOptions"];

export const fetchGetRoleDetailById = (
  variables: GetRoleDetailByIdVariables,
  signal?: AbortSignal,
) =>
  backendFetch<
    Schemas.GetRoleByIdResponseDto,
    GetRoleDetailByIdError,
    undefined,
    {},
    GetRoleDetailByIdQueryParams,
    GetRoleDetailByIdPathParams
  >({ url: "/role/detail/{id}", method: "get", ...variables, signal });

export const useGetRoleDetailById = <TData = Schemas.GetRoleByIdResponseDto,>(
  variables: GetRoleDetailByIdVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      Schemas.GetRoleByIdResponseDto,
      GetRoleDetailByIdError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { fetcherOptions, queryOptions, queryKeyFn } =
    useBackendContext(options);
  return reactQuery.useQuery<
    Schemas.GetRoleByIdResponseDto,
    GetRoleDetailByIdError,
    TData
  >({
    queryKey: queryKeyFn({
      path: "/role/detail/{id}",
      operationId: "getRoleDetailById",
      variables,
    }),
    queryFn: ({ signal }) =>
      fetchGetRoleDetailById({ ...fetcherOptions, ...variables }, signal),
    ...options,
    ...queryOptions,
  });
};

export type UpdateRolePathParams = {
  /**
   * id of the role
   *
   * @example 65e3579de0ca70fe8f2e148e
   */
  id: string;
};

export type UpdateRoleError = Fetcher.ErrorWrapper<undefined>;

export type UpdateRoleVariables = {
  body: Schemas.CreateRolesDto;
  pathParams: UpdateRolePathParams;
} & BackendContext["fetcherOptions"];

export const fetchUpdateRole = (
  variables: UpdateRoleVariables,
  signal?: AbortSignal,
) =>
  backendFetch<
    Schemas.CreateUpdateRoleResponseDto,
    UpdateRoleError,
    Schemas.CreateRolesDto,
    {},
    {},
    UpdateRolePathParams
  >({ url: "/role/{id}", method: "put", ...variables, signal });

export const useUpdateRole = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      Schemas.CreateUpdateRoleResponseDto,
      UpdateRoleError,
      UpdateRoleVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useBackendContext();
  return reactQuery.useMutation<
    Schemas.CreateUpdateRoleResponseDto,
    UpdateRoleError,
    UpdateRoleVariables
  >({
    mutationFn: (variables: UpdateRoleVariables) =>
      fetchUpdateRole({ ...fetcherOptions, ...variables }),
    ...options,
  });
};

export type DeleteRoleByIdPathParams = {
  id: string;
};

export type DeleteRoleByIdError = Fetcher.ErrorWrapper<undefined>;

export type DeleteRoleByIdVariables = {
  pathParams: DeleteRoleByIdPathParams;
} & BackendContext["fetcherOptions"];

export const fetchDeleteRoleById = (
  variables: DeleteRoleByIdVariables,
  signal?: AbortSignal,
) =>
  backendFetch<
    Schemas.CreateUpdateRoleResponseDto,
    DeleteRoleByIdError,
    undefined,
    {},
    {},
    DeleteRoleByIdPathParams
  >({ url: "/role/{id}", method: "delete", ...variables, signal });

export const useDeleteRoleById = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      Schemas.CreateUpdateRoleResponseDto,
      DeleteRoleByIdError,
      DeleteRoleByIdVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useBackendContext();
  return reactQuery.useMutation<
    Schemas.CreateUpdateRoleResponseDto,
    DeleteRoleByIdError,
    DeleteRoleByIdVariables
  >({
    mutationFn: (variables: DeleteRoleByIdVariables) =>
      fetchDeleteRoleById({ ...fetcherOptions, ...variables }),
    ...options,
  });
};

export type GetConfigurationRoleByIdPathParams = {
  /**
   * id of the module
   *
   * @example 65e3579de0ca70fe8f2e148e
   */
  moduleId: string;
};

export type GetConfigurationRoleByIdError = Fetcher.ErrorWrapper<undefined>;

export type GetConfigurationRoleByIdVariables = {
  pathParams: GetConfigurationRoleByIdPathParams;
} & BackendContext["fetcherOptions"];

export const fetchGetConfigurationRoleById = (
  variables: GetConfigurationRoleByIdVariables,
  signal?: AbortSignal,
) =>
  backendFetch<
    Schemas.ConfigurationResponseDto,
    GetConfigurationRoleByIdError,
    undefined,
    {},
    {},
    GetConfigurationRoleByIdPathParams
  >({
    url: "/role/configurationModules/{moduleId}",
    method: "get",
    ...variables,
    signal,
  });

export const useGetConfigurationRoleById = <
  TData = Schemas.ConfigurationResponseDto,
>(
  variables: GetConfigurationRoleByIdVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      Schemas.ConfigurationResponseDto,
      GetConfigurationRoleByIdError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { fetcherOptions, queryOptions, queryKeyFn } =
    useBackendContext(options);
  return reactQuery.useQuery<
    Schemas.ConfigurationResponseDto,
    GetConfigurationRoleByIdError,
    TData
  >({
    queryKey: queryKeyFn({
      path: "/role/configurationModules/{moduleId}",
      operationId: "getConfigurationRoleById",
      variables,
    }),
    queryFn: ({ signal }) =>
      fetchGetConfigurationRoleById(
        { ...fetcherOptions, ...variables },
        signal,
      ),
    ...options,
    ...queryOptions,
  });
};

export type GetAllRolesError = Fetcher.ErrorWrapper<undefined>;

export type GetAllRolesVariables = BackendContext["fetcherOptions"];

export const fetchGetAllRoles = (
  variables: GetAllRolesVariables,
  signal?: AbortSignal,
) =>
  backendFetch<
    Schemas.GetAllRolesResponseDto,
    GetAllRolesError,
    undefined,
    {},
    {},
    {}
  >({ url: "/role/dropdown", method: "get", ...variables, signal });

export const useGetAllRoles = <TData = Schemas.GetAllRolesResponseDto,>(
  variables: GetAllRolesVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      Schemas.GetAllRolesResponseDto,
      GetAllRolesError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { fetcherOptions, queryOptions, queryKeyFn } =
    useBackendContext(options);
  return reactQuery.useQuery<
    Schemas.GetAllRolesResponseDto,
    GetAllRolesError,
    TData
  >({
    queryKey: queryKeyFn({
      path: "/role/dropdown",
      operationId: "getAllRoles",
      variables,
    }),
    queryFn: ({ signal }) =>
      fetchGetAllRoles({ ...fetcherOptions, ...variables }, signal),
    ...options,
    ...queryOptions,
  });
};

export type GetAllRolesByDeptIdPathParams = {
  /**
   * id of the department
   *
   * @example 65e3579de0ca70fe8f2e148e
   */
  id: string;
};

export type GetAllRolesByDeptIdError = Fetcher.ErrorWrapper<undefined>;

export type GetAllRolesByDeptIdVariables = {
  pathParams: GetAllRolesByDeptIdPathParams;
} & BackendContext["fetcherOptions"];

export const fetchGetAllRolesByDeptId = (
  variables: GetAllRolesByDeptIdVariables,
  signal?: AbortSignal,
) =>
  backendFetch<
    Schemas.GetAllRolesResponseDto,
    GetAllRolesByDeptIdError,
    undefined,
    {},
    {},
    GetAllRolesByDeptIdPathParams
  >({ url: "/role/dropdown/{id}", method: "get", ...variables, signal });

export const useGetAllRolesByDeptId = <TData = Schemas.GetAllRolesResponseDto,>(
  variables: GetAllRolesByDeptIdVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      Schemas.GetAllRolesResponseDto,
      GetAllRolesByDeptIdError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { fetcherOptions, queryOptions, queryKeyFn } =
    useBackendContext(options);
  return reactQuery.useQuery<
    Schemas.GetAllRolesResponseDto,
    GetAllRolesByDeptIdError,
    TData
  >({
    queryKey: queryKeyFn({
      path: "/role/dropdown/{id}",
      operationId: "getAllRolesByDeptId",
      variables,
    }),
    queryFn: ({ signal }) =>
      fetchGetAllRolesByDeptId({ ...fetcherOptions, ...variables }, signal),
    ...options,
    ...queryOptions,
  });
};

export type GenerateSignedUrlQueryParams = {
  /**
   * Message related to the form
   *
   * @example sample.pdf
   */
  key: string;
  /**
   * Message related to the form
   *
   * @example pdf
   */
  contentType: string;
};

export type GenerateSignedUrlError = Fetcher.ErrorWrapper<undefined>;

export type GenerateSignedUrlVariables = {
  queryParams: GenerateSignedUrlQueryParams;
} & BackendContext["fetcherOptions"];

export const fetchGenerateSignedUrl = (
  variables: GenerateSignedUrlVariables,
  signal?: AbortSignal,
) =>
  backendFetch<
    Schemas.UrlDto,
    GenerateSignedUrlError,
    undefined,
    {},
    GenerateSignedUrlQueryParams,
    {}
  >({
    url: "/document-handler/generate-signedurl",
    method: "get",
    ...variables,
    signal,
  });

export const useGenerateSignedUrl = <TData = Schemas.UrlDto,>(
  variables: GenerateSignedUrlVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<Schemas.UrlDto, GenerateSignedUrlError, TData>,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { fetcherOptions, queryOptions, queryKeyFn } =
    useBackendContext(options);
  return reactQuery.useQuery<Schemas.UrlDto, GenerateSignedUrlError, TData>({
    queryKey: queryKeyFn({
      path: "/document-handler/generate-signedurl",
      operationId: "generateSignedUrl",
      variables,
    }),
    queryFn: ({ signal }) =>
      fetchGenerateSignedUrl({ ...fetcherOptions, ...variables }, signal),
    ...options,
    ...queryOptions,
  });
};

export type UpdateFormStausError = Fetcher.ErrorWrapper<undefined>;

export type UpdateFormStausVariables = {
  body: Schemas.UpdateFormRequestDto;
} & BackendContext["fetcherOptions"];

export const fetchUpdateFormStaus = (
  variables: UpdateFormStausVariables,
  signal?: AbortSignal,
) =>
  backendFetch<
    Schemas.UploadResponseDto,
    UpdateFormStausError,
    Schemas.UpdateFormRequestDto,
    {},
    {},
    {}
  >({
    url: "/document-handler/updateFormStatus",
    method: "post",
    ...variables,
    signal,
  });

export const useUpdateFormStaus = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      Schemas.UploadResponseDto,
      UpdateFormStausError,
      UpdateFormStausVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useBackendContext();
  return reactQuery.useMutation<
    Schemas.UploadResponseDto,
    UpdateFormStausError,
    UpdateFormStausVariables
  >({
    mutationFn: (variables: UpdateFormStausVariables) =>
      fetchUpdateFormStaus({ ...fetcherOptions, ...variables }),
    ...options,
  });
};

export type GenerateDownloadQueryParams = {
  /**
   * url for file download
   *
   * @example msadocuments/form_20240924T051744386Z_61709.pdf
   */
  url: string;
};

export type GenerateDownloadError = Fetcher.ErrorWrapper<undefined>;

export type GenerateDownloadVariables = {
  queryParams: GenerateDownloadQueryParams;
} & BackendContext["fetcherOptions"];

export const fetchGenerateDownload = (
  variables: GenerateDownloadVariables,
  signal?: AbortSignal,
) =>
  backendFetch<
    Schemas.GenerateDownloadResponseDto,
    GenerateDownloadError,
    undefined,
    {},
    GenerateDownloadQueryParams,
    {}
  >({
    url: "/document-handler/files-download",
    method: "get",
    ...variables,
    signal,
  });

export const useGenerateDownload = <
  TData = Schemas.GenerateDownloadResponseDto,
>(
  variables: GenerateDownloadVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      Schemas.GenerateDownloadResponseDto,
      GenerateDownloadError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { fetcherOptions, queryOptions, queryKeyFn } =
    useBackendContext(options);
  return reactQuery.useQuery<
    Schemas.GenerateDownloadResponseDto,
    GenerateDownloadError,
    TData
  >({
    queryKey: queryKeyFn({
      path: "/document-handler/files-download",
      operationId: "generateDownload",
      variables,
    }),
    queryFn: ({ signal }) =>
      fetchGenerateDownload({ ...fetcherOptions, ...variables }, signal),
    ...options,
    ...queryOptions,
  });
};

export type GeneratePreSignedUrlQueryParams = {
  /**
   * The URL which has to be pre signed
   *
   * @example https://dev-form-builder-ent-bucket.s3.ap-southeast-2.amazonaws.com/sample.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=ASIA2SFQEUYDQJY3IFC3%2F20250115%2Fap-southeast-2%2Fs3%2Faws4_request&X-Amz-Date=20250115T061248Z&X-Amz-Expires=3600&X-Amz-Security-Token=FwoGZXIvYXdzEEAaDA7z7%2FUx9pOluKIQUiKcAjX4Nw%2BTsZke5bMKKLJSRO9qGmURHFhAwtLnevQVBG4Z9shcFDR3tQ4sE2yeTgKq7KEBOrAJuMKWY13u%2FncJMR%2FmXWlapStZS5giML8mW%2BcmcbFUMnysdUMduVMCXAYV%2F5kul1Rq8NSnYz%2BVkC67hDjS%2B78QRGiC0yUB8JLw3F%2BQ02dhtXDferMZoSNsBe6TBDIayWw9OVjHRlSGE7GDYvRbw5Wf319alW8qPWUlzMp%2BruSeYQyVxVJrvrP4JriBcd6plEbJ6yOCsC2sGPqbzF7ciFJEW2am2yd2u6qEAu74Tb6M1F5hk899s3ZgtsuG0PUiex8z7w%2F1UW8%2FabrO9FRTDcq7jGAVXQLt7ZD1yE6Hb7iFP5y7yYg6SQ1hKIGjnbwGMiqLZf9iGcvSatG6x7s%2Bp5o%2FYY69Qtn08nLtsWzGR7G8UJ1Y0nsNORKxZVA%3D&X-Amz-Signature=16b24def903c8acb307bd10caa7bdf95a45d708516f540a3ae29d1e2e814109c&X-Amz-SignedHeaders=host&x-id=PutObject
   */
  url: string;
};

export type GeneratePreSignedUrlError = Fetcher.ErrorWrapper<undefined>;

export type GeneratePreSignedUrlVariables = {
  queryParams: GeneratePreSignedUrlQueryParams;
} & BackendContext["fetcherOptions"];

export const fetchGeneratePreSignedUrl = (
  variables: GeneratePreSignedUrlVariables,
  signal?: AbortSignal,
) =>
  backendFetch<
    Schemas.GeneratePreSignedUrlResponseDto,
    GeneratePreSignedUrlError,
    undefined,
    {},
    GeneratePreSignedUrlQueryParams,
    {}
  >({
    url: "/document-handler/files-fetch",
    method: "get",
    ...variables,
    signal,
  });

export const useGeneratePreSignedUrl = <
  TData = Schemas.GeneratePreSignedUrlResponseDto,
>(
  variables: GeneratePreSignedUrlVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      Schemas.GeneratePreSignedUrlResponseDto,
      GeneratePreSignedUrlError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { fetcherOptions, queryOptions, queryKeyFn } =
    useBackendContext(options);
  return reactQuery.useQuery<
    Schemas.GeneratePreSignedUrlResponseDto,
    GeneratePreSignedUrlError,
    TData
  >({
    queryKey: queryKeyFn({
      path: "/document-handler/files-fetch",
      operationId: "generatePreSignedUrl",
      variables,
    }),
    queryFn: ({ signal }) =>
      fetchGeneratePreSignedUrl({ ...fetcherOptions, ...variables }, signal),
    ...options,
    ...queryOptions,
  });
};

export type CreateUserError = Fetcher.ErrorWrapper<undefined>;

export type CreateUserVariables = {
  body: Schemas.CreateUsersDto;
} & BackendContext["fetcherOptions"];

export const fetchCreateUser = (
  variables: CreateUserVariables,
  signal?: AbortSignal,
) =>
  backendFetch<
    Schemas.CreateUpdateUserResponseDto,
    CreateUserError,
    Schemas.CreateUsersDto,
    {},
    {},
    {}
  >({ url: "/user", method: "post", ...variables, signal });

export const useCreateUser = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      Schemas.CreateUpdateUserResponseDto,
      CreateUserError,
      CreateUserVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useBackendContext();
  return reactQuery.useMutation<
    Schemas.CreateUpdateUserResponseDto,
    CreateUserError,
    CreateUserVariables
  >({
    mutationFn: (variables: CreateUserVariables) =>
      fetchCreateUser({ ...fetcherOptions, ...variables }),
    ...options,
  });
};

export type GetUserListQueryParams = {
  /**
   * Id of the Module
   *
   * @example 65e3579de0ca70fe8f2e148e
   */
  menuModuleId: string;
  /**
   * Email address of the user
   *
   * @example balak@nrl.com.au
   */
  email: string;
  /**
   * The starting index for pagination
   *
   * @example 0
   */
  start?: string;
  /**
   * The number of items to be retrieved per page
   *
   * @example 10
   */
  size?: string;
  /**
   * Search text for filtering results
   *
   * @example example search text
   */
  searchText?: string;
  /**
   * Field by which to sort the results
   *
   * @example ASC
   */
  sortBy?: string;
  /**
   * Sorting order, either true (ascending) or false (descending)
   *
   * @example true
   */
  sortOrder?: boolean;
};

export type GetUserListError = Fetcher.ErrorWrapper<undefined>;

export type GetUserListVariables = {
  queryParams: GetUserListQueryParams;
} & BackendContext["fetcherOptions"];

export const fetchGetUserList = (
  variables: GetUserListVariables,
  signal?: AbortSignal,
) =>
  backendFetch<
    Schemas.AdminRolesResponseDto,
    GetUserListError,
    undefined,
    {},
    GetUserListQueryParams,
    {}
  >({ url: "/user/list", method: "get", ...variables, signal });

export const useGetUserList = <TData = Schemas.AdminRolesResponseDto,>(
  variables: GetUserListVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      Schemas.AdminRolesResponseDto,
      GetUserListError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { fetcherOptions, queryOptions, queryKeyFn } =
    useBackendContext(options);
  return reactQuery.useQuery<
    Schemas.AdminRolesResponseDto,
    GetUserListError,
    TData
  >({
    queryKey: queryKeyFn({
      path: "/user/list",
      operationId: "getUserList",
      variables,
    }),
    queryFn: ({ signal }) =>
      fetchGetUserList({ ...fetcherOptions, ...variables }, signal),
    ...options,
    ...queryOptions,
  });
};

export type GetUserByIdPathParams = {
  /**
   * Id of the user
   *
   * @example 65e3579de0ca70fe8f2e148e
   */
  id: string;
};

export type GetUserByIdQueryParams = {
  /**
   * Id of the Module
   *
   * @example 65e3579de0ca70fe8f2e148e
   */
  menuModuleId: string;
  /**
   * Email address of the user
   *
   * @example balak@nrl.com.au
   */
  email: string;
};

export type GetUserByIdError = Fetcher.ErrorWrapper<undefined>;

export type GetUserByIdVariables = {
  pathParams: GetUserByIdPathParams;
  queryParams: GetUserByIdQueryParams;
} & BackendContext["fetcherOptions"];

export const fetchGetUserById = (
  variables: GetUserByIdVariables,
  signal?: AbortSignal,
) =>
  backendFetch<
    Schemas.GetUserByIdResponseDto,
    GetUserByIdError,
    undefined,
    {},
    GetUserByIdQueryParams,
    GetUserByIdPathParams
  >({ url: "/user/detail/{id}", method: "get", ...variables, signal });

export const useGetUserById = <TData = Schemas.GetUserByIdResponseDto,>(
  variables: GetUserByIdVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      Schemas.GetUserByIdResponseDto,
      GetUserByIdError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { fetcherOptions, queryOptions, queryKeyFn } =
    useBackendContext(options);
  return reactQuery.useQuery<
    Schemas.GetUserByIdResponseDto,
    GetUserByIdError,
    TData
  >({
    queryKey: queryKeyFn({
      path: "/user/detail/{id}",
      operationId: "getUserById",
      variables,
    }),
    queryFn: ({ signal }) =>
      fetchGetUserById({ ...fetcherOptions, ...variables }, signal),
    ...options,
    ...queryOptions,
  });
};

export type UpdateUserPathParams = {
  id: string;
};

export type UpdateUserError = Fetcher.ErrorWrapper<undefined>;

export type UpdateUserVariables = {
  body: Schemas.CreateUsersDto;
  pathParams: UpdateUserPathParams;
} & BackendContext["fetcherOptions"];

export const fetchUpdateUser = (
  variables: UpdateUserVariables,
  signal?: AbortSignal,
) =>
  backendFetch<
    Schemas.CreateUpdateUserResponseDto,
    UpdateUserError,
    Schemas.CreateUsersDto,
    {},
    {},
    UpdateUserPathParams
  >({ url: "/user/{id}", method: "put", ...variables, signal });

export const useUpdateUser = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      Schemas.CreateUpdateUserResponseDto,
      UpdateUserError,
      UpdateUserVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useBackendContext();
  return reactQuery.useMutation<
    Schemas.CreateUpdateUserResponseDto,
    UpdateUserError,
    UpdateUserVariables
  >({
    mutationFn: (variables: UpdateUserVariables) =>
      fetchUpdateUser({ ...fetcherOptions, ...variables }),
    ...options,
  });
};

export type DeleteUserByIdPathParams = {
  id: string;
};

export type DeleteUserByIdError = Fetcher.ErrorWrapper<undefined>;

export type DeleteUserByIdVariables = {
  pathParams: DeleteUserByIdPathParams;
} & BackendContext["fetcherOptions"];

export const fetchDeleteUserById = (
  variables: DeleteUserByIdVariables,
  signal?: AbortSignal,
) =>
  backendFetch<
    Schemas.CreateUpdateUserResponseDto,
    DeleteUserByIdError,
    undefined,
    {},
    {},
    DeleteUserByIdPathParams
  >({ url: "/user/{id}", method: "delete", ...variables, signal });

export const useDeleteUserById = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      Schemas.CreateUpdateUserResponseDto,
      DeleteUserByIdError,
      DeleteUserByIdVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useBackendContext();
  return reactQuery.useMutation<
    Schemas.CreateUpdateUserResponseDto,
    DeleteUserByIdError,
    DeleteUserByIdVariables
  >({
    mutationFn: (variables: DeleteUserByIdVariables) =>
      fetchDeleteUserById({ ...fetcherOptions, ...variables }),
    ...options,
  });
};

export type GetAllUsersDropdownError = Fetcher.ErrorWrapper<undefined>;

export type GetAllUsersDropdownVariables = BackendContext["fetcherOptions"];

export const fetchGetAllUsersDropdown = (
  variables: GetAllUsersDropdownVariables,
  signal?: AbortSignal,
) =>
  backendFetch<
    Schemas.GetAllUsersResponseDto,
    GetAllUsersDropdownError,
    undefined,
    {},
    {},
    {}
  >({ url: "/user/dropdown", method: "get", ...variables, signal });

export const useGetAllUsersDropdown = <TData = Schemas.GetAllUsersResponseDto,>(
  variables: GetAllUsersDropdownVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      Schemas.GetAllUsersResponseDto,
      GetAllUsersDropdownError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { fetcherOptions, queryOptions, queryKeyFn } =
    useBackendContext(options);
  return reactQuery.useQuery<
    Schemas.GetAllUsersResponseDto,
    GetAllUsersDropdownError,
    TData
  >({
    queryKey: queryKeyFn({
      path: "/user/dropdown",
      operationId: "getAllUsersDropdown",
      variables,
    }),
    queryFn: ({ signal }) =>
      fetchGetAllUsersDropdown({ ...fetcherOptions, ...variables }, signal),
    ...options,
    ...queryOptions,
  });
};

export type GetUserMetaPathParams = {
  /**
   * email of the user
   *
   * @example mmurugesan@nrl.com.au
   */
  email: string;
};

export type GetUserMetaError = Fetcher.ErrorWrapper<undefined>;

export type GetUserMetaVariables = {
  pathParams: GetUserMetaPathParams;
} & BackendContext["fetcherOptions"];

export const fetchGetUserMeta = (
  variables: GetUserMetaVariables,
  signal?: AbortSignal,
) =>
  backendFetch<
    Schemas.UserMetaResponseDto,
    GetUserMetaError,
    undefined,
    {},
    {},
    GetUserMetaPathParams
  >({ url: "/user/profile/{email}", method: "get", ...variables, signal });

export const useGetUserMeta = <TData = Schemas.UserMetaResponseDto,>(
  variables: GetUserMetaVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      Schemas.UserMetaResponseDto,
      GetUserMetaError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { fetcherOptions, queryOptions, queryKeyFn } =
    useBackendContext(options);
  return reactQuery.useQuery<
    Schemas.UserMetaResponseDto,
    GetUserMetaError,
    TData
  >({
    queryKey: queryKeyFn({
      path: "/user/profile/{email}",
      operationId: "getUserMeta",
      variables,
    }),
    queryFn: ({ signal }) =>
      fetchGetUserMeta({ ...fetcherOptions, ...variables }, signal),
    ...options,
    ...queryOptions,
  });
};

export type GetImpersonateUsersListError = Fetcher.ErrorWrapper<undefined>;

export type GetImpersonateUsersListVariables = BackendContext["fetcherOptions"];

export const fetchGetImpersonateUsersList = (
  variables: GetImpersonateUsersListVariables,
  signal?: AbortSignal,
) =>
  backendFetch<
    Schemas.UserImpersonateResponseDto,
    GetImpersonateUsersListError,
    undefined,
    {},
    {},
    {}
  >({
    url: "/user/impersonate/user/list",
    method: "get",
    ...variables,
    signal,
  });

export const useGetImpersonateUsersList = <
  TData = Schemas.UserImpersonateResponseDto,
>(
  variables: GetImpersonateUsersListVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      Schemas.UserImpersonateResponseDto,
      GetImpersonateUsersListError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { fetcherOptions, queryOptions, queryKeyFn } =
    useBackendContext(options);
  return reactQuery.useQuery<
    Schemas.UserImpersonateResponseDto,
    GetImpersonateUsersListError,
    TData
  >({
    queryKey: queryKeyFn({
      path: "/user/impersonate/user/list",
      operationId: "getImpersonateUsersList",
      variables,
    }),
    queryFn: ({ signal }) =>
      fetchGetImpersonateUsersList({ ...fetcherOptions, ...variables }, signal),
    ...options,
    ...queryOptions,
  });
};

export type CreateWorkFlowError = Fetcher.ErrorWrapper<undefined>;

export type CreateWorkFlowVariables = {
  body: Schemas.CreateWorkflowDto;
} & BackendContext["fetcherOptions"];

export const fetchCreateWorkFlow = (
  variables: CreateWorkFlowVariables,
  signal?: AbortSignal,
) =>
  backendFetch<
    Schemas.CreateUpdateWorkflowResponseDto,
    CreateWorkFlowError,
    Schemas.CreateWorkflowDto,
    {},
    {},
    {}
  >({ url: "/workflow", method: "post", ...variables, signal });

export const useCreateWorkFlow = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      Schemas.CreateUpdateWorkflowResponseDto,
      CreateWorkFlowError,
      CreateWorkFlowVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useBackendContext();
  return reactQuery.useMutation<
    Schemas.CreateUpdateWorkflowResponseDto,
    CreateWorkFlowError,
    CreateWorkFlowVariables
  >({
    mutationFn: (variables: CreateWorkFlowVariables) =>
      fetchCreateWorkFlow({ ...fetcherOptions, ...variables }),
    ...options,
  });
};

export type GetWorkflowByModuleIdPathParams = {
  /**
   * id of the module
   *
   * @example 65e3579de0ca70fe8f2e148e
   */
  moduleId: string;
};

export type GetWorkflowByModuleIdQueryParams = {
  /**
   * Email address of the user
   *
   * @example mmurugesan@nrl.com.au
   */
  email: string;
  /**
   * Id of the Module
   *
   * @example 65e3579de0ca70fe8f2e148e
   */
  menuModuleId: string;
};

export type GetWorkflowByModuleIdError = Fetcher.ErrorWrapper<undefined>;

export type GetWorkflowByModuleIdVariables = {
  pathParams: GetWorkflowByModuleIdPathParams;
  queryParams: GetWorkflowByModuleIdQueryParams;
} & BackendContext["fetcherOptions"];

export const fetchGetWorkflowByModuleId = (
  variables: GetWorkflowByModuleIdVariables,
  signal?: AbortSignal,
) =>
  backendFetch<
    Schemas.WorkflowByMouduleIdResponseDto,
    GetWorkflowByModuleIdError,
    undefined,
    {},
    GetWorkflowByModuleIdQueryParams,
    GetWorkflowByModuleIdPathParams
  >({
    url: "/workflow/workflow-module/{moduleId}",
    method: "get",
    ...variables,
    signal,
  });

export const useGetWorkflowByModuleId = <
  TData = Schemas.WorkflowByMouduleIdResponseDto,
>(
  variables: GetWorkflowByModuleIdVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      Schemas.WorkflowByMouduleIdResponseDto,
      GetWorkflowByModuleIdError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { fetcherOptions, queryOptions, queryKeyFn } =
    useBackendContext(options);
  return reactQuery.useQuery<
    Schemas.WorkflowByMouduleIdResponseDto,
    GetWorkflowByModuleIdError,
    TData
  >({
    queryKey: queryKeyFn({
      path: "/workflow/workflow-module/{moduleId}",
      operationId: "getWorkflowByModuleId",
      variables,
    }),
    queryFn: ({ signal }) =>
      fetchGetWorkflowByModuleId({ ...fetcherOptions, ...variables }, signal),
    ...options,
    ...queryOptions,
  });
};

export type GetWorkflowByIdPathParams = {
  /**
   * id of the workflow
   *
   * @example 65e3579de0ca70fe8f2e148e
   */
  id: string;
};

export type GetWorkflowByIdQueryParams = {
  /**
   * Email address of the user
   *
   * @example mmurugesan@nrl.com.au
   */
  email: string;
  /**
   * Id of the Module
   *
   * @example 65e3579de0ca70fe8f2e148e
   */
  menuModuleId: string;
};

export type GetWorkflowByIdError = Fetcher.ErrorWrapper<undefined>;

export type GetWorkflowByIdVariables = {
  pathParams: GetWorkflowByIdPathParams;
  queryParams: GetWorkflowByIdQueryParams;
} & BackendContext["fetcherOptions"];

export const fetchGetWorkflowById = (
  variables: GetWorkflowByIdVariables,
  signal?: AbortSignal,
) =>
  backendFetch<
    Schemas.WorkflowResponseDto,
    GetWorkflowByIdError,
    undefined,
    {},
    GetWorkflowByIdQueryParams,
    GetWorkflowByIdPathParams
  >({ url: "/workflow/{id}", method: "get", ...variables, signal });

export const useGetWorkflowById = <TData = Schemas.WorkflowResponseDto,>(
  variables: GetWorkflowByIdVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      Schemas.WorkflowResponseDto,
      GetWorkflowByIdError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { fetcherOptions, queryOptions, queryKeyFn } =
    useBackendContext(options);
  return reactQuery.useQuery<
    Schemas.WorkflowResponseDto,
    GetWorkflowByIdError,
    TData
  >({
    queryKey: queryKeyFn({
      path: "/workflow/{id}",
      operationId: "getWorkflowById",
      variables,
    }),
    queryFn: ({ signal }) =>
      fetchGetWorkflowById({ ...fetcherOptions, ...variables }, signal),
    ...options,
    ...queryOptions,
  });
};

export type DeleteWorkFlowByIdPathParams = {
  /**
   * id of the workflow
   *
   * @example 65e3579de0ca70fe8f2e148e
   */
  id: string;
};

export type DeleteWorkFlowByIdQueryParams = {
  /**
   * Email address of the user
   *
   * @example mmurugesan@nrl.com.au
   */
  email: string;
  /**
   * Id of the Module
   *
   * @example 65e3579de0ca70fe8f2e148e
   */
  menuModuleId: string;
};

export type DeleteWorkFlowByIdError = Fetcher.ErrorWrapper<undefined>;

export type DeleteWorkFlowByIdVariables = {
  pathParams: DeleteWorkFlowByIdPathParams;
  queryParams: DeleteWorkFlowByIdQueryParams;
} & BackendContext["fetcherOptions"];

export const fetchDeleteWorkFlowById = (
  variables: DeleteWorkFlowByIdVariables,
  signal?: AbortSignal,
) =>
  backendFetch<
    Schemas.DeleteWorkflowResponseDto,
    DeleteWorkFlowByIdError,
    undefined,
    {},
    DeleteWorkFlowByIdQueryParams,
    DeleteWorkFlowByIdPathParams
  >({ url: "/workflow/{id}", method: "delete", ...variables, signal });

export const useDeleteWorkFlowById = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      Schemas.DeleteWorkflowResponseDto,
      DeleteWorkFlowByIdError,
      DeleteWorkFlowByIdVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useBackendContext();
  return reactQuery.useMutation<
    Schemas.DeleteWorkflowResponseDto,
    DeleteWorkFlowByIdError,
    DeleteWorkFlowByIdVariables
  >({
    mutationFn: (variables: DeleteWorkFlowByIdVariables) =>
      fetchDeleteWorkFlowById({ ...fetcherOptions, ...variables }),
    ...options,
  });
};

export type QueryOperation =
  | {
      path: "/forms/contract/list/{email}";
      operationId: "getFormList";
      variables: GetFormListVariables;
    }
  | {
      path: "/forms/contract/detail/{id}";
      operationId: "getFormDetail";
      variables: GetFormDetailVariables;
    }
  | {
      path: "/forms/contract/history/{id}";
      operationId: "getFormHistory";
      variables: GetFormHistoryVariables;
    }
  | {
      path: "/forms/filter/meta";
      operationId: "getFilterMeta";
      variables: GetFilterMetaVariables;
    }
  | {
      path: "/forms/gmUser/check";
      operationId: "getGMUser";
      variables: GetGMUserVariables;
    }
  | {
      path: "/forms/monetary-value";
      operationId: "fixMonetaryValue";
      variables: FixMonetaryValueVariables;
    }
  | {
      path: "/forms/headcount/list/{email}";
      operationId: "getHeadcountFormList";
      variables: GetHeadcountFormListVariables;
    }
  | {
      path: "/forms/headcount/detail/{id}";
      operationId: "getHeadcountFormDetail";
      variables: GetHeadcountFormDetailVariables;
    }
  | {
      path: "/forms/export/csv";
      operationId: "exportCsvFormDetails";
      variables: ExportCsvFormDetailsVariables;
    }
  | {
      path: "/form-module/list";
      operationId: "getAdminFormModules";
      variables: GetAdminFormModulesVariables;
    }
  | {
      path: "/form-module/detail/{id}";
      operationId: "getFormModuleById";
      variables: GetFormModuleByIdVariables;
    }
  | {
      path: "/form-module/dropdown";
      operationId: "getFormModules";
      variables: GetFormModulesVariables;
    }
  | {
      path: "/departments/list";
      operationId: "getAllDepartmentsAdmin";
      variables: GetAllDepartmentsAdminVariables;
    }
  | {
      path: "/departments/detail/{id}";
      operationId: "getDepartmentById";
      variables: GetDepartmentByIdVariables;
    }
  | {
      path: "/departments/dropdown";
      operationId: "getAllDepartments";
      variables: GetAllDepartmentsVariables;
    }
  | {
      path: "/departments/forms/dropdown/{moduleId}";
      operationId: "getAllDepartmentsByModuleId";
      variables: GetAllDepartmentsByModuleIdVariables;
    }
  | {
      path: "/departments/User/dropdown";
      operationId: "getAllUserDepartments";
      variables: GetAllUserDepartmentsVariables;
    }
  | {
      path: "/permission/list";
      operationId: "getPermissionList";
      variables: GetPermissionListVariables;
    }
  | {
      path: "/permission/detail/{id}";
      operationId: "getPermissionById";
      variables: GetPermissionByIdVariables;
    }
  | {
      path: "/permission/dropdown";
      operationId: "getAllPermissionDropdown";
      variables: GetAllPermissionDropdownVariables;
    }
  | {
      path: "/role/list";
      operationId: "getRoleList";
      variables: GetRoleListVariables;
    }
  | {
      path: "/role/detail/{id}";
      operationId: "getRoleDetailById";
      variables: GetRoleDetailByIdVariables;
    }
  | {
      path: "/role/configurationModules/{moduleId}";
      operationId: "getConfigurationRoleById";
      variables: GetConfigurationRoleByIdVariables;
    }
  | {
      path: "/role/dropdown";
      operationId: "getAllRoles";
      variables: GetAllRolesVariables;
    }
  | {
      path: "/role/dropdown/{id}";
      operationId: "getAllRolesByDeptId";
      variables: GetAllRolesByDeptIdVariables;
    }
  | {
      path: "/document-handler/generate-signedurl";
      operationId: "generateSignedUrl";
      variables: GenerateSignedUrlVariables;
    }
  | {
      path: "/document-handler/files-download";
      operationId: "generateDownload";
      variables: GenerateDownloadVariables;
    }
  | {
      path: "/document-handler/files-fetch";
      operationId: "generatePreSignedUrl";
      variables: GeneratePreSignedUrlVariables;
    }
  | {
      path: "/user/list";
      operationId: "getUserList";
      variables: GetUserListVariables;
    }
  | {
      path: "/user/detail/{id}";
      operationId: "getUserById";
      variables: GetUserByIdVariables;
    }
  | {
      path: "/user/dropdown";
      operationId: "getAllUsersDropdown";
      variables: GetAllUsersDropdownVariables;
    }
  | {
      path: "/user/profile/{email}";
      operationId: "getUserMeta";
      variables: GetUserMetaVariables;
    }
  | {
      path: "/user/impersonate/user/list";
      operationId: "getImpersonateUsersList";
      variables: GetImpersonateUsersListVariables;
    }
  | {
      path: "/workflow/workflow-module/{moduleId}";
      operationId: "getWorkflowByModuleId";
      variables: GetWorkflowByModuleIdVariables;
    }
  | {
      path: "/workflow/{id}";
      operationId: "getWorkflowById";
      variables: GetWorkflowByIdVariables;
    };
