/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppStrictPageRouteImport } from './routes/_app/strict-page'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppLogoutRouteImport } from './routes/_app/logout'
import { Route as AppHomeRouteImport } from './routes/_app/home'
import { Route as AppPageRouteImport } from './routes/_app/$page'
import { Route as AppHeadcountFormsRouteImport } from './routes/_app/headcount/forms'
import { Route as AppHeadcountDashboardRouteImport } from './routes/_app/headcount/dashboard'
import { Route as AppContractFormsRouteImport } from './routes/_app/contract/forms'
import { Route as AppContractDashboardRouteImport } from './routes/_app/contract/dashboard'
import { Route as AppHeadcountConfigurationListRouteImport } from './routes/_app/headcount/configuration/list'
import { Route as AppContractConfigurationListRouteImport } from './routes/_app/contract/configuration/list'
import { Route as AppHeadcountRequestsDetailFormIdRouteImport } from './routes/_app/headcount/requests/detail.$formId'
import { Route as AppHeadcountConfigurationUpdateConfigurationIdRouteImport } from './routes/_app/headcount/configuration/update.$configurationId'
import { Route as AppContractRequestsDetailFormIdRouteImport } from './routes/_app/contract/requests/detail.$formId'
import { Route as AppContractConfigurationUpdateConfigurationIdRouteImport } from './routes/_app/contract/configuration/update.$configurationId'
import { Route as AppFinanceVendorContractRequestsDetailFormIdRouteImport } from './routes/_app/finance/vendor-contract/requests/detail.$formId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppStrictPageRoute = AppStrictPageRouteImport.update({
  id: '/strict-page',
  path: '/strict-page',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppLogoutRoute = AppLogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppPageRoute = AppPageRouteImport.update({
  id: '/$page',
  path: '/$page',
  getParentRoute: () => AppRoute,
} as any)
const AppHeadcountFormsRoute = AppHeadcountFormsRouteImport.update({
  id: '/headcount/forms',
  path: '/headcount/forms',
  getParentRoute: () => AppRoute,
} as any)
const AppHeadcountDashboardRoute = AppHeadcountDashboardRouteImport.update({
  id: '/headcount/dashboard',
  path: '/headcount/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppContractFormsRoute = AppContractFormsRouteImport.update({
  id: '/contract/forms',
  path: '/contract/forms',
  getParentRoute: () => AppRoute,
} as any)
const AppContractDashboardRoute = AppContractDashboardRouteImport.update({
  id: '/contract/dashboard',
  path: '/contract/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppHeadcountConfigurationListRoute =
  AppHeadcountConfigurationListRouteImport.update({
    id: '/headcount/configuration/list',
    path: '/headcount/configuration/list',
    getParentRoute: () => AppRoute,
  } as any)
const AppContractConfigurationListRoute =
  AppContractConfigurationListRouteImport.update({
    id: '/contract/configuration/list',
    path: '/contract/configuration/list',
    getParentRoute: () => AppRoute,
  } as any)
const AppHeadcountRequestsDetailFormIdRoute =
  AppHeadcountRequestsDetailFormIdRouteImport.update({
    id: '/headcount/requests/detail/$formId',
    path: '/headcount/requests/detail/$formId',
    getParentRoute: () => AppRoute,
  } as any)
const AppHeadcountConfigurationUpdateConfigurationIdRoute =
  AppHeadcountConfigurationUpdateConfigurationIdRouteImport.update({
    id: '/headcount/configuration/update/$configurationId',
    path: '/headcount/configuration/update/$configurationId',
    getParentRoute: () => AppRoute,
  } as any)
const AppContractRequestsDetailFormIdRoute =
  AppContractRequestsDetailFormIdRouteImport.update({
    id: '/contract/requests/detail/$formId',
    path: '/contract/requests/detail/$formId',
    getParentRoute: () => AppRoute,
  } as any)
const AppContractConfigurationUpdateConfigurationIdRoute =
  AppContractConfigurationUpdateConfigurationIdRouteImport.update({
    id: '/contract/configuration/update/$configurationId',
    path: '/contract/configuration/update/$configurationId',
    getParentRoute: () => AppRoute,
  } as any)
const AppFinanceVendorContractRequestsDetailFormIdRoute =
  AppFinanceVendorContractRequestsDetailFormIdRouteImport.update({
    id: '/finance/vendor-contract/requests/detail/$formId',
    path: '/finance/vendor-contract/requests/detail/$formId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/$page': typeof AppPageRoute
  '/home': typeof AppHomeRoute
  '/logout': typeof AppLogoutRoute
  '/settings': typeof AppSettingsRoute
  '/strict-page': typeof AppStrictPageRoute
  '/': typeof AppIndexRoute
  '/contract/dashboard': typeof AppContractDashboardRoute
  '/contract/forms': typeof AppContractFormsRoute
  '/headcount/dashboard': typeof AppHeadcountDashboardRoute
  '/headcount/forms': typeof AppHeadcountFormsRoute
  '/contract/configuration/list': typeof AppContractConfigurationListRoute
  '/headcount/configuration/list': typeof AppHeadcountConfigurationListRoute
  '/contract/configuration/update/$configurationId': typeof AppContractConfigurationUpdateConfigurationIdRoute
  '/contract/requests/detail/$formId': typeof AppContractRequestsDetailFormIdRoute
  '/headcount/configuration/update/$configurationId': typeof AppHeadcountConfigurationUpdateConfigurationIdRoute
  '/headcount/requests/detail/$formId': typeof AppHeadcountRequestsDetailFormIdRoute
  '/finance/vendor-contract/requests/detail/$formId': typeof AppFinanceVendorContractRequestsDetailFormIdRoute
}
export interface FileRoutesByTo {
  '/$page': typeof AppPageRoute
  '/home': typeof AppHomeRoute
  '/logout': typeof AppLogoutRoute
  '/settings': typeof AppSettingsRoute
  '/strict-page': typeof AppStrictPageRoute
  '/': typeof AppIndexRoute
  '/contract/dashboard': typeof AppContractDashboardRoute
  '/contract/forms': typeof AppContractFormsRoute
  '/headcount/dashboard': typeof AppHeadcountDashboardRoute
  '/headcount/forms': typeof AppHeadcountFormsRoute
  '/contract/configuration/list': typeof AppContractConfigurationListRoute
  '/headcount/configuration/list': typeof AppHeadcountConfigurationListRoute
  '/contract/configuration/update/$configurationId': typeof AppContractConfigurationUpdateConfigurationIdRoute
  '/contract/requests/detail/$formId': typeof AppContractRequestsDetailFormIdRoute
  '/headcount/configuration/update/$configurationId': typeof AppHeadcountConfigurationUpdateConfigurationIdRoute
  '/headcount/requests/detail/$formId': typeof AppHeadcountRequestsDetailFormIdRoute
  '/finance/vendor-contract/requests/detail/$formId': typeof AppFinanceVendorContractRequestsDetailFormIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/$page': typeof AppPageRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/logout': typeof AppLogoutRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/strict-page': typeof AppStrictPageRoute
  '/_app/': typeof AppIndexRoute
  '/_app/contract/dashboard': typeof AppContractDashboardRoute
  '/_app/contract/forms': typeof AppContractFormsRoute
  '/_app/headcount/dashboard': typeof AppHeadcountDashboardRoute
  '/_app/headcount/forms': typeof AppHeadcountFormsRoute
  '/_app/contract/configuration/list': typeof AppContractConfigurationListRoute
  '/_app/headcount/configuration/list': typeof AppHeadcountConfigurationListRoute
  '/_app/contract/configuration/update/$configurationId': typeof AppContractConfigurationUpdateConfigurationIdRoute
  '/_app/contract/requests/detail/$formId': typeof AppContractRequestsDetailFormIdRoute
  '/_app/headcount/configuration/update/$configurationId': typeof AppHeadcountConfigurationUpdateConfigurationIdRoute
  '/_app/headcount/requests/detail/$formId': typeof AppHeadcountRequestsDetailFormIdRoute
  '/_app/finance/vendor-contract/requests/detail/$formId': typeof AppFinanceVendorContractRequestsDetailFormIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$page'
    | '/home'
    | '/logout'
    | '/settings'
    | '/strict-page'
    | '/'
    | '/contract/dashboard'
    | '/contract/forms'
    | '/headcount/dashboard'
    | '/headcount/forms'
    | '/contract/configuration/list'
    | '/headcount/configuration/list'
    | '/contract/configuration/update/$configurationId'
    | '/contract/requests/detail/$formId'
    | '/headcount/configuration/update/$configurationId'
    | '/headcount/requests/detail/$formId'
    | '/finance/vendor-contract/requests/detail/$formId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$page'
    | '/home'
    | '/logout'
    | '/settings'
    | '/strict-page'
    | '/'
    | '/contract/dashboard'
    | '/contract/forms'
    | '/headcount/dashboard'
    | '/headcount/forms'
    | '/contract/configuration/list'
    | '/headcount/configuration/list'
    | '/contract/configuration/update/$configurationId'
    | '/contract/requests/detail/$formId'
    | '/headcount/configuration/update/$configurationId'
    | '/headcount/requests/detail/$formId'
    | '/finance/vendor-contract/requests/detail/$formId'
  id:
    | '__root__'
    | '/_app'
    | '/_app/$page'
    | '/_app/home'
    | '/_app/logout'
    | '/_app/settings'
    | '/_app/strict-page'
    | '/_app/'
    | '/_app/contract/dashboard'
    | '/_app/contract/forms'
    | '/_app/headcount/dashboard'
    | '/_app/headcount/forms'
    | '/_app/contract/configuration/list'
    | '/_app/headcount/configuration/list'
    | '/_app/contract/configuration/update/$configurationId'
    | '/_app/contract/requests/detail/$formId'
    | '/_app/headcount/configuration/update/$configurationId'
    | '/_app/headcount/requests/detail/$formId'
    | '/_app/finance/vendor-contract/requests/detail/$formId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/strict-page': {
      id: '/_app/strict-page'
      path: '/strict-page'
      fullPath: '/strict-page'
      preLoaderRoute: typeof AppStrictPageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/logout': {
      id: '/_app/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof AppLogoutRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$page': {
      id: '/_app/$page'
      path: '/$page'
      fullPath: '/$page'
      preLoaderRoute: typeof AppPageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/headcount/forms': {
      id: '/_app/headcount/forms'
      path: '/headcount/forms'
      fullPath: '/headcount/forms'
      preLoaderRoute: typeof AppHeadcountFormsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/headcount/dashboard': {
      id: '/_app/headcount/dashboard'
      path: '/headcount/dashboard'
      fullPath: '/headcount/dashboard'
      preLoaderRoute: typeof AppHeadcountDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contract/forms': {
      id: '/_app/contract/forms'
      path: '/contract/forms'
      fullPath: '/contract/forms'
      preLoaderRoute: typeof AppContractFormsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contract/dashboard': {
      id: '/_app/contract/dashboard'
      path: '/contract/dashboard'
      fullPath: '/contract/dashboard'
      preLoaderRoute: typeof AppContractDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/headcount/configuration/list': {
      id: '/_app/headcount/configuration/list'
      path: '/headcount/configuration/list'
      fullPath: '/headcount/configuration/list'
      preLoaderRoute: typeof AppHeadcountConfigurationListRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contract/configuration/list': {
      id: '/_app/contract/configuration/list'
      path: '/contract/configuration/list'
      fullPath: '/contract/configuration/list'
      preLoaderRoute: typeof AppContractConfigurationListRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/headcount/requests/detail/$formId': {
      id: '/_app/headcount/requests/detail/$formId'
      path: '/headcount/requests/detail/$formId'
      fullPath: '/headcount/requests/detail/$formId'
      preLoaderRoute: typeof AppHeadcountRequestsDetailFormIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/headcount/configuration/update/$configurationId': {
      id: '/_app/headcount/configuration/update/$configurationId'
      path: '/headcount/configuration/update/$configurationId'
      fullPath: '/headcount/configuration/update/$configurationId'
      preLoaderRoute: typeof AppHeadcountConfigurationUpdateConfigurationIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contract/requests/detail/$formId': {
      id: '/_app/contract/requests/detail/$formId'
      path: '/contract/requests/detail/$formId'
      fullPath: '/contract/requests/detail/$formId'
      preLoaderRoute: typeof AppContractRequestsDetailFormIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contract/configuration/update/$configurationId': {
      id: '/_app/contract/configuration/update/$configurationId'
      path: '/contract/configuration/update/$configurationId'
      fullPath: '/contract/configuration/update/$configurationId'
      preLoaderRoute: typeof AppContractConfigurationUpdateConfigurationIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance/vendor-contract/requests/detail/$formId': {
      id: '/_app/finance/vendor-contract/requests/detail/$formId'
      path: '/finance/vendor-contract/requests/detail/$formId'
      fullPath: '/finance/vendor-contract/requests/detail/$formId'
      preLoaderRoute: typeof AppFinanceVendorContractRequestsDetailFormIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppPageRoute: typeof AppPageRoute
  AppHomeRoute: typeof AppHomeRoute
  AppLogoutRoute: typeof AppLogoutRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStrictPageRoute: typeof AppStrictPageRoute
  AppIndexRoute: typeof AppIndexRoute
  AppContractDashboardRoute: typeof AppContractDashboardRoute
  AppContractFormsRoute: typeof AppContractFormsRoute
  AppHeadcountDashboardRoute: typeof AppHeadcountDashboardRoute
  AppHeadcountFormsRoute: typeof AppHeadcountFormsRoute
  AppContractConfigurationListRoute: typeof AppContractConfigurationListRoute
  AppHeadcountConfigurationListRoute: typeof AppHeadcountConfigurationListRoute
  AppContractConfigurationUpdateConfigurationIdRoute: typeof AppContractConfigurationUpdateConfigurationIdRoute
  AppContractRequestsDetailFormIdRoute: typeof AppContractRequestsDetailFormIdRoute
  AppHeadcountConfigurationUpdateConfigurationIdRoute: typeof AppHeadcountConfigurationUpdateConfigurationIdRoute
  AppHeadcountRequestsDetailFormIdRoute: typeof AppHeadcountRequestsDetailFormIdRoute
  AppFinanceVendorContractRequestsDetailFormIdRoute: typeof AppFinanceVendorContractRequestsDetailFormIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppPageRoute: AppPageRoute,
  AppHomeRoute: AppHomeRoute,
  AppLogoutRoute: AppLogoutRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStrictPageRoute: AppStrictPageRoute,
  AppIndexRoute: AppIndexRoute,
  AppContractDashboardRoute: AppContractDashboardRoute,
  AppContractFormsRoute: AppContractFormsRoute,
  AppHeadcountDashboardRoute: AppHeadcountDashboardRoute,
  AppHeadcountFormsRoute: AppHeadcountFormsRoute,
  AppContractConfigurationListRoute: AppContractConfigurationListRoute,
  AppHeadcountConfigurationListRoute: AppHeadcountConfigurationListRoute,
  AppContractConfigurationUpdateConfigurationIdRoute:
    AppContractConfigurationUpdateConfigurationIdRoute,
  AppContractRequestsDetailFormIdRoute: AppContractRequestsDetailFormIdRoute,
  AppHeadcountConfigurationUpdateConfigurationIdRoute:
    AppHeadcountConfigurationUpdateConfigurationIdRoute,
  AppHeadcountRequestsDetailFormIdRoute: AppHeadcountRequestsDetailFormIdRoute,
  AppFinanceVendorContractRequestsDetailFormIdRoute:
    AppFinanceVendorContractRequestsDetailFormIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
